### PR TITLE
Fix S3 Remote State Backend Validation

### LINKED ISSUE #875: Failed to read terraform_remote_state data
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha5
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
data "terraform_remote_state" "vpc" {
  backend = "s3"
  config = {
    region = "us-west-2"
    bucket = "terragrunt-test-bucket-2ttejd"
    key    = "mgmt/vpc/terraform.tfstate"
  }
}

```

### Debug Output

https://gist.github.com/denis256/341a3042d60cd885d3fc918446acce2d

### Expected Behavior

Read remote state as data

Terraform is reading it, Tofu fails

### Actual Behavior

╷
│ Error: Invalid backend configuration
│ 
│   with data.terraform_remote_state.vpc,
│   on main.tf line 3, in data "terraform_remote_state" "vpc":
│    3:   config = {
│    4:     region = "us-west-2"
│    5:     bucket = "terragrunt-test-bucket-2ttejd"
│    6:     key    = "mgmt/vpc/terraform.tfstate"
│    7:   }
│ 
│ The given configuration is not valid for backend "s3": attribute "assume_role" is required.

### Steps to Reproduce

1. tofu init
2. tofu plan

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
This is the first part of #875 and fixes the main issue reported.  The schema validation for backends has two paths, one from data blocks, the other from backend blocks.  At the moment, backend blocks pre-populates empty maps as shown in the issue.  This will be fixed in a followup PR.

This PR fixes the schema optional fields, adds a test for the minimum set of fields required, and also improves the user facing errors when they are missing multiple fields (stable key sort).

Resolves #875

## Target Release

1.6.0

### CODE REVIEW

File: internal/configs/configschema/coerce_value.go [hunk 1]
```diff
@@ -57,7 +58,15 @@ func (b *Block) coerceValue(in cty.Value, path cty.Path) (cty.Value, error) {
 
 	attrs := make(map[string]cty.Value)
 
-	for name, attrS := range b.Attributes {
+	// Stable sort keys for consistent error reports
```
Comment (cube2222) [inline internal/configs/configschema/coerce_value.go:61]: The second instance of this makes sense, but in this case no errors are possible, so I'd leave it out.

File: internal/configs/configschema/coerce_value.go [hunk 2]
```diff
@@ -78,7 +87,15 @@ func (b *Block) coerceValue(in cty.Value, path cty.Path) (cty.Value, error) {
 		attrs[name] = val
 	}
 
-	for typeName, blockS := range b.BlockTypes {
+	// Stable sort keys for consistent error reports
```
Comment (cube2222) [inline internal/configs/configschema/coerce_value.go:90]: I'm kind of split on this.

On the one hand, consistent error messages make sense.

On the other hand, this will require an effort on our side in all such places in the codebase (I expect there to be a bunch) and I'm not sure the (very limited imo) value is worth the effort.

On the other other hand, we could also use Diagnostics here instead of failing on the first error. Basically, before the for loop create a diagnostics struct, and then append the errors to it, continuing the loop. This way we'll get all the errors. But if this is the approach we wanna take, I'd put in an issue and delay it past the stable release.

Comment (kislerdm) [reply internal/configs/configschema/coerce_value.go:90]: I see the value in collecting all error messages. It's especially useful when user validates the configuration using `tofu validate`.

File: internal/configs/configschema/coerce_value.go (hunk 1 above)
Comment (cam72cam) [reply internal/configs/configschema/coerce_value.go:61]: I don't follow, attrs are the main error path in the linked ticket?

File: internal/configs/configschema/coerce_value.go (hunk 2 above)
Comment (cam72cam) [reply internal/configs/configschema/coerce_value.go:90]: I think that wherever we are iterating through maps where there are user facing messages, we should try to sort if possible.  I see this as an ongoing cleanup when we encounter it.

As far as tfdialogs,  I think that's the right long term solution, but it might drastically baloon the scope of this bugfix.  I'll take a look into it this morning and give a rough estimate on how hard it would be.  Alternatively I could return a more complex error type as a stopgap.

Comment (cam72cam) [reply internal/configs/configschema/coerce_value.go:90]: It's definitely a non-trivial amount of work to introduce a complex error type / diags and make sure functionality is not broken.  I'm going to recommend we keep the sort and add a ticket to the backlog.

File: internal/configs/configschema/coerce_value.go (hunk 1 above)
Comment (cube2222) [reply internal/configs/configschema/coerce_value.go:61]: my bad, github collapsed the relevant part

File: internal/configs/configschema/coerce_value.go (hunk 2 above)
Comment (cam72cam) [reply internal/configs/configschema/coerce_value.go:90]: Created https://github.com/opentofu/opentofu/issues/881 to track the follow up work proposed here.

File: internal/configs/configschema/coerce_value.go (hunk 1 above)
Comment (cam72cam) [reply internal/configs/configschema/coerce_value.go:61]: Spoke with @cube2222, simple misunderstanding.

File: internal/configs/configschema/coerce_value.go (hunk 2 above)
Comment (cam72cam) [reply internal/configs/configschema/coerce_value.go:90]: The remaining question is should we back out the stable sort to be consistent or set precedence that we fix these when we encounter them, either with a stable sort or better use of tfdiags/complex errors

**Review by cube2222 — APPROVED** [review]

File: internal/configs/configschema/coerce_value.go (hunk 2 above)
Comment (cube2222) [reply internal/configs/configschema/coerce_value.go:90]: > I think that wherever we are iterating through maps where there are user facing messages, we should try to sort if possible.

I don't care too much either way, so happy to do it the way you propose

**Review by kislerdm — APPROVED** [review]
