### PR TITLE
Reduce calls to ListKey in azure backend

### LINKED ISSUE #3047: 429 Too Many Requests when using Azure as remote state backend
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
v1.10.3 on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "azurerm" {
    container_name       = "DEDUCTED"
    key                  = "*path relative to include*/terraform.tfstate"
    resource_group_name  = "DEDUCTED"
    storage_account_name = "DEDUCTED"
    subscription_id      = "DEDUCTED"
  }
}

```

### Debug Output

```
  ╷
  │ Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "DEDUCTED": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=429 -- Original Error: autorest/azure: Service returned an error. Status=429 Code="TooManyRequests" Message="The request is being throttled as the limit has been reached for operation type - Read_ObservationWindow_00:05:00. For more information, see - https://aka.ms/srpthrottlinglimits"
  │ 
  │ 
  ╵
```

### Expected Behavior

Tofu should manage to make requests to Azure in a way, which doesn't lead to the execution erroring because of 429 responses.

### Actual Behavior

Tofu returns an error. This doesn't happen when using Terraform instead of Tofu with the exact same configuration.

### Steps to Reproduce

It happens when using a big infrastructure in terragrunt with an azure storage account as the remote state backend. It seems as though the amount of requests made to Azure to fetch the `.tfstate` for every Tofu module leads to the 429. Apparently terraform has some form of protection against it, that tofu is missing.

### Additional Context

We're using terragrunt and configured `${path_relative_to_include()}/terraform.tfstate` as the key for the remote state. Maybe this could be relevant, as it leads to Tofu requesting a different file for every execution. However, it might also be unrelated because Tofu would probably do the same amount of requests per instance, even if terragrunt always configured the same remote config.

It should also be mentioned that this doesn't happen all the time, but often enough to cause a lot of trouble. I tried using `terragrunt init --all` on an infrastructure with ~400-500 modules and it happens on maybe 30% of tries. In those cases however, it completely screws the execution, resulting in sometimes even almost all units failing.

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
Only calls ListKeys once in the azure backend to reduce likelihood of rate limiting.

Tests on main are bork'd so this is waiting on another PR to fix those.

Resolves #3047

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/backend/remote-state/azure/arm_client.go [hunk 1]
```diff
@@ -30,14 +30,11 @@ type ArmClient struct {
 	groupsClient          *resources.GroupsClient
 	storageAccountsClient *armStorage.AccountsClient
 
-	// azureAdStorageAuth is only here if we're using AzureAD Authentication but is an Authorizer for Storage
-	azureAdStorageAuth *autorest.Authorizer
+	// storageAuth is set to build the clients below
```
Comment (yottta) [inline internal/backend/remote-state/azure/arm_client.go]:
```suggestion
	// storageAuth stores the authentication mechanism to be used later when building the clients to interact with the Azure Services.
	// This is initialised once when the backend is created and then reused for each subsequent calls on the services.
```

Just a suggestion 🤷

**Review by yottta — DISMISSED** [review]
Great catch!
For me, the functionality looks to be equivalent with the one before, obviously except the initialisation of the `storageAuth`.

File: internal/backend/remote-state/azure/arm_client.go [hunk 2]
```diff
@@ -123,119 +128,56 @@ func buildArmClient(ctx context.Context, config BackendConfig) (*ArmClient, erro
...
-		storageAuth, err := autorest.NewSASTokenAuthorizer(c.sasToken)
-		if err != nil {
-			return nil, fmt.Errorf("Error building SAS Token Authorizer: %w", err)
-		}
-
-		blobsClient := blobs.NewWithEnvironment(c.environment)
-		c.configureClient(&blobsClient.Client, storageAuth)
-		return &blobsClient, nil
+	log.Printf("[DEBUG] Building the Arm Client from an Access Token (using user credentials)")
+	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(20)*time.Second)
```
Comment (Yantrio) [inline internal/backend/remote-state/azure/arm_client.go]: Should we use the `timeoutSeconds` value here?

File: internal/backend/remote-state/azure/arm_client.go [hunk 3]
```diff
@@ -123,119 +128,56 @@ func buildArmClient(ctx context.Context, config BackendConfig) (*ArmClient, erro
...
-	if accessKey == "" {
-		log.Printf("[DEBUG] Building the Blob Client from an Access Token (using user credentials)")
-		timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(c.timeoutSeconds)*time.Second)
-		defer cancel()
-		keys, err := c.storageAccountsClient.ListKeys(timeoutCtx, c.resourceGroupName, c.storageAccountName, "")
-		if err != nil {
-			return nil, fmt.Errorf("Error retrieving keys for Storage Account %q: %w", c.storageAccountName, err)
-		}
+	accessKeys := *keys.Keys
+	accessKey := *accessKeys[0].Value
```
Comment (Yantrio) [inline internal/backend/remote-state/azure/arm_client.go]: Should the if check here also check for an empty set of keys being returned?

**Review by Yantrio — CHANGES_REQUESTED** [review]
LGTM just 2 small nitpicks
