### PR TITLE
fix: remove OPENTOFU_USER_AGENT

### LINKED ISSUE #3864: Remove undocumented OPENTOFU_USER_AGENT environment variable
> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

## OpenTofu Version

All versions since 1.6.0-alpha (introduced as `OPENTF_USER_AGENT` in PR #186, renamed in PR #467).

## Issue

OpenTofu has an undocumented `OPENTOFU_USER_AGENT` environment variable that **completely replaces** the entire User-Agent string sent by OpenTofu core. This was added during the early OpenTF fork days (Aug 2023, issue #183) as part of a quick UA refactor, but was never documented or announced.

This is problematic because:

1. **It's undocumented** — it doesn't appear anywhere in the website docs, CLI help, or environment variable reference.
2. **It's dangerous** — unlike `TF_APPEND_USER_AGENT` which safely appends, this replaces the entire UA string.
3. **It only affects OpenTofu core** — providers use the Terraform Plugin SDK, which only reads `TF_APPEND_USER_AGENT`. So `OPENTOFU_USER_AGENT` gives a false sense of control.
4. **Nobody is using it** — a GitHub-wide code search shows zero usage outside of OpenTofu's own source code and forks/vendored copies of the same file.

## Attempted Solutions

`TF_APPEND_USER_AGENT` already covers the legitimate use case (adding custom identifiers to the UA string) and works with both OpenTofu core and providers.

## Proposal

Remove the `OPENTOFU_USER_AGENT` env var handling from `internal/httpclient/useragent.go` and its tests in `useragent_test.go`.

## Workarounds and Alternatives

-

## References

- #183 — Original issue: "Rename user agents"
- #186 — PR that introduced `OPENTF_USER_AGENT`
- #467 — PR that renamed it to `OPENTOFU_USER_AGENT`
- #2954 — Related: `TF_APPEND_USER_AGENT` causing S3 backend SSO issues

### PR DESCRIPTION
**Pull request by KrishnaSindhur**
which replaces the entire default UA and undocumented

Resolves #3864 

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by Yantrio** [comment]
@KrishnaSindhur Can you please add a changelog entry for this? Just incase someone is relying on the usage of this environment variable. 

Thanks!

File: internal/httpclient/useragent_test.go [hunk 1]
```diff
@@ -72,51 +72,30 @@ func TestUserAgentAppendViaEnvVar(t *testing.T) {
 		})
 	}
 }
-func TestCustomUserAgentViaEnvVar(t *testing.T) {
 
-	appendUaVal := os.Getenv(appendUaEnvVar)
-	os.Unsetenv(appendUaEnvVar)
-	defer os.Setenv(appendUaEnvVar, appendUaVal)
+func TestCustomUserAgentEnvVarIgnored(t *testing.T) {
```
Comment (cam72cam) [inline internal/httpclient/useragent_test.go]: The changes here removes an existing test for appendUaEnvVar and hacks together a test for removedCustomUAEnvVar, which we have removed all code for.  That is incorrect.

This should leave the existing useful test and remove any test associated with customUAEnvVar

Comment (cam72cam) [reply internal/httpclient/useragent_test.go]: Now that I read this again, I still stand by that we should not be adding tests for removed functionality, but was incorrect in determining that one the two TestCustom* should be preserved.
