### PR TITLE
Fix crash with sensitive for_each set elements

### LINKED ISSUE #3065: Crash if `for_each` has a Set with sensitive values
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
❯ tofu --version                                                                                                
OpenTofu v1.10.2
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v6.3.0
```

### OpenTofu Configuration Files

```hcl
data "aws_ssm_parameter" "public_subnet_ids" {
  name = "/tf/${local.account_name}/vpc/${local.env}/public_subnet_ids"
}

data "aws_subnet" "public_subnets" {
  for_each = toset(split(",", data.aws_ssm_parameter.public_subnet_ids.value))
  id       = each.value
}
```

### Debug Output

Available upon request, though it is repeatable without my specific setup.

### Expected Behavior

Plan succeeds.

### Actual Behavior

```
data.aws_ssm_parameter.public_subnet_ids: Read complete after 0s [id=/tf/xxx-account-name-xxx/vpc/nonprod/public_subnet_ids]

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 42698 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x64
runtime/debug.PrintStack()
        runtime/debug/stack.go:18 +0x1c
github.com/opentofu/opentofu/internal/logging.panicHandler({0x105210a00, 0x105895ed0}, {0x1400be9f800, 0x6c3, 0x800})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xc0
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.PanicHandlerWithTraceFn.func2()
        github.com/opentofu/opentofu/internal/logging/panic.go:82 +0x88
panic({0x105210a00?, 0x105895ed0?})
        runtime/panic.go:792 +0x124
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        github.com/zclconf/go-cty@v1.16.3/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.ElementIterator({{{0x1058d9fc0?, 0x14006bea470?}}, {0x10551b4c0?, 0x1400bb5d338?}})
        github.com/zclconf/go-cty@v1.16.3/cty/value_ops.go:1214 +0x54
github.com/opentofu/opentofu/internal/lang/evalchecks.performSetValueChecks({0x1058da278, 0x140009a4690}, 0x1400bb5cab0, {{{0x1058d9fc0?, 0x14006bea470?}}, {0x10551b4c0?, 0x1400bb5d338?}})
        github.com/opentofu/opentofu/internal/lang/evalchecks/eval_for_each.go:228 +0x90
github.com/opentofu/opentofu/internal/lang/evalchecks.performTypeAndValueChecks({0x1058da278, 0x140009a4690}, 0x1400bb5cab0, 0x0, 0x0, {{{0x1058d9fc0?, 0x14006bea470?}}, {0x10551b4c0?, 0x1400bb5d338?}}, {0x1058d9478, ...})
        github.com/opentofu/opentofu/internal/lang/evalchecks/eval_for_each.go:106 +0x170
github.com/opentofu/opentofu/internal/lang/evalchecks.EvaluateForEachExpressionValue({0x1058da278, 0x140009a4690}, 0x140086232f0, 0x0, 0x0, {0x1058d9478, 0x1400bb673c0})
        github.com/opentofu/opentofu/internal/lang/evalchecks/eval_for_each.go:86 +0x300
github.com/opentofu/opentofu/internal/lang/evalchecks.EvaluateForEachExpression({0x1058da278?, 0x140009a4690?}, 0x40?, {0x1058d9478?, 0x1400bb673c0?})
        github.com/opentofu/opentofu/internal/lang/evalchecks/eval_for_each.go:43 +0x3c
github.com/opentofu/opentofu/internal/tofu.evaluateForEachExpression({0x1058da278, 0x140009a4690}, {0x1058f9628?, 0x1400bca4700?}, {0x1058d9478, 0x1400bb673c0})
        github.com/opentofu/opentofu/internal/tofu/eval_expansion.go:36 +0x54
github.com/opentofu/opentofu/internal/tofu.(*NodeAbstractResource).writeResourceState(0x140047358c8, {0x1058f9628, 0x1400bca4700}, {{}, {0x0, 0x0, 0x0}, {{}, 0x44, {0x14000c94640, ...}, ...}})
        github.com/opentofu/opentofu/internal/tofu/node_resource_abstract.go:519 +0xcc
github.com/opentofu/opentofu/internal/tofu.(*nodeExpandPlannableResource).expandResourceInstances(0x140030e44b0, {0x1058d9280, 0x107386800}, {0x1058f9628?, 0x140035a2800?}, {{}, {0x0, 0x0, 0x0}, {{}, ...}}, ...)
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan.go:224 +0xd0
github.com/opentofu/opentofu/internal/tofu.(*nodeExpandPlannableResource).DynamicExpand(0x140030e44b0, {0x1058f9628, 0x140035a2800})
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan.go:181 +0x4b4
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x1057dedc0, 0x140030e44b0})
        github.com/opentofu/opentofu/internal/tofu/graph.go:95 +0x460
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x1400246e660, {0x1057dedc0, 0x140030e44b0}, 0x14007840400)
        github.com/opentofu/opentofu/internal/dag/walk.go:386 +0x2a8
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 30714
        github.com/opentofu/opentofu/internal/dag/walk.go:309 +0xc44
With go-routine called from:
goroutine 30714 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x64
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
        github.com/opentofu/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk(0x1400e95ea40, {0x1058d9328, 0x1400a2159b0}, {0x1058da358, 0x140076da5a0})
        github.com/opentofu/opentofu/internal/tofu/graph.go:50 +0x48
github.com/opentofu/opentofu/internal/tofu.(*Graph).Walk(...)
        github.com/opentofu/opentofu/internal/tofu/graph.go:39
github.com/opentofu/opentofu/internal/tofu.(*Context).walk(0x14000548c60, {0x1058d9328, 0x1400a2159b0}, 0x1400e95ea40, 0x2, 0x14002423928)
        github.com/opentofu/opentofu/internal/tofu/context_walk.go:61 +0xf4
github.com/opentofu/opentofu/internal/tofu.(*Context).planWalk(0x14000548c60, {0x1058d9328, 0x1400a2159b0}, 0x14000ce0a80, 0x140028a3ca0, 0x1400296a8f0)
        github.com/opentofu/opentofu/internal/tofu/context_plan.go:794 +0x39c
github.com/opentofu/opentofu/internal/tofu.(*Context).plan(0x14000548c60, {0x1058d9328, 0x1400a2159b0}, 0x14000ce0a80, 0x140028a3ca0, 0x1400296a8f0)
        github.com/opentofu/opentofu/internal/tofu/context_plan.go:363 +0x358
github.com/opentofu/opentofu/internal/tofu.(*Context).Plan(0x14000548c60, {0x1058d9398, 0x14000d6ae70}, 0x14000ce0a80, 0x140028a3ca0, 0x1400296a8f0)
        github.com/opentofu/opentofu/internal/tofu/context_plan.go:236 +0xa28
github.com/opentofu/opentofu/internal/backend/local.(*Local).opPlan.func2()
        github.com/opentofu/opentofu/internal/backend/local/backend_plan.go:120 +0xf8
created by github.com/opentofu/opentofu/internal/backend/local.(*Local).opPlan in goroutine 116
        github.com/opentofu/opentofu/internal/backend/local/backend_plan.go:116 +0x6a4
```

### Steps to Reproduce

1. `tofu plan -out tfplan`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
Will need to be backported to 1.10, originated in the rewrite of for_each https://github.com/opentofu/opentofu/pull/2597

Resolves #3065 

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/lang/evalchecks/eval_for_each.go [hunk 1]
```diff
@@ -225,6 +225,7 @@ func performSetValueChecks(expr hcl.Expression, hclCtx *hcl.EvalContext, forEach
 
 	// A set of strings may contain null, which makes it impossible to
 	// convert to a map, so we must return an error
+	forEachVal, _ = forEachVal.UnmarkDeep()
```
Comment (apparentlymart) [inline internal/lang/evalchecks/eval_for_each.go]: I don't think it's correct to return the unmarked version of this value, because the caller of this function then passes the returned value on to another function:

https://github.com/opentofu/opentofu/blob/131b1456cae9c3359148c6b93b909b880e1bd739/internal/lang/evalchecks/eval_for_each.go#L105-L109

...and then that function wants to reject attempts to use a sensitive value:

https://github.com/opentofu/opentofu/blob/131b1456cae9c3359148c6b93b909b880e1bd739/internal/lang/evalchecks/eval_for_each.go#L172-L185

To make sure this change can't affect anything beyond fixing the bug as reported, I'd suggest that we instead change the following line to `it := forEachVal.UnmarkDeep().ElementIterator()`, so that the mark will still be present in all of the other places it previously was.

Comment (cam72cam) [reply internal/lang/evalchecks/eval_for_each.go]: Fixed in [634ca05](https://github.com/opentofu/opentofu/pull/3070/commits/634ca0570a2e6cc23435376f0d3b803a322e8ec9)

**Comment by diofeher** [comment]
@apparentlymart I was having a discussion with the team on how we didn't have this problem before, and it was basically because I moved this check around to the `valueChecks` function:

https://github.com/opentofu/opentofu/blob/main/internal/lang/evalchecks/eval_for_each.go#L174

So for collections, the check for sensitive values were missing. We had this check on the beginning of the checks before:

https://github.com/opentofu/opentofu/blob/v1.9/internal/lang/evalchecks/eval_for_each.go#L74

So a possible solution would be to move back to the top level of the checks, putting it here:
https://github.com/opentofu/opentofu/blob/main/internal/lang/evalchecks/eval_for_each.go#L100

Or just check again in that point:

https://github.com/opentofu/opentofu/blob/main/internal/lang/evalchecks/eval_for_each.go#L213

**Comment by cam72cam** [comment]
@apparentlymart added the suggested test

**Comment by cam72cam** [comment]
@diofeher we only care if the keys are sensitive.  That is a top level concern, except for the very narrow set case which is now fully tested.

**Review by apparentlymart — APPROVED** [review]
