### PR TITLE
Render write-only attributes after rendered all of the other attributes

### LINKED ISSUE #3640: `tofu plan` with resources containing write-only attributes generate inconsistent output across multiple runs
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.11.2
on linux_amd64
+ provider registry.opentofu.org/hashicorp/kubernetes v3.0.1
```

reproduces on latest main (4958feb) build, too

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    kubernetes = {
      source  = "registry.opentofu.org/hashicorp/kubernetes"
      version = "3.0.1"
    }
  }

  required_version = ">= 1.11"
}

provider "kubernetes" {}


resource "kubernetes_namespace_v1" "test" {
  metadata {
    name = "dbg-tofu-wo"
  }
}

resource "kubernetes_secret_v1" "test" {
    count = 5
    metadata {
        name      = "dbg-secret-${count.index}"
        namespace = kubernetes_namespace_v1.test.metadata[0].name
    }

    data = {
        test = "a"
    }
}
```

### Debug Output

https://gist.github.com/sberz/3fcc0e93fafc1974c172f9a6e6aa14ad (Kubernetes cluster credentials have been replaced with `[REDACTED]`)

### Expected Behavior

Only the changed field (data) should get updated

### Actual Behavior

The write-only attributes (`data_wo` and `binary_data_wo`) randomly marked as updated as well

e.g.:
```hcl
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place (current -> planned)

OpenTofu will perform the following actions:

  # kubernetes_secret_v1.test[0] will be updated in-place
  ~ resource "kubernetes_secret_v1" "test" {
      ~ binary_data_wo                 = (write-only attribute)
      ~ data                           = (sensitive value)
      ~ data_wo                        = (write-only attribute)
        id                             = "dbg-tofu-wo/dbg-secret-0"
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # kubernetes_secret_v1.test[1] will be updated in-place
  ~ resource "kubernetes_secret_v1" "test" {
      ~ binary_data_wo                 = (write-only attribute)
      ~ data                           = (sensitive value)
      ~ data_wo                        = (write-only attribute)
        id                             = "dbg-tofu-wo/dbg-secret-1"
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # kubernetes_secret_v1.test[2] will be updated in-place
  ~ resource "kubernetes_secret_v1" "test" {
      ~ data                           = (sensitive value)
      ~ data_wo                        = (write-only attribute)
        id                             = "dbg-tofu-wo/dbg-secret-2"
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # kubernetes_secret_v1.test[3] will be updated in-place
  ~ resource "kubernetes_secret_v1" "test" {
      ~ data                           = (sensitive value)
        id                             = "dbg-tofu-wo/dbg-secret-3"
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # kubernetes_secret_v1.test[4] will be updated in-place
  ~ resource "kubernetes_secret_v1" "test" {
      ~ data                           = (sensitive value)
      ~ data_wo                        = (write-only attribute)
        id                             = "dbg-tofu-wo/dbg-secret-4"
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 5 to change, 0 to destroy.

```

### Steps to Reproduce

1. `tofu init`
2. `tofu apply`
3. Change the secrets data (e.g. `test = "b"`)
4. `tofu plan` (optional: run `tofu plan` multiple times to watch the plan change randomly every single time)

If no Kubernetes cluster is available, the simplest way to create one is by using kind (https://kind.sigs.k8s.io/):
```shell
kind create cluster --name tofu-dbg --kubeconfig ./kubeconfig-tofu-dbg.yaml
export KUBE_CONFIG_PATH=./kubeconfig-tofu-dbg.yaml
```

### Additional Context
This happens on multiple different resources from different providers (`aws_rds_cluster`, `helm_release`, `kubernetes_secret`, etc.) so this seems like a OpenTofu bug rather than provider bug (or every provider I use has the exact same bug)

This mostly affects our CI/CD piplelines as the plan changes on every single run and therefore rejects the apply due to changes of the plan

### References

- https://github.com/dflook/terraform-github-actions/issues/414

### PR DESCRIPTION
**Pull request by yottta**
Write-only attributes need to be rendered only when there is at least one regular attribute changed. 
To know that, during generating diffs for attributes, we track the "action" of the whole block (update/create/delete/etc). 
That action is updated based on the diff of each attribute of the processed resource. 
So if the resource exists and an attribute value changes, then it change the resource action to "update".

Since there is no value for the write-only attributes (not in the state nor in the plan), the "action" of such an attribute will always be the action of the whole resource block.

Before this change, we were processing **all of the attributes of a block in one go**, iterating over the `block.Attributes` map. 
Since a map in golang is unordered, the "action" that was given into the diffs for write-only attributes was dependant on what other attributes were processed before that attribute. 
In other words, between multiple plan executions, the rendered plan would have been different just because of the order of iteration over the map of attributes.

Now, we separated the process of generating diffs for a block in 2 steps:
1. process all the non write-only attributes **first**, to settle on a clear action of the block 
2. process the write-only attributes **only,** which now will all have the action of the block

---

To check the correctness of this, I added a test in the first commit of this PR so you can just checkout the branch, run `git reset --hard HEAD~1` and then you can run that test in a loop to see how it fails randomly:
```shell
while true; do go test github.com/opentofu/opentofu/internal/command/jsonformat/differ -run "^\QTestValue_SimpleBlocks\E$" -count=1; done
```
Then you can `git pull` and run that test again to see if it fails again.

Resolves #3640 

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [ ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [ ] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [ ] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/command/jsonformat/differ/differ_test.go [hunk 1]
```diff
@@ -166,6 +166,66 @@ func TestValue_SimpleBlocks(t *testing.T) {
...
+						AttributeType: unmarshalType(t, cty.String),
+						WriteOnly:     true,
+					},
+					"write_only_attribute4": {
+						AttributeType: unmarshalType(t, cty.String),
+						WriteOnly:     true,
+					},
+				},
+				BlockTypes: map[string]*jsonprovider.BlockType{
+					"nested_with_write_only": {
```
Comment (Gogotchuri) [inline internal/command/jsonformat/differ/differ_test.go:208]: There is no validation below for this nested block

Comment (yottta) [reply internal/command/jsonformat/differ/differ_test.go:208]: Because that's not meant to appear in the diff. Do you think that would worth a comment here to make it clear?

Comment (Gogotchuri) [reply internal/command/jsonformat/differ/differ_test.go:208]: Ah, right. All good then, missed it.
