### PR TITLE
MakeStaticTimestampFunc now returns unknown value if the given time.Time is zero

### LINKED ISSUE #2397: At plan time, plantimestamp should be considered unknown, and instead of some default value
### OpenTofu Version

```shell
1.9.0
```

### OpenTofu Configuration Files

```hcl
locals {
  first_year = 2023
  current_timestamp = plantimestamp()
}

output "table_years" {
  value = toset(
    [
      for year in range(local.first_year, tonumber(formatdate("YYYY", local.current_timestamp)) + 2) : tostring(year)
    ]
  )
}
```

### Debug Output

.

### Expected Behavior

Plan should result in an unknown output. Apply should work and create an output

### Actual Behavior

Plan fails, because at plan time a default `"0001-01-01T00:00:00Z"` is used in place of `plantimestamp()`

```
╷
│ Error: Error in function call
│ 
│   on main.tf line 11, in output "table_years":
│   11:       for year in range(local.first_year, tonumber(formatdate("YYYY", local.current_timestamp)) + 2) : tostring(year)
│     ├────────────────
│     │ while calling range(params...)
│     │ local.current_timestamp is "0001-01-01T00:00:00Z"
│     │ local.first_year is 2023
│ 
│ Call to function "range" failed: more than 1024 values were generated; either decrease the difference between start and end or use a smaller step.
╵

```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### Additional Context

_No response_

### References

Terraform Issue where the bug was originally documented: https://github.com/hashicorp/terraform/issues/35898

### PR DESCRIPTION
**Pull request by yottta**
Resolves #2397

## Target Release

1.10.0
1.9.0
1.8.0
1.7.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/backend/local/backend_plan_test.go [hunk 1]
```diff
@@ -161,6 +161,39 @@ func TestLocal_plan_context_error(t *testing.T) {
 	}
 }
 
+// Ensure that the plantimestamp() call is not affecting the validation step during planning.
+func TestLocal_plan_range_over_zero_plan_timestamp(t *testing.T) {
```
Comment (cam72cam) [inline internal/backend/local/backend_plan_test.go:165]: This test should probably be a TestContext2Validate test instead, in context_validate test.

**Review by cam72cam — APPROVED** [review]

File: internal/tofu/context_validate_test.go [hunk 2]
```diff
@@ -2488,3 +2488,21 @@ locals {
 		t.Fatalf("expected deprecated warning, got: %q\n", warn)
 	}
 }
+
+// Ensure that the plantimestamp() call is not affecting the validation step.
+func TestContext2Validate_range_over_zero_plan_timestamp(t *testing.T) {
```
Comment (ollevche) [inline internal/tofu/context_validate_test.go:2493]: nit: I am a bit confused by the naming in this file, however I believe it should be:

```suggestion
func TestContext2Validate_rangeOverZeroPlanTimestamp(t *testing.T) {
```

**Review by ollevche — DISMISSED** [review]
Looks good, thank you! Left a minor nit comment

File: internal/tofu/context_validate_test.go (hunk 2 above)
Comment (yottta) [reply internal/tofu/context_validate_test.go]: https://github.com/opentofu/opentofu/commit/f46251f9d02a84e51a589a2284b6496db8fe2d9c

**Review by cam72cam — APPROVED** [review]
