### PR TITLE
fix: `showSensitive` working for provisioners output

### LINKED ISSUE #3927: local-exec output suppressed even with -show-sensitive
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.11.5
on linux_amd64
+ provider registry.opentofu.org/hashicorp/null v3.2.4
+ provider registry.opentofu.org/hashicorp/random v3.8.1
```

### OpenTofu Configuration Files

```hcl
resource "random_password" "session_token" {
  length  = 22
  special = false
}

resource "null_resource" "demo" {
  provisioner "local-exec" {
    command = "echo 'Transient Token Length: ${length(random_password.session_token.result)}'"
    environment = {
      TOKEN = random_password.session_token.result
    }
  }
}
```

### Debug Output

```
% tofu apply -show-sensitive
(...)
random_password.session_token: Creating...
random_password.session_token: Creation complete after 0s [id=none]
null_resource.demo: Creating...
null_resource.demo: Provisioning with 'local-exec'...
null_resource.demo (local-exec): (output suppressed due to sensitive value in config)
null_resource.demo (local-exec): (output suppressed due to sensitive value in config)
null_resource.demo: Creation complete after 0s [id=5346491974677561093]
```

Trace logs for the same:

[tofu.log](https://github.com/user-attachments/files/26189125/tofu.log)

### Expected Behavior

Since the `-show-sensitive` flag is provided, I would expect sensitive output to be displayed.

### Actual Behavior

Sensitive output is displayed in the plan, but not in local-exec output during the apply step.

### Steps to Reproduce

1. `tofu init`
2. `tofu apply -show-sensitive`

### Additional Context

I checked the source of the message `output suppressed due to sensitive value in config` and found it here:

https://github.com/opentofu/opentofu/blob/e4c8e4fe80893b35631933bea8c18b92d2459045/internal/tofu/node_resource_abstract_instance.go#L2728

Based on that code reference, I concluded this is behavior of OpenTofu itself rather than anything in an external provider.

### References

_No response_

### PR DESCRIPTION
**Pull request by diofeher**
Alternative implementation of #3930, as requested by @yottta. We can compare the implementations here.

Resolves #3927

I checked passing showSensitive through the ui_hook.go (via [*View](https://github.com/opentofu/opentofu/blob/main/internal/command/views/hook_ui.go#L49)), but I didn't like the responsibility of the Hook using that.

It seemed more semantically correct to pass this option through the EvalContext, even with more code.

Before:
```
null_resource.demo: Creating...
2026-03-23T22:38:13.564-0300 [INFO]  Starting apply for null_resource.demo
2026-03-23T22:38:13.564-0300 [DEBUG] null_resource.demo: applying the planned Create change
null_resource.demo: Provisioning with 'local-exec'...
null_resource.demo (local-exec): (output suppressed due to sensitive value in config)
null_resource.demo (local-exec): (output suppressed due to sensitive value in config)
null_resource.demo: Creation complete after 0s [id=541969575736346590]
```

After:
```
null_resource.demo: Creating...
2026-03-23T22:37:20.430-0300 [INFO]  Starting apply for null_resource.demo
2026-03-23T22:37:20.430-0300 [DEBUG] null_resource.demo: applying the planned Create change
null_resource.demo: Provisioning with 'local-exec'...
null_resource.demo (local-exec): Executing: ["/bin/sh" "-c" "echo 'Transient Token Length: 22'"]
null_resource.demo (local-exec): Transient Token Length: 22
null_resource.demo: Creation complete after 0s [id=2658144095968671671]
```

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/tofu/node_resource_abstract_instance.go [hunk 1]
```diff
@@ -2701,45 +2701,21 @@ func (n *NodeAbstractResourceInstance) applyProvisioners(ctx context.Context, ev
...
 
-		// The output function
-		outputFn := func(msg string) {
-			// Given that we return nil below, this will never error
-			_ = evalCtx.Hook(func(h Hook) (HookAction, error) {
-				h.ProvisionOutput(n.Addr, prov.Type, msg)
-				return HookActionContinue, nil
-			})
-		}
-
```
Comment (diofeher) [inline internal/tofu/node_resource_abstract_instance.go:2729]: I'm removing this code from this part as the `outputFn` below should catch all cases. The handling of the "suppressed" message is inside the ProvisionOutput now.

File: internal/tofu/node_resource_abstract_instance.go [hunk 2]
```diff
@@ -2701,45 +2701,21 @@ func (n *NodeAbstractResourceInstance) applyProvisioners(ctx context.Context, ev
...
-		// In case the configuration of a provisioner is referencing an
-		// ephemeral value, supress the whole output of the provisioner.
-		if _, hasEphemeral := configMarks[marks.Ephemeral]; hasEphemeral {
-			outputFn = func(msg string) {
-				// Given that we return nil below, this will never error
-				_ = evalCtx.Hook(func(h Hook) (HookAction, error) {
-					h.ProvisionOutput(n.Addr, prov.Type, "(output suppressed due to ephemeral value in config)")
-					return HookActionContinue, nil
-				})
-			}
```
Comment (diofeher) [inline internal/tofu/node_resource_abstract_instance.go:2783]: In the last ticket triage, someone mentioned that ephemerals can look fine in the output locally. If they need to be suppressed, the user can add a sensitive flag to them. That's why I removed this part along with my changes.

File: internal/command/views/view.go [hunk 3]
```diff
@@ -248,6 +248,10 @@ func (v *View) SetShowSensitive(showSensitive bool) {
 	v.showSensitive = showSensitive
 }
 
+func (v *View) ShowSensitive() bool {
```
Comment (cam72cam) [inline internal/command/views/view.go]: Does this need to be exported?

Comment (diofeher) [reply internal/command/views/view.go]: You're right, I was trying to change another part of the code and thought it was going to be needed, but then I forgot to change it back. Thanks for the catch!

Comment (diofeher) [reply internal/command/views/view.go]: Fixed on https://github.com/opentofu/opentofu/pull/3931/commits/94146b7582b861728cd8b6b1d40b4d80e4729195

File: internal/command/e2etest/primary_test.go [hunk 4]
```diff
@@ -459,7 +459,11 @@ Changes to Outputs:
 					`simple_resource.test_res (local-exec): visible test value`,
 					`simple_resource.test_res (local-exec): \"visible test value\"`,
 				}, true},
-				outputEntry{[]string{"simple_resource.test_res (local-exec): (output suppressed due to ephemeral value in config)"}, true},
+				outputEntry{[]string{
```
Comment (yottta) [inline internal/command/e2etest/primary_test.go]: Could we add a comment here explaining on why this was changed?
And also, could you please update the content of the provisioner commands in the [configuration](https://github.com/opentofu/opentofu/blob/137b81982d1807b585831f3e4233a599cb02382f/internal/command/e2etest/testdata/ephemeral-workflow/main.tf#L51-L57) for this test?
Now, having it as "not visible" is confusing.

File: internal/command/meta.go [hunk 5]
```diff
@@ -31,6 +31,7 @@ import (
 	"github.com/opentofu/opentofu/internal/backend"
 	"github.com/opentofu/opentofu/internal/backend/local"
 	"github.com/opentofu/opentofu/internal/command/arguments"
+	"github.com/opentofu/opentofu/internal/command/clistate"
```
Comment (yottta) [inline internal/command/meta.go:29]: Unrelated change. If not asking for too much, could you revert this.

**Review by yottta — CHANGES_REQUESTED** [review]
Because changes have been made to the ephemeral supressing, please update the [public documentation](https://github.com/opentofu/opentofu/blob/137b81982d1807b585831f3e4233a599cb02382f/website/docs/language/ephemerality/index.mdx?plain=1#L183) too.

File: internal/command/e2etest/primary_test.go (hunk 4 above)
Comment (diofeher) [reply internal/command/e2etest/primary_test.go]: Thanks for the catch! Makes sense, working on it

Comment (diofeher) [reply internal/command/e2etest/primary_test.go]: Added at https://github.com/opentofu/opentofu/pull/3931/commits/41a65b21bd9d0e335ed5718bb999846368691bfb (sorry for the squashed commit)

**Review by yottta — CHANGES_REQUESTED** [review]
Please update the [docs](https://opentofu.org/docs/language/ephemerality/#using-the-module-in-a-configuration-to-retrieve-a-secret-and-configure-a-provider) too.

**Review by yottta — APPROVED** [review]
