### PR TITLE
Enhance the documentation and the integration tests for the pg backend

### LINKED ISSUE #3699: PG backend ignore `schema_name` parameter
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.11.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "pg" {
    conn_str             = "postgresql://tofu_user:npg_xxx.gwc.azure.neon.tech/neondb?sslmode=require&options=-c search_path=tofu_foundation"
    schema_name          = "tofu_foundation"
    skip_schema_creation = true
  }
}
```

### Debug Output

```
TF_LOG=trace tofu init
2026-01-22T10:51:30.387+0100 [TRACE] OpenTelemetry: OTEL_TRACES_EXPORTER not set, OTel tracing is not enabled
2026-01-22T10:51:30.387+0100 [INFO]  OpenTofu version: 1.11.2
2026-01-22T10:51:30.387+0100 [DEBUG] using github.com/hashicorp/go-tfe v1.95.0
2026-01-22T10:51:30.387+0100 [DEBUG] using github.com/opentofu/hcl/v2 v2.20.2-0.20251021132045-587d123c2828
2026-01-22T10:51:30.387+0100 [DEBUG] using github.com/zclconf/go-cty v1.17.0
2026-01-22T10:51:30.387+0100 [INFO]  Go runtime version: go1.25.5 X:nodwarf5
2026-01-22T10:51:30.387+0100 [INFO]  CLI args: []string{"tofu", "init"}
2026-01-22T10:51:30.387+0100 [TRACE] Stdout is a terminal of width 169
2026-01-22T10:51:30.387+0100 [TRACE] Stderr is a terminal of width 169
2026-01-22T10:51:30.387+0100 [TRACE] Stdin is a terminal
2026-01-22T10:51:30.387+0100 [DEBUG] Attempting to open CLI config file: /home/backsippan/.tofurc
2026-01-22T10:51:30.387+0100 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2026-01-22T10:51:30.387+0100 [DEBUG] ignoring non-existing provider search directory /home/backsippan/gh/cv/tofun/test-pg-backend/test3-no-search-path/terraform.d/plugins
2026-01-22T10:51:30.387+0100 [DEBUG] ignoring non-existing provider search directory /home/backsippan/.terraform.d/plugins
2026-01-22T10:51:30.387+0100 [DEBUG] ignoring non-existing provider search directory /home/backsippan/.local/share/terraform/plugins
2026-01-22T10:51:30.387+0100 [DEBUG] ignoring non-existing provider search directory /home/backsippan/.local/share/flatpak/exports/share/terraform/plugins
2026-01-22T10:51:30.387+0100 [DEBUG] ignoring non-existing provider search directory /var/lib/flatpak/exports/share/terraform/plugins
2026-01-22T10:51:30.387+0100 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2026-01-22T10:51:30.387+0100 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2026-01-22T10:51:30.387+0100 [DEBUG] Found the config directory: /home/backsippan/.terraform.d
2026-01-22T10:51:30.387+0100 [INFO]  CLI command args: []string{"init"}

Initializing the backend...
2026-01-22T10:51:30.388+0100 [TRACE] Meta.Backend: built configuration for "pg" backend with hash value 4420875
2026-01-22T10:51:30.388+0100 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2026-01-22T10:51:30.388+0100 [DEBUG] New state was assigned lineage "9420bb9a-44cf-1c99-d4b9-c06b0bb92d6e"
2026-01-22T10:51:30.388+0100 [TRACE] Meta.Backend: moving from default local state only to "pg" backend
2026-01-22T10:51:30.388+0100 [DEBUG] checking for provisioner in "."
2026-01-22T10:51:30.389+0100 [DEBUG] checking for provisioner in "/usr/bin"
2026-01-22T10:51:30.389+0100 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2026-01-22T10:51:30.389+0100 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2026-01-22T10:51:30.389+0100 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2026-01-22T10:51:30.389+0100 [TRACE] statemgr.Filesystem: read nil snapshot
2026-01-22T10:51:30.389+0100 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
╷
│ Error: pq: permission denied for schema public
│ 
│ 
╵
```

### Expected Behavior

Setting schema_name parameter should not break `opentofu init` run.

### Actual Behavior

Runnin `opentofu init` with a specified `schema_name` fails with an SQL error

### Steps to Reproduce

just run `tofu init`

### Additional Context

I think the issue lays here: 
https://github.com/opentofu/opentofu/blob/c4f49afc10060ceaaba3ac7367557afcf75f061d/internal/backend/remote-state/pg/backend.go#L146
Since there is hard coded usage of `public` schema. 

### References

_No response_

### PR DESCRIPTION
**Pull request by yottta**
This reworks the tests to actually check the created postgres entries.
Also adds some more details in the documentation for the pg backend to explain why the user used to access the DB needs to have access to the `public` schema.

Resolves #3699

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [ ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [ ] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [ ] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [x] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by yottta** [comment]
Converted to draft since this breaks the locking across multiple OpenTofu projects.
From the [locking RFC](https://github.com/opentofu/opentofu/blob/4c381a0c0ce0b557f10501dc31e53ecd1cf9388e/rfc/20250127-PostgreSQL-Locking.md#proposed-solution):
> Also, pg_advisory_lock is database scoped, so pg backend needs to handle collisions between different state IDs, even if they come from different OpenTofu setups (i.e. different schemas inside the same database). **This is handled via single sequence in a shared schema (public)**.

**Comment by yottta** [comment]
After a conversation with the maintainers, we decided to just improve the documentation.
The hardcoded `public` schema is necessary due to the way locking is implemented and the way it works with multiple configurations that need to lock states in the same time.

For more information check the documentation and the [RFC for PG locking](https://github.com/opentofu/opentofu/blob/4c381a0c0ce0b557f10501dc31e53ecd1cf9388e/rfc/20250127-PostgreSQL-Locking.md#proposed-solution):
> Also, `pg_advisory_lock` is database scoped, so `pg` backend needs to handle collisions between different state IDs, even if they come from different OpenTofu setups (i.e. different schemas inside the same database). This is handled via single sequence in a shared schema (`public`).

File: internal/backend/remote-state/pg/backend.go [hunk 1]
```diff
@@ -143,16 +146,18 @@ func (b *Backend) configure(ctx context.Context) error {
 	}
 
 	if !skipTableCreation {
-		query = "CREATE SEQUENCE IF NOT EXISTS public.global_states_id_seq AS bigint"
+		query = fmt.Sprintf("CREATE SEQUENCE IF NOT EXISTS public.%s AS bigint", sequenceName)
```
Comment (cam72cam) [inline internal/backend/remote-state/pg/backend.go]: Let's move the `public.` into the const string

File: internal/backend/remote-state/pg/backend_test.go [hunk 2]
```diff
@@ -101,6 +103,46 @@ func TestBackendConfig(t *testing.T) {
...
+			Name: "valid-config-creates-only-index",
+			Setup: func(db *sql.DB) error {
+				schemaName := fmt.Sprintf("terraform_%s", t.Name())
+				tableName := fmt.Sprintf("terraform_table_%s", t.Name())
+				query := fmt.Sprintf(`CREATE SCHEMA IF NOT EXISTS %s`, pq.QuoteIdentifier(schemaName))
+				if _, err := db.Exec(query); err != nil {
+					return fmt.Errorf("failed to create schema during setup: %w", err)
+				}
+				quotedSchema := pq.QuoteIdentifier(schemaName)
+				query = fmt.Sprintf("CREATE SEQUENCE IF NOT EXISTS %s.%s AS bigint", quotedSchema, sequenceName)
```
Comment (cam72cam) [inline internal/backend/remote-state/pg/backend_test.go]: This seems wrong?  Shouldn't this be public.?

Comment (yottta) [reply internal/backend/remote-state/pg/backend_test.go]: Fixed in dba89289bd3d9e2a943d7bd77b3d51917f20dbf7

File: internal/backend/remote-state/pg/backend.go (hunk 1 above)
Comment (yottta) [reply internal/backend/remote-state/pg/backend.go]: Fixed in dba89289bd3d9e2a943d7bd77b3d51917f20dbf7
