### PR TITLE
Resolve issue with tofu init crashing when using a variable for module source via a test file

### LINKED ISSUE #3686: Crash when using variable for version module specification
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
❯ tofu --version
OpenTofu v1.11.3
on darwin_arm64

(same problem on linux_amd64)
```

### OpenTofu Configuration Files

There is no specific config; it's a module.

Test HCL is below:
```hcl
mock_provider "aws" {
  override_data {
    target = module.karpenter.data.aws_iam_policy_document.controller_assume_role
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[]}"
    }
  }

  override_data {
    target = module.karpenter.data.aws_iam_policy_document.controller
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[]}"
    }
  }

  override_data {
    target = module.karpenter.data.aws_iam_policy_document.queue
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[]}"
    }
  }

  override_data {
    target = module.karpenter.data.aws_iam_policy_document.node_assume_role
    values = {
      json = "{\"Version\":\"2012-10-17\",\"Statement\":[]}"
    }
  }

  override_data {
    target = module.karpenter.data.aws_partition.current
    values = {
      partition = "aws"
    }
  }

  override_data {
    target = module.karpenter.data.aws_region.current
    values = {
      region = "us-west-2"
    }
  }

  override_data {
    target = module.karpenter.data.aws_caller_identity.current
    values = {
      account_id = "123456789012"
    }
  }

  override_resource {
    target = module.karpenter.aws_sqs_queue.this
    values = {
      arn = "arn:aws:sqs:us-west-2:123456789012:karpenter-queue"
    }
  }

  override_resource {
    target = module.karpenter.aws_iam_policy.controller
    values = {
      arn = "arn:aws:iam::123456789012:policy/KarpenterControllerPolicy"
    }
  }

  override_resource {
    target = module.karpenter.aws_iam_role.controller
    values = {
      arn = "arn:aws:iam::123456789012:role/KarpenterController"
    }
  }

  override_resource {
    target = module.karpenter.aws_iam_role.node
    values = {
      arn = "arn:aws:iam::123456789012:role/KarpenterNode"
    }
  }
}
mock_provider "kubernetes" {}

run "plan" {
  command = plan

  module {
    source = "./."
  }

  providers = {
    aws        = aws
    kubernetes = kubernetes
  }

  variables {
    enable_karpenter = true
    env              = "dev"
    tags             = { env = "dev" }

    aws_access_key = "test"
    aws_secret_key = "test"
    aws_region     = "us-west-2"

    cluster_endpoint                   = "https://example.com"
    cluster_certificate_authority_data = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG4tLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
    cluster_name                       = "example-cluster"
  }

  assert {
    condition     = kubernetes_storage_class.pd_ssd.metadata[0].name == "gp3"
    error_message = "Default storage class should be gp3."
  }

  assert {
    condition     = kubernetes_namespace.karpenter[0].metadata[0].name == "karpenter"
    error_message = "Karpenter namespace should be created."
  }

  assert {
    condition     = length(module.karpenter) == 1
    error_message = "Karpenter module should be instantiated when enabled."
  }
}
```

### Debug Output

```
❯ TF_LOG=trace tofu init -backend=false
2026-01-16T09:50:37.702+0100 [TRACE] OpenTelemetry: OTEL_TRACES_EXPORTER not set, OTel tracing is not enabled
2026-01-16T09:50:37.703+0100 [INFO]  OpenTofu version: 1.11.3
2026-01-16T09:50:37.703+0100 [DEBUG] using github.com/hashicorp/go-tfe v1.95.0
2026-01-16T09:50:37.703+0100 [DEBUG] using github.com/opentofu/hcl/v2 v2.20.2-0.20251021132045-587d123c2828
2026-01-16T09:50:37.703+0100 [DEBUG] using github.com/zclconf/go-cty v1.17.0
2026-01-16T09:50:37.703+0100 [INFO]  Go runtime version: go1.25.5
2026-01-16T09:50:37.703+0100 [INFO]  CLI args: []string{"tofu", "init", "-backend=false", "-upgrade"}
2026-01-16T09:50:37.703+0100 [TRACE] Stdout is a terminal of width 314
2026-01-16T09:50:37.703+0100 [TRACE] Stderr is a terminal of width 314
2026-01-16T09:50:37.703+0100 [TRACE] Stdin is a terminal
2026-01-16T09:50:37.703+0100 [DEBUG] Attempting to open CLI config file: /Users/minowara/.tofurc
2026-01-16T09:50:37.703+0100 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2026-01-16T09:50:37.704+0100 [DEBUG] ignoring non-existing provider search directory /Users/minowara/Documents/Azul/DevOps/Infrastructure/Modules/tf-aws-eks-k8s/terraform.d/plugins
2026-01-16T09:50:37.704+0100 [DEBUG] ignoring non-existing provider search directory /Users/minowara/.terraform.d/plugins
2026-01-16T09:50:37.704+0100 [DEBUG] ignoring non-existing provider search directory /Users/minowara/Library/Application Support/io.terraform/plugins
2026-01-16T09:50:37.704+0100 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2026-01-16T09:50:37.704+0100 [DEBUG] Found the config directory: /Users/minowara/.terraform.d
2026-01-16T09:50:37.704+0100 [INFO]  CLI command args: []string{"init", "-backend=false"}
2026-01-16T09:50:37.708+0100 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2026-01-16T09:50:37.709+0100 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2026-01-16T09:50:37.709+0100 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2026-01-16T09:50:37.709+0100 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2026-01-16T09:50:37.709+0100 [TRACE] statemgr.Filesystem: read nil snapshot
Upgrading modules...
2026-01-16T09:50:37.709+0100 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
2026-01-16T09:50:37.710+0100 [DEBUG] Module installer: begin karpenter
2026-01-16T09:50:37.710+0100 [TRACE] ModuleInstaller: discarding previous record of karpenter prior to reinstall
2026-01-16T09:50:37.710+0100 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/karpenter prior to install of karpenter
2026-01-16T09:50:37.770+0100 [TRACE] ModuleInstaller: karpenter is a registry module at registry.opentofu.org/terraform-aws-modules/eks/aws//modules/karpenter
2026-01-16T09:50:37.770+0100 [DEBUG] karpenter listing available versions of registry.opentofu.org/terraform-aws-modules/eks/aws//modules/karpenter at registry.opentofu.org
2026-01-16T09:50:37.770+0100 [TRACE] HTTP client GET request to https://registry.opentofu.org/.well-known/terraform.json
2026-01-16T09:50:37.854+0100 [DEBUG] fetching module versions from "https://registry.opentofu.org/v1/modules/terraform-aws-modules/eks/aws/versions"
2026-01-16T09:50:37.854+0100 [DEBUG] GET https://registry.opentofu.org/v1/modules/terraform-aws-modules/eks/aws/versions
2026-01-16T09:50:37.855+0100 [TRACE] HTTP client GET request to https://registry.opentofu.org/v1/modules/terraform-aws-modules/eks/aws/versions
2026-01-16T09:50:37.881+0100 [DEBUG] found available version "21.14.0" for terraform-aws-modules/eks/aws
...
Downloading registry.opentofu.org/terraform-aws-modules/eks/aws 21.14.0 for karpenter...
2026-01-16T09:50:37.883+0100 [DEBUG] looking up module location from "https://registry.opentofu.org/v1/modules/terraform-aws-modules/eks/aws/21.14.0/download"
2026-01-16T09:50:37.883+0100 [DEBUG] GET https://registry.opentofu.org/v1/modules/terraform-aws-modules/eks/aws/21.14.0/download
2026-01-16T09:50:37.883+0100 [TRACE] HTTP client GET request to https://registry.opentofu.org/v1/modules/terraform-aws-modules/eks/aws/21.14.0/download
2026-01-16T09:50:37.915+0100 [TRACE] ModuleInstaller: karpenter registry.opentofu.org/terraform-aws-modules/eks/aws 21.14.0 is available at "git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v21.14.0"
2026-01-16T09:50:37.915+0100 [TRACE] getmodules: fetching "git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v21.14.0" to ".terraform/modules/karpenter"
2026-01-16T09:50:47.902+0100 [TRACE] ModuleInstaller: karpenter "git::https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v21.14.0" was downloaded to .terraform/modules/karpenter
2026-01-16T09:50:47.902+0100 [TRACE] ModuleInstaller: karpenter should now be at .terraform/modules/karpenter/modules/karpenter
2026-01-16T09:50:47.907+0100 [DEBUG] Module installer: karpenter installed at .terraform/modules/karpenter/modules/karpenter
- karpenter in .terraform/modules/karpenter/modules/karpenter
2026-01-16T09:50:47.907+0100 [DEBUG] Module installer: begin test.tests.basic.plan
2026-01-16T09:50:47.907+0100 [TRACE] ModuleInstaller: discarding previous record of test.tests.basic.plan prior to reinstall
2026-01-16T09:50:47.907+0100 [TRACE] ModuleInstaller: also discarding downstream test.tests.basic.plan.karpenter
2026-01-16T09:50:47.907+0100 [TRACE] ModuleInstaller: cleaning directory .terraform/modules/test.tests.basic.plan prior to install of test.tests.basic.plan
2026-01-16T09:50:47.907+0100 [TRACE] ModuleInstaller: test.tests.basic.plan has local path "./."
2026-01-16T09:50:47.907+0100 [TRACE] ModuleInstaller: test.tests.basic.plan uses directory from parent: .

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x64
runtime/debug.PrintStack()
        runtime/debug/stack.go:18 +0x1c
github.com/opentofu/opentofu/internal/logging.panicHandler({0x103df9240, 0x10683b390}, {0x0, 0x0, 0x0})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xb4
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        github.com/opentofu/opentofu/internal/logging/panic.go:51 +0xcc
panic({0x103df9240?, 0x10683b390?})
        runtime/panic.go:783 +0x120
github.com/opentofu/opentofu/internal/configs.staticScopeData.GetInputVariable({0x140009960f0?, {0x14000a94700?, 0x14000c20be8?, 0x101904c50?}}, {0xc20a08?, 0x106ab3870?}, {{}, {0x14000696ab0?, 0x3500?}}, {{0x140004c2180, ...}, ...})
        github.com/opentofu/opentofu/internal/configs/static_scope.go:269 +0x12c
github.com/opentofu/opentofu/internal/lang.(*evalVarBuilder).putValueBySubject(0x14000c20d88, {0x1045f1ef0?, 0x10697dae0?}, 0x14000c20e10?)
        github.com/opentofu/opentofu/internal/lang/eval.go:518 +0x7dc
github.com/opentofu/opentofu/internal/lang.(*Scope).evalContext(0x14000022000, {0x1045f1ef0, 0x10697dae0}, 0x0, {0x140006a2bd0, 0x1, 0x1}, {0x0, 0x0})
        github.com/opentofu/opentofu/internal/lang/eval.go:395 +0x580
github.com/opentofu/opentofu/internal/lang.(*Scope).EvalContext(...)
        github.com/opentofu/opentofu/internal/lang/eval.go:323
github.com/opentofu/opentofu/internal/lang.(*Scope).EvalExpr(0x14000022000, {0x1045f1ef0, 0x10697dae0}, {0x1045f2f68, 0x1400085de60}, {{0x1045f2c10?, 0x10697dae0?}})
        github.com/opentofu/opentofu/internal/lang/eval.go:186 +0x8c
github.com/opentofu/opentofu/internal/configs.StaticEvaluator.Evaluate({{{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}}, 0x14000988900}, {0x1045f1ef0, ...}, ...)
        github.com/opentofu/opentofu/internal/configs/static_evaluator.go:96 +0x1e8
github.com/opentofu/opentofu/internal/configs.(*ModuleCall).decodeStaticVersion(0x14000b14300, {0x1045f1ef0, 0x10697dae0}, 0x140009960a0)
        github.com/opentofu/opentofu/internal/configs/module_call.go:265 +0x164
github.com/opentofu/opentofu/internal/configs.(*ModuleCall).decodeStaticFields(0x14000b14300, {0x1045f1ef0, 0x10697dae0}, 0x140009960a0)
        github.com/opentofu/opentofu/internal/configs/module_call.go:184 +0x6c
github.com/opentofu/opentofu/internal/configs.NewModule({0x1400088b480, 0x6, 0x0?}, {0x0, 0x0, 0x14000c21698?}, {{0x0, 0x0, 0x0}, 0x0, ...}, ...)
        github.com/opentofu/opentofu/internal/configs/module.go:253 +0xadc
github.com/opentofu/opentofu/internal/configs.(*Parser).LoadConfigDirSelective(0x140006a7840, {0x103925b38, 0x1}, {{0x0, 0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, ...}}, ...)
        github.com/opentofu/opentofu/internal/configs/parser_config_dir.go:68 +0x234
github.com/opentofu/opentofu/internal/configs.(*Parser).LoadConfigDir(...)
        github.com/opentofu/opentofu/internal/configs/parser_config_dir.go:55
github.com/opentofu/opentofu/internal/initwd.(*ModuleInstaller).installLocalModule(0x140008dd780, {0x1045f1e10, 0x14000610180}, 0x14000694000, {0x14000e15998, 0x15}, 0x14000900ed0, {0x1045be6c0, 0x14000714ea0})
        github.com/opentofu/opentofu/internal/initwd/module_install.go:468 +0x904
github.com/opentofu/opentofu/internal/initwd.(*ModuleInstaller).InstallModules.(*ModuleInstaller).moduleInstallWalker.func2({0x1045f1e10, 0x140008d2b70}, 0x14000694000)
        github.com/opentofu/opentofu/internal/initwd/module_install.go:347 +0xf1c
github.com/opentofu/opentofu/internal/configs.ModuleWalkerFunc.LoadModule(0x13227bd60?, {0x1045f1e10?, 0x140008d2b70?}, 0x0?)
        github.com/opentofu/opentofu/internal/configs/config_build.go:257 +0x38
github.com/opentofu/opentofu/internal/configs.loadModule({0x1045f1e10, 0x140008d2b70}, 0x140008b9ea0, 0x14000694000, {0x104599240, 0x1400091c240})
        github.com/opentofu/opentofu/internal/configs/config_build.go:168 +0x4c
github.com/opentofu/opentofu/internal/configs.buildTestModules({0x1045f1e10, 0x140008d2b70}, 0x140008b9ea0, {0x104599240, 0x1400091c240})
        github.com/opentofu/opentofu/internal/configs/config_build.go:87 +0x4a0
github.com/opentofu/opentofu/internal/configs.BuildConfig({0x1045f1e10, 0x140008d2b70}, 0x140008fed80, {0x104599240, 0x1400091c240})
        github.com/opentofu/opentofu/internal/configs/config_build.go:35 +0xc8
github.com/opentofu/opentofu/internal/initwd.(*ModuleInstaller).installDescendentModules(0x140008dd780, {0x1045f1e10, 0x140008d2b70}, 0x140008fed80, 0x14000900ed0, {0x104599240, 0x1400091c240}, 0x0)
        github.com/opentofu/opentofu/internal/initwd/module_install.go:394 +0xc8
github.com/opentofu/opentofu/internal/initwd.(*ModuleInstaller).InstallModules(0x140008dd780, {0x1045f1e10, 0x140008d2b70}, {0x103925b38, 0x1}, {0x103226c03, 0x5}, 0x1, 0x0, {0x1045be6c0, ...}, ...)
        github.com/opentofu/opentofu/internal/initwd/module_install.go:206 +0x440
github.com/opentofu/opentofu/internal/command.(*Meta).installModules(0x1400073cb48, {0x1045f1e10, 0x140008d2b70}, {0x14000080054?, 0x14000842978?}, {0x103226c03, 0x5}, 0x1, 0x0, {0x1045be6c0, ...})
        github.com/opentofu/opentofu/internal/command/meta_config.go:304 +0x340
github.com/opentofu/opentofu/internal/command.(*InitCommand).getModules(0x1400073cb48, {0x1045f1e48, 0x1400071bd60}, {0x14000080054, 0x4b}, {0x103226c03, 0x5}, 0x140008c8a20, 0x1)
        github.com/opentofu/opentofu/internal/command/init.go:426 +0x564
github.com/opentofu/opentofu/internal/command.(*InitCommand).Run(0x1400073cb48, {0x140001140a0, 0x2, 0x2})
        github.com/opentofu/opentofu/internal/command/init.go:274 +0x16a4
github.com/mitchellh/cli.(*CLI).Run(0x140004b28c0)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x420
main.realMain()
        github.com/opentofu/opentofu/cmd/tofu/main.go:372 +0x1818
main.main()
        github.com/opentofu/opentofu/cmd/tofu/main.go:69 +0x1c

```

### Expected Behavior

Initialization will finish.

### Actual Behavior

Crash of the CLI.

### Steps to Reproduce

1. `tofu init -backend=false`
2.  `variables.tf` 
```
variable "module_karpenter_version" {
  description = "Version of Terraform AWS EKS Karpenter module to use"
  type        = string
  default     = "21.14.0"
}
```
3. `karpenter.tf`
```
resource "kubernetes_namespace" "karpenter" {
  count = var.enable_karpenter ? 1 : 0
  metadata {
    name = "karpenter"
  }
}

module "karpenter" {
  count  = var.enable_karpenter ? 1 : 0
  source = "terraform-aws-modules/eks/aws//modules/karpenter"
  version = var.module_karpenter_version #throwing error
  #version = "21.14.0" #working properly

  cluster_name = var.cluster_name

  create_access_entry             = true
  create_pod_identity_association = true
  namespace                       = kubernetes_namespace.karpenter[0].metadata[0].name
  enable_spot_termination         = true

  create_iam_role    = true
  iam_role_name      = "KarpenterController-${var.cluster_name}"
  node_iam_role_name = "KarpenterNode-${var.cluster_name}"

  tags = var.tags
}
```

### Additional Context

When changing the `version` of the `karpenter.tf` module to a plain string `version = "21.14.0"`, then there is no crash, and initialization will finish.

### References

_No response_

### PR DESCRIPTION
**Pull request by Yantrio**
Resolves #3686

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/configs/config_build.go [hunk 1]
```diff
@@ -81,7 +82,27 @@ func buildTestModules(ctx context.Context, root *Config, walker ModuleWalker) hc
...
+				Call: NewStaticModuleCall(path, func(v *Variable) (cty.Value, hcl.Diagnostics) {
+					// Handle the case where this is overridden in the test run block
+					expr, isOverridden := run.Variables[v.Name]
+					if isOverridden {
+						identifier := StaticIdentifier{
+							Module:    path,
+							Subject:   fmt.Sprintf("var.%s", v.Name),
+							DeclRange: expr.Range(),
+						}
+						return root.Module.StaticEvaluator.Evaluate(ctx, expr, identifier)
```
Comment (Yantrio) [inline internal/configs/config_build.go:93]: Should we use StaticEvaluator here or just grab the value of the expression, WDYT @cam72cam ?

Comment (cam72cam) [reply internal/configs/config_build.go:93]: I guess the other question I have is: should we do anything beyond the default statement below?  Should the variables in a test run block considered "static values" for the purposes of building configuration?

File: internal/configs/config_build.go [hunk 2]
```diff
@@ -81,7 +82,27 @@ func buildTestModules(ctx context.Context, root *Config, walker ModuleWalker) hc
...
+					}
+
+					// If we haven't had it overridden in a run block, fall back to trying our best
+					// but we do have defaults for some that we can use.
+					if v.Default != cty.NilVal {
+						return v.Default, nil
+					}
+					return cty.DynamicVal, nil
+				}, root.Module.SourceDir, ""), // what should the workspace be here? im so confused...
```
Comment (yottta) [inline internal/configs/config_build.go]:
```suggestion
				}, root.Module.SourceDir, root.Module.StaticEvaluator.call.workspace),
```

As far as I can tell, this should be the workspace that is configured for the current run. That is [given to the root module call](https://github.com/opentofu/opentofu/blob/c4f49afc10060ceaaba3ac7367557afcf75f061d/internal/command/meta_config.go#L125) creation and later used to [resolve references like `tofu.workspace`](https://github.com/opentofu/opentofu/blob/c4f49afc10060ceaaba3ac7367557afcf75f061d/internal/configs/static_scope.go#L223).

So it should be available in this context too IINW 🤔

File: internal/configs/config_build.go (hunk 1 above)
Comment (yottta) [reply internal/configs/config_build.go:93]: > Should we use StaticEvaluator here or just grab the value of the expression

Can we? We need a proper evalCtx for it and it's not really at hand from what I've seen.

Comment (Yantrio) [reply internal/configs/config_build.go:93]: I'll keep the static evaluator as is. we can always revisit later if needed.
