### PR TITLE
Failed to load backend configuration

### LINKED ISSUE #3643: Legacy state reader incorrectly triggered when TF_DATA_DIR contains terraform.tfstate
## Description

When `TF_DATA_DIR` points to a directory containing a `terraform.tfstate` file, OpenTofu reads it through the legacy code path in `internal/legacy/tofu/state.go`, which rejects valid version 4 state files with an incorrect error message.

## Steps to Reproduce

```bash
# Setup: any tofu project with providers configured
mkdir -p /tmp/test-state
cd /path/to/tofu/project

# Set TF_DATA_DIR and run tofu
export TF_DATA_DIR="/tmp/test-state"
tofu init
tofu apply -auto-approve  # Creates terraform.tfstate in TF_DATA_DIR

# Later, any state operation fails:
tofu state list
```

## Expected Behavior

State operations work normally since the state file is valid version 4 format created by the same OpenTofu version.

## Actual Behavior

```
Error: Failed to load state: OpenTofu 1.11.2 does not support state version 4, please update.
```

The state file clearly shows it was created by OpenTofu 1.11.2:
```json
{"version":4,"terraform_version":"1.11.2","serial":1,...}
```

## Root Cause Analysis

The error originates from `internal/legacy/tofu/state.go` which has:

```go
const StateVersion = 3  // Not updated for version 4

func ReadStateV3(jsonBytes []byte) (*State, error) {
    // ...
    if state.Version > StateVersion {  // 4 > 3 = true
        return nil, fmt.Errorf("OpenTofu %s does not support state version %d, please update.",
            tfversion.SemVer.String(), state.Version)
    }
    // ...
}
```

When `TF_DATA_DIR` contains a `terraform.tfstate` file, the backend initialization code appears to read it through this legacy path instead of the modern state reader in `internal/states/statefile/`.

## Workaround

Store the state file in a different directory from `TF_DATA_DIR`:

```bash
export TF_DATA_DIR="/tmp/test-state/data"  # For modules/providers only
mkdir -p "$TF_DATA_DIR"
tofu init
tofu apply -state=/tmp/test-state/terraform.tfstate  # State file outside TF_DATA_DIR
```

## Environment

- **OpenTofu Version:** 1.11.2
- **OS:** Linux (Debian 12/13, also reproduced on Proxmox VE 8.x)
- **Provider:** bpg/proxmox v0.91.0 (though likely provider-independent)

## Additional Context

This was discovered during E2E testing with isolated state directories per environment. The pattern of using `TF_DATA_DIR` for state isolation (setting it to a directory containing both the terraform data and state file) triggers this bug consistently.

The legacy state code in `internal/legacy/tofu/state.go` appears to be intended for very old state formats, but it's being triggered incorrectly for modern version 4 states when they happen to be located in `TF_DATA_DIR`.

### PR DESCRIPTION
**Pull request by KrishnaSindhur**
Resolves #3643 (2nd part updated error message

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by KrishnaSindhur** [comment]
Error message in CLI 
Before:
`Error: Failed to load state: opentofu 1.12.0 does not support CLI state version 4, please update`

After this PR change 
`Error: Failed to load backend configuration from /tmp/tofu-repro/data/terraform.tfstate: found a resource state file (version 4) where a backend configuration file (version 3) was expected; if TF_DATA_DIR is set, ensure it does not point to a directory containing a terraform.tfstate resource state file`

File: internal/command/clistate/cli_state.go [hunk 1]
```diff
@@ -129,6 +129,14 @@ func ReadState(src io.Reader) (*CLIState, error) {
 	}
 
 	if ver.Version != StateVersion {
+		if bytes.Contains(jsonBytes, []byte(`"terraform_version"`)) {
```
Comment (yottta) [inline internal/command/clistate/cli_state.go]: We should, somehow, plug the check requested [here](https://github.com/opentofu/opentofu/issues/3643#issuecomment-3739547627):
> If we do this then I think the special error message should be returned only if the TF_DATA_DIR environment variable is set, because otherwise we'd risk misleading someone who has an invalid CLI state file for some other reason that's unrelated to the TF_DATA_DIR variable.

Though, considering that the env variable is defined and used in the [`workdir`](https://github.com/opentofu/opentofu/blob/6e2250e050d10a4e2bd82d717bae594da845395d/internal/command/workdir/dir.go#L15) package, I would suggest one of the following approaches:
* Export a new function from that package that returns a `bool` if that environment variable has a value defined. 
* Export a function for the `workdir.Dir` that will return a stored `bool` that will be set to `true` only when [`workdir.Dir.OverrideDataDir`](https://github.com/opentofu/opentofu/blob/6e2250e050d10a4e2bd82d717bae594da845395d/internal/command/workdir/dir.go#L145) is called. And then pass the value returned by that into the `clistate.LocalState` whenever is initialised.

Personally, I would suggest to go with the second option, since it goes well with the initialisation of the `LocalState`, since it already uses information from the `workdir.Dir` configured object.

Before applying the changes, let's wait a couple of days, maybe other maintainers will like to have this done differently.

Other than that, I am not sure that the `bytes.Contains` check should be kept once we add the env var check 🤔

**Review by yottta — CHANGES_REQUESTED** [review]
Thanks for the help here.
There is one thing that is still to be tackled. Details inline.

File: internal/command/clistate/cli_state.go [hunk 2]
```diff
@@ -129,6 +129,14 @@ func ReadState(src io.Reader) (*CLIState, error) {
...
+			return nil, fmt.Errorf(
+				"found a resource state file (version %d) where a backend configuration "+
+					"file (version %d) was expected; if TF_DATA_DIR is set, ensure it does "+
+					"not point to a directory containing a terraform.tfstate resource state file",
+				ver.Version, StateVersion,
+			)
```
Comment (apparentlymart) [inline internal/command/clistate/cli_state.go:140]: This is a tricky situation because this error message needs to mention concepts we've never needed to mention in the UI or docs before, so we don't have established terminology to use.

But I do have some small suggested adjustments here:

```suggestion
			return nil, fmt.Errorf(
				"found a resource state file (version %d) where a backend configuration cache "+
					"file was expected; if TF_DATA_DIR is set, ensure it does "+
					"not point to a directory containing your main terraform.tfstate resource state file",
				ver.Version,
			)
```

Here I introduced the new terminology "backend configuration _cache_ file", because we already use the term "backend configuration" to refer to a `backend` block in a normal configuration file. The `$TF_DATA_DIR/terraform.tfstate` file behaves as a _sort of_ cache of the backend configuration settings that were present during `tofu init`, so that seemed like a reasonable way to distinguish it.

I also removed the part that would've said "(version 3)" here because the fact that the "backend configuration cache file" format was derived from version 3 of the resource state file format is an implementation detail that I think would make this situation appear more confusing, because it suggests that it might be possible to "upgrade" the backend configuration cache file format into the resource state format, which isn't true.

I finally added "your main" before mentioning `terraform.tfstate` by name, because I worry that someone who isn't already familiar with this problem could have trouble understanding what we mean given that both of these files are named `terraform.tstate`. I'm not sure that "your main terraform.tfstate" is enough to distinguish them either, but I'm just hoping that including that extra modifier would make the reader realize that we're trying to distinguish between two different files of the same name here. 🤷‍♂️

File: internal/command/clistate/cli_state.go (hunk 1 above)
Comment (KrishnaSindhur) [reply internal/command/clistate/cli_state.go]: I have kept both the checks,  `if dataDirOverridden && bytes.Contains(jsonBytes, []byte(`"terraform_version"`))` is the second check redundant?

File: internal/command/workdir/dir.go [hunk 3]
```diff
@@ -143,6 +147,13 @@ func (d *Dir) OverrideOriginalWorkingDir(originalPath string) {
 // working directory.
 func (d *Dir) OverrideDataDir(dataDir string) {
 	d.dataDir = filepath.Clean(dataDir)
+	d.dataDirOverridden = true
```
Comment (yottta) [inline internal/command/workdir/dir.go:150]: I know that this is quite dumb to ask for, but can we add a unit test for this with some comments on that test to explain why that test exists and why that expectancy is like that?
This is mostly for the future contributors that might want to change anything around this flag.

**Review by yottta — APPROVED** [review]
Other than the suggestion left by @apparentlymart and the one small thing that I left during this review, this looks pretty good.
Thanks for the help! 🙌

File: internal/command/workdir/dir.go (hunk 3 above)
Comment (yottta) [reply internal/command/workdir/dir.go:150]: Thanks for this. Added in 51ae09271a99e0893c8c271c9b55775603d52c6f

**Review by apparentlymart — APPROVED** [review]
