### PR TITLE
Deny ephemeral values in `count`

### LINKED ISSUE #3904: Ephemeral values should not be accepted in the `count` meta-argument
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.11.5
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
    }
    tfcoremock = {
      source = "hashicorp/tfcoremock"
    }
  }
}

resource "random_password" "boop" {
  count = terraform.applying ? 1 : 0

  length = 16
}
```

### Debug Output

```shell
%> tofu plan

No changes. Your infrastructure matches the configuration.

OpenTofu has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

### Expected Behavior

To fail similarly with the cases where an ephemeral value is given into the `enabled` or `for_each` meta-arguments.

### Actual Behavior

Succeeds (as seen in the debug output above)

### Steps to Reproduce

`tofu init`
`tofu plan`

### Additional Context

Considering that ephemeral resources are not stored in the state (and soon neither in the plan file), the ephemeral resources should be able to use ephemeral values for all 3 meta-arguments.
Right now, by using ephemeral values in `for_each` and `enabled` meta-arguments will fail for ephemeral blocks too.

### References

_No response_

### PR DESCRIPTION
**Pull request by yottta**
> [!NOTE]
> This PR solves the issue in #3904 by denying ephemeral values from being used in the `count` meta-argument.
> This is an alternative approach for #3907, which allowed the usage of ephemeral values in the repetition meta-arguments (count/for_each/enabled), but by doing that, it could disclose ephemeral values, which breaks the promise of ephemeral values not being visible in state/plan/logs.

Resolves #3904

During the initial [implementation](https://github.com/opentofu/opentofu/issues/2834), I missed adding validation for usage of ephemeral values in `count` meta argument.
This PR adds fixes the issue by raising an error if `count` uses an ephemeral value.

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [x] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/command/e2etest/primary_test.go [hunk 1]
```diff
@@ -513,6 +514,158 @@ Changes to Outputs:
...
+			}
+		}
+
+		{ // PLAN
+			stdout, stderr, err := tf.Run("-chdir="+chdir, "plan")
+			combined := fmt.Sprintf("%s\n\n%s", stripAnsi(stdout), stripAnsi(stderr))
+			if err == nil {
+				t.Errorf("expected to have an error during plan but got nothing. output:\n%s", combined)
+			}
+			entriesChecker := outputEntriesChecker(expectedApplyOutput)
```
Comment (diofeher) [inline internal/command/e2etest/primary_test.go]: Should you check the `expectedPlanOutput` instead?

Comment (yottta) [reply internal/command/e2etest/primary_test.go]: Good catch! Fixed in a04344aaaf701967cc29061981a0ed6c5c9adef5
