### PR TITLE
bug fix for Instance module without resources/outputs was not reporting correct length.

### LINKED ISSUE #3067: Instanced module without resources/outputs does not report correct length.
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
1.6.0...1.10.2
```

### OpenTofu Configuration Files

```hcl
main.tf:
module "foo" {
        source = "./foo"
        count = 1
        stuff = "s"
}

output "check" {
        value = length(module.foo)
}

foo/foo.tf
variable "stuff" {

}
```

### Debug Output

N/A

### Expected Behavior

Changes to Outputs:
  + check = 1

### Actual Behavior

Changes to Outputs:
  + check = 0

### Steps to Reproduce

1. tofu init
2. tofu plan

### Additional Context

While investigating a potential issue with tofu test, I was running released versions of terraform and tofu on a [random module with tests](https://github.com/FociSolutions/github-foundations-modules) that I found.  After I confirmed the unrelated fix, I noted that a count was different in the test and traced it down to an issue in OpenTofu's evaluate.go.

OpenTofu uses `output block` state and `output block` changes during plan to produce the value of a given `module.<name>`.  If the module does not have any outputs, the resulting value is an empty Tuple or Object (depending on for_each or count).

The data necessary to correctly identify they instance keys may not exist within the state/changes and should instead first look at the instance expander.

This will need to be refactored and a breaking change mentioned in the release.  It should not be backported as it's a breaking change.  This will match the functionality present in terraform binaries 1.8+.

### References

_No response_

### PR DESCRIPTION
**Pull request by KrishnaSindhur**
Resolves #3067 

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by KrishnaSindhur** [comment]
@diofeher Could you please review this approach? There might be another possible way to handle it without adding `InstanceExpander`.

Also, if you would like me to add more tests to cover different scenarios, I can create a new test file for that.

File: internal/tofu/evaluate.go [hunk 1]
```diff
@@ -440,6 +444,23 @@ func (d *evaluationStateData) GetModule(_ context.Context, addr addrs.ModuleCall
 	// module instance.
 	moduleInstances := map[addrs.InstanceKey]map[string]cty.Value{}
 
+	// First, we need to determine which module instances actually exist.
+	if d.Evaluator.InstanceExpander != nil {
```
Comment (yottta) [inline internal/tofu/evaluate.go]: Please check this [down below](https://github.com/KrishnaSindhur/opentofu/blob/d57435fd2b8e73808631c301daf164f891670bc0/internal/tofu/evaluate.go#L611).
This should be done only on non-validation phases, but the way it is done right now, it's done all the time.

File: internal/tofu/evaluate_test.go [hunk 2]
```diff
@@ -921,7 +923,179 @@ func TestEvaluatorGetModule(t *testing.T) {
 	}
 }
 
+func TestEvaluatorGetModule_ForEach(t *testing.T) {
```
Comment (diofeher) [inline internal/tofu/evaluate_test.go:930]: Can you add a comment to this test explaining its context?

File: internal/tofu/evaluate.go (hunk 1 above)
Comment (diofeher) [reply internal/tofu/evaluate.go]: Besides what @yottta said, it would be to explain why this is being done to give context to other readers.

File: internal/tofu/evaluate.go [hunk 3]
```diff
@@ -440,6 +444,23 @@ func (d *evaluationStateData) GetModule(_ context.Context, addr addrs.ModuleCall
...
+
+		for _, moduleInstanceAddr := range moduleInstanceAddrs {
+			if len(moduleInstanceAddr) > 0 {
+				lastStep := moduleInstanceAddr[len(moduleInstanceAddr)-1]
+				key := lastStep.InstanceKey
+
+				if _, exists := moduleInstances[key]; !exists {
+					moduleInstances[key] = map[string]cty.Value{}
+				}
+			}
```
Comment (diofeher) [inline internal/tofu/evaluate.go]:
```suggestion
			_, callInstance := moduleInstanceAddr.CallInstance()
			key := callInstance.Key

			if _, exists := moduleInstances[key]; !exists {
				moduleInstances[key] = map[string]cty.Value{}
			}
```

Let's use `CallInstance` as this is the pattern being used in this file.

**Review by diofeher — CHANGES_REQUESTED** [review]
Thanks for the contribution, @KrishnaSindhur, and sorry for the delay in getting back to you.

I've left some comments. Please let me know if you have any questions.

**Review by diofeher — APPROVED** [review]
Looking good, thanks a lot for this awesome contribution, @KrishnaSindhur!

File: internal/tofu/evaluate.go [hunk 4]
```diff
@@ -440,6 +444,25 @@ func (d *evaluationStateData) GetModule(_ context.Context, addr addrs.ModuleCall
...
+	// validation, the InstanceExpander may not be fully populated yet.
+	if d.Evaluator.InstanceExpander != nil && d.Evaluator.Operation != walkValidate {
+		childModuleAddr := d.ModulePath.Module().Child(addr.Name)
+		moduleInstanceAddrs := d.Evaluator.InstanceExpander.ExpandModule(childModuleAddr)
+
+		for _, moduleInstanceAddr := range moduleInstanceAddrs {
+			_, callInstance := moduleInstanceAddr.CallInstance()
+			key := callInstance.Key
+			if _, exists := moduleInstances[key]; !exists {
+				moduleInstances[key] = map[string]cty.Value{}
```
Comment (cam72cam) [inline internal/tofu/evaluate.go:461]: I wonder if it's possible for this to produce a moduleInstances map that has some values populated and others not.  Concretely, could there ever exist a scenario where moduleInstances contains two keys after this function, but the outputConfigs iteration below only populates one of the entries?

We use ObjectVal and TupleVal below, so it would not cause a panic in cty if we guess wrong.

In theory this is impossible, but that's my only hesitation about this approach.  I'm pretty sure that it would be a bug in OpenTofu if that were to occur, but maybe we want to be more defensive?

Depending on how the rest of the team feels about this, I think I'm comfortable merging this as is.  If we want to make this extra defensive, we could only execute this new code if len(outputConfigs) == 0, which would me it would either populate it here XOR populate it from looping over outputConfigs below.

**Comment by cam72cam** [comment]
We also need an entry in CHANGELOG.md for this fix.  Overall, I really like the approach @KrishnaSindhur!

File: internal/tofu/evaluate.go (hunk 4 above)
Comment (apparentlymart) [reply internal/tofu/evaluate.go:461]: If I understand correctly what you are worried about, I think this is okay in principle because this situation should only happen when the child module doesn't define any output values, and in that case an "empty object" would be the expected representation of an instance of that module anyway, right?

(Please let me know if I misunderstood the concern.)

Comment (cam72cam) [reply internal/tofu/evaluate.go:461]: I'm worried about the scenario on which we run this new code, pre-populate a bunch of empty output entries in the map, then only override some of them in the following output loop (state and change output entries).

Comment (apparentlymart) [reply internal/tofu/evaluate.go:461]: Ahh, I see.

From reading the subsequent code it seems like that could potentially happen if a particular module instance was missing from both the state and the plan at the time of evaluation.

Assuming that the dependency graph was constructed correctly, I think that should be possible only if the child module contained no output value or resource declarations, because otherwise some earlier code would've called either [`SyncState.SetResourceProvider`](https://pkg.go.dev/github.com/opentofu/opentofu/internal/states#SyncState.SetResourceProvider) or [`SyncState.SetOutputValue`](https://pkg.go.dev/github.com/opentofu/opentofu/internal/states#SyncState.SetOutputValue) with an address involving each instance of the module, and both of those internally call [`State.EnsureModule`](https://pkg.go.dev/github.com/opentofu/opentofu/internal/states#State.EnsureModule) to force there to be an entry in the state for the containing module instance. (And if it contains no output value declarations then it's expected for the map of output values to be empty.)

Of course, "assuming that the dependency graph was constructed correctly" is doing a lot of work in the previous paragraph, since we've _often_ introduced bugs of that type when introducing new features. But I see that as just one of the fundamental assumptions of the current OpenTofu architecture that _everything_ relies on for correct behavior, and so to me it feels okay to rely on it here too. :thinking: 

Does that make sense? Do you think I'm missing anything?

**Comment by KrishnaSindhur** [comment]
> We also need an entry in CHANGELOG.md for this fix. Overall, I really like the approach @KrishnaSindhur!

Updated the CHANGELOG.md

**Comment by KrishnaSindhur** [comment]
Are we going forward with this approach?

File: internal/tofu/evaluate.go (hunk 4 above)
Comment (cam72cam) [reply internal/tofu/evaluate.go:461]: That seems reasonable to me.  It's a very low chance that we break it in this way and we'd also break a lot of other stuff in that scenario.

**Review by cam72cam — APPROVED** [review]

**Comment by diofeher** [comment]
Thanks @KrishnaSindhur, it just got merged!
