### PR TITLE
Key provider decoding moved from gohcl to hcl/v2

### LINKED ISSUE #3482: JSON content with state/plan Encryption
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.10.5
on linux_amd64
```

### OpenTofu Configuration Files

```json
{
  "terraform": {
    "encryption": {
      "key_provider": {
        "pbkdf2": {
          "example": {
            "passphrase": "mysecretpassphrase!"
          }
        }
      },
      "method": {
        "aes_gcm": {
          "example": {
            "keys": "key_provider.pbkdf2.example"
          }
        }
      },
      "state": {
        "enforced": true,
        "method": "method.aes_gcm.example"
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/ademmers/84e9ae8e8271e2896c00bea6b54a1bb3

### Expected Behavior

The same/regular result you'd have with HCL equivalent: an initialized project.

### Actual Behavior

The `init` command crashes (see trace gist for details)

### Steps to Reproduce

1. `tofu init`

### Additional Context

None

### References

_No response_

### PR DESCRIPTION
**Pull request by yottta**
This changes the way encryption key_provider references are decoded.
By switching from gohcl to hcl/v2, it allows raw references and interpolated references to be processed correctly when an encryption method points to a key_provider.
The following ways of referencing a key_provider now works interchangeably.
```json
...
      "method": {
        "aes_gcm": {
          "remote_state": {
            "keys": "${key_provider.pbkdf2.mykey}"
          }
        }
      }
...
```
```json
...
      "method": {
        "aes_gcm": {
          "remote_state": {
            "keys": "key_provider.pbkdf2.mykey"
          }
        }
      }
...
```
Resolves #3482

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/encryption/keyprovider/output.go [hunk 1]
```diff
@@ -15,6 +22,38 @@ type Output struct {
...
+	var diags hcl.Diagnostics
+	mapVal := val.AsValueMap()
+	if attr, ok := mapVal["encryption_key"]; ok {
+		decodeDiags := gohcl.DecodeExpression(&hclsyntax.LiteralValueExpr{Val: attr, SrcRange: subject}, nil, &out.EncryptionKey)
+		diags = diags.Extend(decodeDiags)
+	} else {
+		return out, hcl.Diagnostics{{
+			Severity: hcl.DiagError,
+			Summary:  "Missing encryption_key value",
+			Detail:   "A encryption_key value is required in the key_provider compatible object at this location",
```
Comment (Gogotchuri) [inline internal/encryption/keyprovider/output.go]:
```suggestion
			Detail:   "An encryption_key value is required in the key_provider compatible object at this location",
```

File: internal/encryption/targets_test.go [hunk 2]
```diff
@@ -361,17 +361,72 @@ func TestBaseEncryption_methodConfigsFromTargetAndSetup(t *testing.T) {
...
+`,
 			wantErr: `Test Config Source:12,15-41: Reference to undeclared encryption method; There is no method "aes_gcm" "nonexistent" block declared in the encryption block.`,
 			wantMethods: []func(method.Method) bool{
 				unencrypted.Is,
 			},
 		},
+		// In https://github.com/opentofu/opentofu/issues/3482 was discovered that interpolation for
+		// target.method does not work, but only literal reference.
+		// This solves the inconsistencies between the way string expressions are evaluated for state.method vs method.keys.
+		"json-config-loads-state-method-interpolated": {
```
Comment (Gogotchuri) [inline internal/encryption/targets_test.go:378]: The  two cases:
- "json-config-loads-state-method-interpolated"
-  "json-config-loads-state-method-not-interpolated"
Are identical.
Shouldn't one use ${key_provider.static.basic}?

Comment (yottta) [reply internal/encryption/targets_test.go:378]: Good catch! My slip up there. Fixed in bad85f8cf1b725897d65124ba16940dbe0b7c4a4.

File: internal/encryption/keyprovider/output.go (hunk 1 above)
Comment (yottta) [reply internal/encryption/keyprovider/output.go]: Fixed in bad85f8cf1b725897d65124ba16940dbe0b7c4a4

File: CHANGELOG.md [hunk 3]
```diff
@@ -24,6 +24,7 @@ BUG FIXES:
 - In the unlikely event that text included in a diagnostic message includes C0 control characters (e.g. terminal escape sequences), OpenTofu will now replace them with printable characters to avoid the risk of inadvertently changing terminal state when stdout or stderr is a terminal. ([#3479](https://github.com/opentofu/opentofu/issues/3479))
 - Fixed `length(module.foo)` returning 0 for module instances without outputs, even when `count` or `for_each` is set. ([#3067](https://github.com/opentofu/opentofu/issues/3067))
 - Fixed `tofu test` with `mock_provider` failing during cleanup when `lifecycle { ignore_changes }` references a block. ([#3644](https://github.com/opentofu/opentofu/issues/3644))
+- Fix the way `key_provider` is decoded from the state encryption to allow the same functionality for json configuration files ([#3654](https://github.com/opentofu/opentofu/issues/3654))
```
Comment (apparentlymart) [inline CHANGELOG.md]: I'd suggest that we try to phrase this in a way that focuses more on how the user experiences the benefit rather than how we implemented it.

For example:

> - In JSON syntax, the state encryption method configuration now allows specifying keys using both normal expression syntax and using template interpolation syntax. Previously only the template interpolation syntax was allowed, which was inconsistent with other parts of the encryption configuration. ([#3654](https://github.com/opentofu/opentofu/issues/3654))

**Review by apparentlymart — APPROVED** [review]
Implementation-wise this looks good to me.

I left an inline comment earlier about the changelog. I was actually intending to submit that as part of this review 🤦‍♂️ but here we are.

In earlier discussion we also noticed that there's currently no documentation for how the state encryption features work in the JSON configuration syntax. It would be nice to add new sections to [Block-type-specific Exceptions](https://opentofu.org/docs/language/syntax/json/#block-type-specific-exceptions) describing the quirks for how these blocks are treated in JSON syntax, but it also seems okay to do that in a separate PR since this one is already quite large.

File: CHANGELOG.md (hunk 3 above)
Comment (yottta) [reply CHANGELOG.md]: Fixed in 48f79c66c833cb6a118ddbb214339f70b76b2685

**Comment by yottta** [comment]
> Implementation-wise this looks good to me.
> 
> I left an inline comment earlier about the changelog. I was actually intending to submit that as part of this review 🤦‍♂️ but here we are.
> 
> In earlier discussion we also noticed that there's currently no documentation for how the state encryption features work in the JSON configuration syntax. It would be nice to add new sections to [Block-type-specific Exceptions](https://opentofu.org/docs/language/syntax/json/#block-type-specific-exceptions) describing the quirks for how these blocks are treated in JSON syntax, but it also seems okay to do that in a separate PR since this one is already quite large.

Good point. Added in https://github.com/opentofu/opentofu/pull/3670
