### PR TITLE
Fix linting on Windows

### LINKED ISSUE #3451: Add Linting for Windows
When I run `make golangci-lint` on Windows, I currently get 9 errors in windows-specific files. I'd like it to be 0, like on Mac or Linux.

This issue is resolved when the following are completed:

- All linting issues on Windows are resolved
- An additional Windows linting step is added for pull requests

### PR DESCRIPTION
**Pull request by diofeher**
Resolves #3451 

I needed to split the `go run` command on installing it first, so the binary can be used for both Windows and Unix/Darwin.

If another maintainer is merging, please use  "Rebase and Merge". 

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [ ] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Did you find that just using `go run` twice was significantly slower than installing first and then running it? I would expect most of `go run`'s work to be cached so that a second run would be relatively fast. 

I don't mind this preinstall version if it's the only way to make it fast enough, but I like the fact that `go run` doesn't write anything in GOBIN and so it definitely won't overwrite another copy of the same tool that might be intentionally a different version than OpenTofu currently needs.

**Comment by diofeher** [comment]
@apparentlymart The problem is that when I was using `GOOS=windows` with `go run` I was receiving a different problem when running, but I'm gonna double check if it's the same error I fixed later and I'll get back to this thread.

EDIT: https://github.com/opentofu/opentofu/actions/runs/19005849382/job/54279182920

Now I've remembered that was the error when I was trying to use `go run` directly, it seems it builds for Windows and tries to use the binary in this format, while the way I implemented before, it uses the proper binary for both platforms.

**Comment by apparentlymart** [comment]
Oh yes, that makes sense... since `go run` includes both a build and a run it changes the target for the build too.

I kinda wish `go run` had an exception of always building for the host because otherwise the built binary is unlikely to work anyway, but I can understand why they wouldn't do that.

File: Makefile [hunk 1]
```diff
@@ -44,10 +44,12 @@ generate:
...
 	go run ./tools/protobuf-compile .
 
-# Golangci-lint
+# Golangci-lint is installed first and then run twice to cover all platforms.
 .PHONY: golangci-lint
 golangci-lint:
-	go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.0 run --timeout 60m ./...
+	go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.0
+	GOOS=windows golangci-lint run --timeout 60m ./...
+	golangci-lint run --timeout 60m ./...
```
Comment (apparentlymart) [inline Makefile]: Someone running this Makefile target on Windows would presumably just run in Windows mode twice with this setup.

Do you think we should use `GOOS=linux` for the other one so that everyone is always running linting on the same set of platforms? That does mean that we won't ever be running lint for darwin, but for the way we use build constraints in this codebase I don't think that will matter very much: we treat everything except Windows as mostly the same and use build constraints mainly to deal with the various oddities of Windows.

Comment (lbordowitz) [reply Makefile]: I believe `golangci-lint` has a `build-tags` flag available; could you see if that would work?

Comment (diofeher) [reply Makefile]: @lbordowitz Yep, I tested with that, but if I use build-tags with Windows, it's going to ask for specific code of Windows, and this is not going to work due to import problems.

Comment (diofeher) [reply Makefile]: @apparentlymart Oh, that's a good point! Let me change that.

Comment (apparentlymart) [reply Makefile]: Yeah, I also tried build tags first but the problem is that it adds those tags in addition to what's implied by the GOOS environment variable, and so it can create normally-impossible situations like having both "windows" and "unix" set at the same time, which then causes conflicts when importing packages that use these tags to choose between mutually-exclusive implementations.

**Review by lbordowitz — APPROVED** [review]

File: internal/flock/filesystem_lock_windows.go [hunk 2]
```diff
@@ -40,7 +41,12 @@ func Lock(f *os.File) error {
 	if err != nil {
 		return err
 	}
-	defer syscall.CloseHandle(ol.HEvent)
+	defer func() {
+		err := syscall.CloseHandle(ol.HEvent)
+		if err != nil {
+			log.Printf("failed to close handle: %v", err)
```
Comment (apparentlymart) [inline internal/flock/filesystem_lock_windows.go]: Normally when we use `log` in this codebase we use a log level prefix and include some context about what caused the log line, so maybe...

```suggestion
			log.Printf("[ERROR] failed to close file locking event handle: %v", err)
```

This is not a very specific "context" but probably the best we can do from here since this function doesn't know anything about what's its doing other than that it somehow involves locking. At least it's a relatively distinct string that would come up in code search if someone searched for it. 🤷‍♂️

File: Makefile [hunk 3]
```diff
@@ -44,10 +44,12 @@ generate:
 protobuf:
 	go run ./tools/protobuf-compile .
 
-# Golangci-lint
+# Golangci-lint is installed first and then run twice to cover all platforms.
 .PHONY: golangci-lint
 golangci-lint:
-	go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.0 run --timeout 60m ./...
+	go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.0
```
Comment (apparentlymart) [inline Makefile]: I'm still kinda concerned about this implicitly overwriting whatever is currently at `$GOBIN/golangci-lint`; a different version might've been installed there for a good reason and the person running this might not realize we've quietly overwritten it. Someone might also have installed `golangci-lint` in a different way that caused it to be somewhere other than `GOBIN`, in which case that other copy might take priority in the following two lines and cause us to run the wrong version of the tool.

As a compromise, what do you think about adding `-o tools/golangci-lint$(shell go env GOEXE)` to this command line and then changing the two lines below to run that local copy of the tool? Then we could add `tools/golangci-lint*` to our `.gitignore` to make sure the executable won't get accidentally checked in to version control. This is similar to the strategy we use for `protoc` in `make protobuf` to avoid interfering with or accidentally running any protobuf compiler that's already installed on the system where we're running.

(If you wait until https://github.com/opentofu/opentofu/pull/3452 is merged and then rebase onto it then you could use `$(EXT)` to get the `.exe` portion added when running on Windows, instead of an inline call to `go env GOEXE`.)

**Review by apparentlymart — APPROVED** [review]

File: Makefile (hunk 3 above)
Comment (diofeher) [reply Makefile]: @apparentlymart Seems a good compromise!

Comment (diofeher) [reply Makefile]: https://github.com/opentofu/opentofu/pull/3457/commits/8c0cfc0b9455cc39f07098c415a076a536ecd4ae

**Comment by diofeher** [comment]
@apparentlymart I need to find a way to set the GOBIN on Windows, I'm trying to find the most portable way.

File: .gitignore [hunk 4]
```diff
@@ -23,6 +23,9 @@ website/node_modules
 website/vendor
 vendor/
 
+# Golangci-lint
+tools/golangci-lint*
```
Comment (apparentlymart) [inline .gitignore]:
```suggestion
# "make golangci-lint" places its temprary golangci-lint executable here
tools/golangci-lint*
```

(just to make it clearer to a future reader exactly why this is here, so that e.g. they can remove it if that makefile target becomes no longer used in future)

**Review by apparentlymart — APPROVED** [review]
Just one more minor thing! This looks good to me, otherwise.

(One of my earlier comments is still unresolved but I'm assuming you'll resolve that before you merge, since you reacted 👍 to it already, and no need to wait for another round of review from me if so.)
