### PR TITLE
fix(genconfig): properly quote attribute names when necessary

### LINKED ISSUE #2520: Import generates invalid HCL for map key with period
### Community note

I was recently trying to move from render.com's proprietary YAML IaC format to TF. I generated the import configuration and ran `tofu plan -generate-config-out=render-generated.tf`. However I found that in this case the some keys are added that are in an invalid format:

```hcl
resource "render_env_group" "foo" {
  environment_id = "evm-phngluimglwnafh"
  name           = "foo"
  secret_files = {
    config.json = {
      content = "{}"
    }
  }
}
```

In this case the key `config.json` is not valid and the plan will fail. I had to do a post-processing pass that quoted such keys to get the TF file to work:

```js
renderGeneratedTf.replace(/\b([^"\s]+(?:\..+)+) = /g, (_, fileKey) => `"${fileKey}" = `);
```
>[!NOTE]
>This pass specifically fixes periods and will for example not fix keys with spaces

If someone could point me to a way to reproduce this using a mock, I'd gladly provide a reproduction.

### OpenTofu Version

```shell
OpenTofu v1.9.0
on linux_amd64
+ provider registry.terraform.io/render-oss/render v1.4.0
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    render = {
      source = "registry.terraform.io/render-oss/render"
      version = "1.4.0"
    }
  }
}

variable "render_api_key" {
  type = string
  sensitive = true
  description = "API key to use when interacting with the API."
}

provider "render" {
  api_key = var.render_api_key
  owner_id = "tea-cthulhurlyehwgahnaglfhtagn"
  skip_deploy_after_service_update = false
  wait_for_deploy_completion = false
}

import {
  to = render_env_group.foo
  id = "evg-phngluimglwnafh"
}

```

### Debug Output

Sorry, this is not the full log, as it leaked some highly sensitive data. I've tried to provide the most relevant, redacted lines:
```log
2025-02-14T09:07:21.593+0100 [WARN]  Provider "registry.terraform.io/render-oss/render" produced an unexpected new value for render_env_group.staging_api during refresh.
      - .name: was null, but now cty.StringVal("foo")
      - .secret_files: was null, but now cty.MapVal(map[string]cty.Value{"config.json":cty.ObjectVal(map[string]cty.Value{"content":cty.StringVal("{}")})})
2025-02-14T09:07:21.596+0100 [TRACE] tofu.contextPlugins: Serving provider "registry.terraform.io/render-oss/render" schema from global schema cache
2025-02-14T09:07:21.596+0100 [TRACE] NodeAbstractResourceInstance.writeResourceInstanceState to refreshState for render_env_group.foo
2025-02-14T09:07:21.596+0100 [TRACE] NodeAbstractResourceInstance.writeResourceInstanceState: writing state object for render_env_group.foo
2025-02-14T09:07:21.597+0100 [TRACE] tofu.contextPlugins: Serving provider "registry.terraform.io/render-oss/render" schema from global schema cache
2025-02-14T09:07:21.597+0100 [TRACE] NodeAbstractResourceInstance.writeResourceInstanceState to prevRunState for render_env_group.foo
2025-02-14T09:07:21.597+0100 [TRACE] NodeAbstractResourceInstance.writeResourceInstanceState: writing state object for render_env_group.foo
2025-02-14T09:07:21.597+0100 [TRACE] tofu.contextPlugins: Serving provider "registry.terraform.io/render-oss/render" schema from global schema cache
2025-02-14T09:07:21.597+0100 [TRACE] NodeAbstractResourceInstance.writeResourceInstanceState to refreshState for render_env_group.foo
2025-02-14T09:07:21.597+0100 [TRACE] NodeAbstractResourceInstance.writeResourceInstanceState: writing state object for render_env_group.foo
2025-02-14T09:07:21.598+0100 [TRACE] tofu.contextPlugins: Serving provider "registry.terraform.io/render-oss/render" schema from global schema cache
2025-02-14T09:07:21.599+0100 [TRACE] tofu.contextPlugins: Serving provider "registry.terraform.io/render-oss/render" schema from global schema cache
2025-02-14T09:07:21.599+0100 [TRACE] writeChange: recorded NoOp change for render_env_group.foo
2025-02-14T09:07:21.599+0100 [ERROR] vertex "render_env_group.foo" error: Reference to undeclared resource
2025-02-14T09:07:21.599+0100 [TRACE] vertex "render_env_group.foo": visit complete, with errors
2025-02-14T09:07:21.600+0100 [TRACE] dag/walk: upstream of "root" errored, so skipping
2025-02-14T09:07:21.600+0100 [TRACE] vertex "render_env_group.foo (expand)": dynamic subgraph encountered errors: Reference to undeclared resource
2025-02-14T09:07:21.600+0100 [ERROR] vertex "render_env_group.foo (expand)" error: Reference to undeclared resource
2025-02-14T09:07:21.600+0100 [TRACE] vertex "render_env_group.foo (expand)": visit complete, with errors
2025-02-14T09:07:21.600+0100 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/render-oss/render\"] (close)" errored, so skipping
2025-02-14T09:07:21.600+0100 [TRACE] dag/walk: upstream of "root" errored, so skipping
2025-02-14T09:07:21.600+0100 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/render-oss/render"
2025-02-14T09:07:21.600+0100 [TRACE] tofu.contextPlugins: Serving provider "registry.terraform.io/render-oss/render" schema from global schema cache
2025-02-14T09:07:21.600+0100 [INFO]  backend/local: plan operation completed
2025-02-14T09:07:21.600+0100 [TRACE] LoadSchemas: retrieving schema for provider type "registry.terraform.io/render-oss/render"
2025-02-14T09:07:21.600+0100 [TRACE] tofu.contextPlugins: Serving provider "registry.terraform.io/render-oss/render" schema from global schema cache

Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Warning: Config generation is experimental
│ 
│ Generating configuration during import is currently experimental, and the generated configuration format may change in future versions.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on render-generated.tf line 10:
│   (source code not available)
│ 
│ A managed resource "config" has not been declared in the root module.
```

### Expected Behavior

Expected output file to contain:

```hcl
# __generated__ by OpenTofu
# Please review these resources and move them into your main configuration files.

# __generated__ by OpenTofu
resource "render_env_group" "foo" {
  env_vars = {}
  environment_id = "evm-phngluimglwnafh"
  name           = "foo"
  secret_files = {
    "config.json" = {
      content = null # sensitive
    }
  }
}
```

### Actual Behavior

Output file to contains:

```hcl
# __generated__ by OpenTofu
# Please review these resources and move them into your main configuration files.

# __generated__ by OpenTofu
resource "render_env_group" "foo" {
  env_vars = {}
  environment_id = "evm-phngluimglwnafh"
  name           = "foo"
  secret_files = {
    config.json = {
      content = null # sensitive
    }
  }
}
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan -generate-config-out=render-generated.tf`

### Additional Context

It sees to be specific to the part: `cty.MapVal(map[string]cty.Value{"config.json":cty.ObjectVal`… when this map is written to the generated HCL, the map key should be quoted, because otherwise the period changes how it's parsed.

### References

_No response_

### PR DESCRIPTION
**Pull request by Yantrio**
Ensure attribute names are correctly quoted in generated config when they contain characters that make them invalid identifiers (e.g., dots, double quotes).

- Use `hclsyntax.ValidIdentifier` to check if an attribute name needs quoting.
- Convert invalid identifiers to valid HCL strings using `hclwrite.TokensForValue`.
- Add test cases for attributes with dots and double quotes to verify correctness.

Resolves #2520

## Target Release

1.10.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

**Review by yottta — DISMISSED** [review]
LGTM.

File: internal/genconfig/generate_config_test.go [hunk 1]
```diff
@@ -670,20 +768,20 @@ resource "tfcoremock_simple_resource" "example" {
 		},
 	}
 	for name, tc := range tcs {
-		t.Run(name, func(t *testing.T) {
+		t.Run(name, func(tt *testing.T) {
```
Comment (apparentlymart) [inline internal/genconfig/generate_config_test.go:771]: I expect we should probably discuss this in another place since it's not directly relevant to this PR, but I think this is one place where shadowing the parent scope's `t` is both idiomatic style _and_ wise, because it's never correct to access the parent `t` from inside a `t.Run`... if you're lucky it causes a panic, and if you're less lucky it makes the test harness get confused.

I accept that we've decided to differ from typical Go idiom in a number of different ways in this project, but this particular one seems like an unnecessary deviation from how tests are typically written in Go and seems more likely to _cause_ problems than to avoid them. :face_with_diagonal_mouth:

**Review by apparentlymart — DISMISSED** [review]
Notwithstanding my largely-off-topic previous comment about style/idiom, this does seem to me like it should solve the reported bug.

**Review by ollevche — DISMISSED** [review]

File: internal/genconfig/generate_config_test.go (hunk 1 above)
Comment (Yantrio) [reply internal/genconfig/generate_config_test.go:771]: I'm super happy to move back to shadowing :D You're right and honestly I really dont mind either way. I'll update this.

**Review by cam72cam — APPROVED** [review]
