### PR TITLE
"force-unlock" support for the HTTP backend

### LINKED ISSUE #2027: Finally allow force-unlock for remote http backend
### OpenTofu Version

```shell
OpenTofu v1.6.3
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

N/A

### Expected Behavior

successful 200

### Actual Behavior

tofu force-unlock <lock-id>

Do you really want to force-unlock?
  OpenTofu will remove the lock on the remote state.
  This will allow local OpenTofu commands to modify this state, even though it
  may still be in use. Only 'yes' will be accepted to confirm.

  Enter a value: yes

Failed to unlock state: Unexpected HTTP response code 405

### Steps to Reproduce

tofu force-unlock <lock id>

### Additional Context

This bug was reported in Terraform back in 2021. A PR was opened for the fix but wasn't accepted. There is another PR currently open on Terraform. The PR was opened back in January this year, PR is still not accepted. The issue still persists with the latest version of the OpenTofu CLI as well. If you look at the code within `client.go` on line 132, the `Unlock` function accepts the lock ID but never uses it. As a result, no lock ID is ever passed to the remote HTTP backend when performing force-unlock, causing a failure to unlock the state. This feature is important for organizations that have their own HTTP remote backend, allowing their users to use the Tofu CLI command line to unlock their state instead of using workarounds like the `curl` command. I am happy to contribute to the fix and open a PR.

https://github.com/opentofu/opentofu/blob/main/internal/backend/remote-state/http/client.go#L132

### References

_No response_

### PR DESCRIPTION
**Pull request by haiderbari**
Resolves #2027

## Target Release

1.10.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/backend/remote-state/http/client.go [hunk 1]
```diff
@@ -134,7 +134,25 @@ func (c *httpClient) Unlock(id string) error {
...
 	}
 
-	resp, err := c.httpRequest(c.UnlockMethod, c.UnlockURL, c.jsonLockInfo, "unlock")
+	var lockInfo statemgr.LockInfo
+
+	// force unlock command does not instantiate statemgr.LockInfo
+	// which means that c.jsonLockInfo will be nil
+	if c.jsonLockInfo != nil {
+		if err := json.Unmarshal(c.jsonLockInfo, &lockInfo); err != nil {
+			return fmt.Errorf("failed to unmarshal jsonLockInfo")
```
Comment (cam72cam) [inline internal/backend/remote-state/http/client.go:143]: We should probably include the err as `%w` in the fmt.Errorf here.

**Comment by haiderbari** [comment]
Hi @cam72cam I will push suggested change soon, for the checks it fails unit tests on linux arm. I presume it's not related to my changes because I did run unit tests and found no issues but I am running the tests on an AMD machine. For the linting looks like it flagged that the LockInfo struct doesn't have json tags associate with each attribute of the struct. Do I need to add the line of code in excludes list from linting or do you want me add the json tags to the struct.

**Comment by cam72cam** [comment]
You can ignore the linux arm tests, they are flaky at the moment.

Just add the nolint rule for the json tag issue and you should be fine.  We are slowly adopting linting across the project and issues like this occasionally crop up.

**Review by cam72cam — APPROVED** [review]

**Review by apparentlymart — APPROVED** [review]

**Comment by cam72cam** [comment]
Thanks @haiderbari!
