### PR TITLE
Better output for test assertions

### LINKED ISSUE #2545: Better output for failed expectations in tests
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.9.0
on darwin_arm64
```

### The problem in your OpenTofu project

As with the upstream project, it can be very difficult to debug expectation failures in tests, especially when object comparison fails. Typically, there's just a generic error like:
```
x.y is list of string with 3 elements
```
Sorry if there's an existing issue for this here as well - I looked and couldn't find one.

### Attempted Solutions

No known solutions.

### Proposal

Ideally, you would see diff style output showing the difference between the two things (separate request, maybe, but as a bonus, better "deep equality" comparison of objects would also be nice), and some additional context / debugging information in the case where they're something that can't be compared.

The current PR for implementing a fix to the linked issue seems reasonable to me, though I think the formatting could still be a little nicer.

### Workarounds and Alternatives

Currently, you'd need to try comparing specific elements or using outputs to figure out what's different or what's not matching outside of terraform.

This is not always trivial.

### References

- https://github.com/hashicorp/terraform/issues/34428
- https://github.com/hashicorp/terraform/issues/35760

### PR DESCRIPTION
**Pull request by diofeher**
Resolves #2545 

We're reusing the same mechanism that we use on our Renderers to show why a condition has failed on the Test Suite.

Screenshot 2025-07-11 at 09 12 00

Screenshot 2025-07-11 at 09 14 23

### Summary of the changes:

Two refactoring PRs were needed in order to break the dependency cycle:

- https://github.com/opentofu/opentofu/pull/3025
- https://github.com/opentofu/opentofu/pull/3028

After that, we refactored `GenerateChange` to be used to create the `structured.Change`.
Then we get the computed.Diff and pass that to the renderer in order to reuse what we use for resource diffs on plan and applies.

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [ ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [ ] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [ ] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/command/jsonplan/plan.go [hunk 1]
```diff
@@ -562,6 +562,56 @@ func MarshalResourceChanges(resources []*plans.ResourceInstanceChangeSrc, schema
...
+
+	return &Change{
+		Before:       json.RawMessage(before),
+		After:        json.RawMessage(after),
+		AfterUnknown: a,
+
+		// Just to be explicit, outputs cannot be imported so this is always
+		// nil.
+		Importing: nil,
+	}, nil
```
Comment (apparentlymart) [inline internal/command/jsonplan/plan.go]: I think we should be able to populate the `BeforeSensitive` and `AfterSensitive` fields here too, based on whether `beforeVal` and `afterVal` contain any marks.

I think the form of this previously embedded in the output value function wasn't doing it just because for root module output values it's invalid to have any sensitive parts of the value unless the output value as a whole was declared as `sensitive = true`, and so just checking the declaration is a reasonable shortcut there.

But for arbitrary values that _aren't_ from output values there could potentially be sensitive elements anywhere in the value, so we should populate the two sensitive fields correctly to avoid exposing those in cleartext in the final diff. [`jsonstate.SensitiveAsBoolWithPathValueMarks`](https://pkg.go.dev/github.com/opentofu/opentofu/internal/command/jsonstate#SensitiveAsBoolWithPathValueMarks) seems to be able to deal with that as long as we first separate the marks from the value using [`cty.Value.UnmarkDeepWithPaths`](https://pkg.go.dev/github.com/zclconf/go-cty/cty#Value.UnmarkDeepWithPaths), instead of just `cty.Value.UnmarkDeep` as this function is currently using above.)

Comment (diofeher) [reply internal/command/jsonplan/plan.go]: Oh, that's really valuable information! I'm going to refactor based on it :) Thanks!

Comment (diofeher) [reply internal/command/jsonplan/plan.go]: Fixed on https://github.com/opentofu/opentofu/pull/3009/commits/19351afbff38ba529566f3a676e3b27647f65a51, please let me know if that's what you were expecting

Comment (diofeher) [reply internal/command/jsonplan/plan.go]: I was talking to @cam72cam about it and I'm gonna open a different PR for the refactoring and leave this one only for the implementation of the improvements of the test assertion itself.

**Comment by apparentlymart** [comment]
Am I understanding correctly that this extra "Diff" part is generated whenever the diagnostic's expression is a `hcl.BinaryOpExpr`, without taking anything else into account?

I imagine we should _at least_ check whether the operation of the expression is one that's reasonable to diff. :thinking: 

`hclsyntax.OpEqual` seems like the main case we want to handle, and is the one your test cases currently focus on. In that case I wonder if we should also annotate the diff with either `left operand -> right operand` or vice-versa depending on which way we're choosing to present the diff.

`hclsyntax.OpNotEqual` seems likely to come up in test cases too, but I don't think there's really any reasonable diff to produce for that operation, since we only know what we _don't_ want and have no signal about what we _do_ want. Would you agree?

I think all of the other operators seem out of scope. For example, if someone tested `something > 2` it would be weird to show a diff for that case. If someone wrote `"a" + 2` then that would fail with an error diagnostic saying that the left operand must be a number, and so it would be very strange to include a diff `"a" -> 2` as part of that diagnostic.

**Comment by apparentlymart** [comment]
I feel uneasy about using `DiagnosticExpressionValue` to describe a diff, because those also appear in our machine-readable diagnostic serialization, like [what appears from `tofu validate -json`](https://opentofu.org/docs/cli/commands/validate/#json-output-format) and also in some of our other machine-readable output situations. As you have it implemented right now it seems like those would appear in the `"values"` property of a diagnostic's `"snippet"` object, which is inconsistent with the current documentation of that property.

I wonder about instead adding a new field `Diff` to `jsonentities.Diagnostic`, and having that field be of type `*jsonentities.Change` to directly represent the change in [our usual JSON format](https://opentofu.org/docs/internals/json-format/#change-representation) when the diff is being returned directly as JSON rather than in the human-readable form.

Then the code that translates `jsonentities.Diagnostic` into the human-oriented form would be responsible for testing whether the diff field is `!= nil` and including the extra "diff (left -> right):" section in the result, so that the human-oriented diff is only in the human-oriented output and not in the JSON output.

I'd like to see a test case for what happens when the original diagnostic has `Expression` set to a `hclsyntax.BinaryOpExpr` _and_ `EvalContext` set to contain symbols that the expression refers to, so we can test how the normal presentation of values interacts with the additional diff. My personal preference would be for the normal values to appear first and then the diff to be shown beneath, something like this:

```
╷
│ Error: Whatever the error summary happens to be
│ 
│   on example.tf line 8, in output "example":
│    8:    value = (var.foo == "foo")
│     ├────────────────
│     │ var.foo is "bar"
│     │
│     ├ difference (left -> right):
│     │ "bar" -> "foo"
│ 
│ Whatever the error detail happens to be.
╵
```

...but the other way around could be fine too, I suppose. I don't feel that strongly about it as long as both are included in a reasonable way where both can be read clearly.

(I also wrote "difference" instead of "diff" in the above. I don't feel _super_ strongly about that but it seems more accessible to use the full word here, rather than an abbreviation, because some readers might not know what "diff" is short for and the extra six characters don't seem to cause any significant layout problems.)

**Comment by diofeher** [comment]
> Am I understanding correctly that this extra "Diff" part is generated whenever the diagnostic's expression is a hcl.BinaryOpExpr, without taking anything else into account?

@apparentlymart Yes, you're right! I was researching about other types of Expr to use, but it wasn't clear to me, so I decided to start with the BinaryOpExpr. Now that I'm re-reading the https://opentofu.org/docs/language/expressions/custom-conditions/#condition-expressions I need to test with these other possible conditions.


> I think all of the other operators seem out of scope. For example, if someone tested something > 2 it would be weird to show a diff for that case. If someone wrote "a" + 2 then that would fail with an error diagnostic saying that the left operand must be a number, and so it would be very strange to include a diff "a" -> 2 as part of that diagnostic.

Hmm, that's a good point! Let me add a specific check for this one.

> hclsyntax.OpNotEqual seems likely to come up in test cases too, but I don't think there's really any reasonable diff to produce for that operation, since we only know what we don't want and have no signal about what we do want. Would you agree?

I'm not sure. When seeing the [docs](https://opentofu.org/docs/language/expressions/custom-conditions/#length-function), I could see being used multiple times, and I think by showing at least a better message instead of the type, would be helpful here.


> I wonder about instead adding a new field Diff to jsonentities.Diagnostic, and having that field be of type *jsonentities.Change to directly represent the change in [our usual JSON format](https://opentofu.org/docs/internals/json-format/#change-representation) when the diff is being returned directly as JSON rather than in the human-readable form.

I think that's a great idea! I'm not fine with these tests testing the characters and color at this point of evaluation, so I totally agree with you by adding a new field and then putting the UI evaluation higher in the chain of calls.

**Comment by diofeher** [comment]
@apparentlymart Let me know what you think about this approach: https://github.com/opentofu/opentofu/pull/3009/commits/a8a6fa9a08367d49049c63553fa4c39e6621832e

I'm feeling it's a lot better since it's easier to test and more flexible. I will add more tests tomorrow.

**Comment by apparentlymart** [comment]
This overall approach looks good to me and matches what I was thinking about.

In retrospect I think I was wrong to suggest using these types that did not previously have `json:` struct tags. I'm not sure which tags are better to use, but I was trying to suggest to use whatever we already use to produce the [Change Representation](https://opentofu.org/docs/internals/json-format/#change-representation) structure in the JSON plan output, since then the difference should be described in the same way so that consuming software could potentially reuse the same code to handle both.

I would not expect that we need to add `json:` struct tags to any new types here since it seems like we already have _some_ way to represent this as JSON... I just don't quickly remember which type we're using for that today.

**Comment by diofeher** [comment]
That's a good point @apparentlymart ! I can actually use the `jsonplan.Change`, this is what is used by the output. Thanks again for the recommendations.  https://github.com/opentofu/opentofu/pull/3009/commits/ecc8ade76f39da40274ab0aa19c8976b831ef468

File: internal/command/format/diagnostic_test.go [hunk 2]
```diff
@@ -893,6 +895,89 @@ func TestDiagnosticFromJSON_invalid(t *testing.T) {
 [red]│[reset]
 [red]│[reset] It all went wrong.
 [red]╵[reset]
+`,
```
Comment (apparentlymart) [inline internal/command/format/diagnostic_test.go]: Could you also add a test with a `jsonentities.Diagnostic` object where _both_ `Difference` and `Snippet.Values` are set at the same time?

File: internal/command/format/diagnostic_test.go [hunk 3]
```diff
@@ -893,6 +895,89 @@ func TestDiagnosticFromJSON_invalid(t *testing.T) {
...
+			`[red]╷[reset]
+[red]│[reset] [bold][red]Error: [reset][bold]Bad testing[reset]
+[red]│[reset]
+[red]│[reset]   on ohno.tf line 1:
+[red]│[reset]    1: condition = 3 == 5[underline][reset]
+[red]│[reset]
+[red]│[reset]     [dark_gray]├────────────────[reset]
+[red]│[reset]     [dark_gray]│[reset] [bold]Diff: [reset]
+[red]│[reset]     [dark_gray]│[reset] "3" [yellow]->[reset] "5"
+[red]│[reset] It all went wrong.
```
Comment (apparentlymart) [inline internal/command/format/diagnostic_test.go]: There seems to be a missing blank line before the diagnostic detail message here.

File: internal/command/format/diagnostic_test.go [hunk 4]
```diff
@@ -893,6 +895,89 @@ func TestDiagnosticFromJSON_invalid(t *testing.T) {
...
+[red]│[reset]    2:       "Test-Header-1: foo",
+[red]│[reset]    3:       "Test-Header-2: bar",
+[red]│[reset]    4:     ])
+[red]│[reset]
+[red]│[reset]     [dark_gray]├────────────────[reset]
+[red]│[reset]     [dark_gray]│[reset] [bold]Diff: [reset]
+[red]│[reset]     [dark_gray]│[reset] {
+[red]│[reset]     [dark_gray]│[reset]       [yellow]~[reset] Test-Header-2 = "foo" [yellow]->[reset] "bar"
+[red]│[reset]     [dark_gray]│[reset]         [dark_gray]# (1 unchanged attribute hidden)[reset]
+[red]│[reset]     [dark_gray]│[reset]     }
```
Comment (apparentlymart) [inline internal/command/format/diagnostic_test.go]: The indentation of this closing brace doesn't seem to align correctly with the opening brace. 🤔

File: internal/command/format/diagnostic_test.go (hunk 2 above)
Comment (apparentlymart) [reply internal/command/format/diagnostic_test.go]: Also I notice that you've added this test case to a function that is documented as testing how the code handles _invalid_ `jsonentities.Diagnostic` values, but it seems like these two examples are both valid. 🤔 Is there an invalid part of this I didn't notice?

It seems like `TestDiagnostic` is the test function that's mainly dealing with the valid cases. I notice that function starts with `tfdiags.Diagnostic` and converts it to `jsonentities.Diagnostic` first as part of the test, so the test input would need to be a diagnostic that _causes_ the `jsonentities.Diagnostic` structure you want to test rather than directly specifying the JSON version. But that seems okay... it's arguably then testing the code in a more realistic way since in practice we always generate `jsonentities.Diagnostic` from `tfdiags.Diagnostic` in real usage anyway.

Comment (diofeher) [reply internal/command/format/diagnostic_test.go]: Ok, it really seems I got confused when looking to find a place to put those tests, I understood incorrectly. Let me rework on it to put them in another place :) Thanks for the catch

Comment (diofeher) [reply internal/command/format/diagnostic_test.go]: I didn't use `TestDiagnostic` because `tfdiags` isn't implementing the `Difference` field, neither `Snippet`. I can create a different test that supports both of them, with similar structure of the `*_invalid` one but being valid :)

Comment (apparentlymart) [reply internal/command/format/diagnostic_test.go]: I was imagining that you'd have a test case that includes a `hcl.Diagnostic` which has `Expression` set to a `hcl.BinaryOpExpr` for `OpEquals`, so that it would then exercise the existing code that decides whether to populate `Difference` based on the expression.

And then for the thing I was asking about in my original comment on this thread, that diagnostic would also have `EvalContext` populated with symbols that the expression refers to, so that the `Snippet.Values` field would also get populated before rendering the diagnostic.

This does mean that you would be testing the logic that turns `tfdiags.Diagnostic` into `jsonentities.Diagnostic` at the same time as testing the rendering to the human-oriented presentation, but that matches the approach that `TestDiagnostic` is already following for its existing test cases, right?

To be specific, it would be similar to this existing test case but with the expression being a real `hcl.BinaryOpExpr`, instead of using `hcltest.MockExprTraversal` to construct a "mock" expression:

https://github.com/opentofu/opentofu/blob/71225f26b755aec38a10b0c97a026badf2b516d6/internal/command/format/diagnostic_test.go#L85-L118

File: internal/command/format/diagnostic_test.go (hunk 3 above)
Comment (diofeher) [reply internal/command/format/diagnostic_test.go]: There's still one thing that I'm not sure if it's an issue, but when using snippet values and diffs, there's one strange blank line:

Screenshot 2025-07-15 at 18 24 14

I could fix it in another PR though since it would involve touching a few different parts, and I spent some time trying to fix it already.

File: internal/command/format/diagnostic_test.go (hunk 2 above)
Comment (diofeher) [reply internal/command/format/diagnostic_test.go]: Fixed on https://github.com/opentofu/opentofu/commit/4318f3e1fa9cfa342a753a9262d439bcd317a84b#diff-52cbf76b97904138f12d8d6228ff6c6708563dcd6bc1ab70c343d5da9a839ea9R268-R289

File: internal/command/format/diagnostic_test.go (hunk 4 above)
Comment (diofeher) [reply internal/command/format/diagnostic_test.go]: Fixed on https://github.com/opentofu/opentofu/commit/4318f3e1fa9cfa342a753a9262d439bcd317a84b#diff-1d921084d76d71c1d112d7ffad8aef2604929a49433c82cb4455c541a09fb57aR142

File: internal/command/format/diagnostic_test.go (hunk 3 above)
Comment (diofeher) [reply internal/command/format/diagnostic_test.go]: But I've fixed your review on https://github.com/opentofu/opentofu/pull/3009/commits/4318f3e1fa9cfa342a753a9262d439bcd317a84b

**Comment by diofeher** [comment]
Btw, I've changed the test suite assertions of `format/diagnostic_test.go` to use `cmp.Diff` since it was really hard to debug as it was just printing the output and expected variables.

File: internal/command/format/diagnostic_test.go (hunk 3 above)
Comment (apparentlymart) [reply internal/command/format/diagnostic_test.go]: hmm, yeah... I think this quirk would also cause some weird output in the case where there is no "Snippet" in the diagnostic, because then the whole "on main.tftest.hcl blah blah..." section would be missing and we'd immediately start with the `├──` line before `Diff:`.

I guess this is why the "values" structure is nested inside "snippet" even though it's technically not part of the source code snippet: the renderer only includes values if it _also_ includes the snippet.

So I guess we have at least two options here:

1. Move the `Difference` field into `DiagnosticSnippet` and render it as part of `appendSourceSnippets`, just after the code that prints out the `DiagnosticSnippet.Values` and `DiagnosticSnippet.FunctionCall` information.

    It's a little strange to think of the diff as being part of the "snippet", but the values and function call information is already in there and is kinda similar so it's at least strange in a consistent way with the existing code.
2. Change `appendSourceSnippets` and `appendDifferenceOutput` so that neither of them include the extra trailing newline anymore, and instead print the newline in the caller only if either `Difference` or `Snippet` is set:

    https://github.com/opentofu/opentofu/blob/4318f3e1fa9cfa342a753a9262d439bcd317a84b/internal/command/format/diagnostic.go#L87-L89

I think I prefer the first option because the way we're presenting this doesn't really make sense if `Snippet` is nil while `Difference` is non-nil. The way we render this directly after the source snippet means that the diff part would look strange without the snippet directly above it.

---

Separately from all that, while I was reading the code nearby here I noticed that `DiagnosticPlainFromJSON` has some similar code where it prints the source snippets without colorization:

https://github.com/opentofu/opentofu/blob/4318f3e1fa9cfa342a753a9262d439bcd317a84b/internal/command/format/diagnostic.go#L188

...so I guess that should also call `appendDifferenceOutput`, for consistency. (IIRC `DiagnosticPlainFromJSON` is used in the `-no-color` mode, which folks use when they are running OpenTofu in a context where terminal escape sequences aren't supported.)

Comment (diofeher) [reply internal/command/format/diagnostic_test.go]: I prefer the first option too! 

Implemented on https://github.com/opentofu/opentofu/pull/3009/commits/e42ad205de9fa8f36ff82636ccfdfa6e2aa54c6b for `-no-color` and for the normal one:

Screenshot 2025-07-16 at 09 55 54

Screenshot 2025-07-16 at 09 57 35

Thanks again for the thoughtful reviews!

**Comment by diofeher** [comment]
Thanks a lot for the words, @Gogotchuri :D Just fixed the tests, waiting the pipeline to finish!
