### PR TITLE
Fix #1407: Pass through metadata fields in state encryption

### LINKED ISSUE #1407: [State Encryption] Fails to save state to Gitlab HTTP State Backend When Encrypted
### OpenTofu Version

```shell
OpenTofu v1.7.0-alpha1
on darwin_amd64
+ provider registry.opentofu.org/e-breuninger/netbox v3.8.4
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
  ...
  }
  backend "http" {
    address = "https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted"
    lock_address = "https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted/lock"
    unlock_address = "https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted/lock"
    username = "user"
    password = "glpat-xyz"
    lock_method = "POST"
    unlock_method = "DELETE"
    retry_wait_min = "5"

    
  }
  encryption {
    key_provider "pbkdf2" "test" {
      passphrase = "abcd12345xyz!@#$"
      key_length = 32
      iterations = 600000
      salt_length = 32
      hash_function = "sha512"
    }

    method "aes_gcm" "encrypt" {
      keys = key_provider.pbkdf2.test
    }


    state {
      method = method.aes_gcm.encrypt
      fallback {
       
      }
    }
  }
}
```

### Debug Output

```
2024-03-15T10:44:12.456-0400 [TRACE] Executing graph transform *tofu.TransitiveReductionTransformer
2024-03-15T10:44:12.456-0400 [TRACE] Completed graph transform *tofu.TransitiveReductionTransformer (no changes)
2024-03-15T10:44:12.456-0400 [DEBUG] Starting graph walk: walkApply
2024-03-15T10:44:12.456-0400 [TRACE] vertex "root": starting visit (*tofu.nodeCloseModule)
2024-03-15T10:44:12.456-0400 [TRACE] vertex "root": visit complete
2024-03-15T10:44:12.456-0400 [DEBUG] states/remote: state read serial is: 1; serial is: 1
2024-03-15T10:44:12.456-0400 [DEBUG] states/remote: state read lineage is: 4ddf5053-a993-fc23-eda1-2383a5767d64; lineage is: 4ddf5053-a993-fc23-eda1-2383a5767d64
2024-03-15T10:44:12.802-0400 [DEBUG] POST https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted?ID=df7262f3-793e-9689-b010-e263a5b3d4db
2024-03-15T10:44:12.958-0400 [DEBUG] POST https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted?ID=df7262f3-793e-9689-b010-e263a5b3d4db (status: 500): retrying in 5s (2 left)
2024-03-15T10:44:18.087-0400 [DEBUG] POST https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted?ID=df7262f3-793e-9689-b010-e263a5b3d4db (status: 500): retrying in 10s (1 left)
2024-03-15T10:44:28.226-0400 [TRACE] statemgr.Filesystem: reading initial snapshot from errored.tfstate
2024-03-15T10:44:28.926-0400 [TRACE] statemgr.Filesystem: read snapshot with lineage "4ddf5053-a993-fc23-eda1-2383a5767d64" serial 3
2024-03-15T10:44:28.926-0400 [TRACE] statemgr.Filesystem: Importing snapshot with lineage "4ddf5053-a993-fc23-eda1-2383a5767d64" serial 2 over snapshot with lineage "4ddf5053-a993-fc23-eda1-2383a5767d64" serial 3 at errored.tfstate
2024-03-15T10:44:28.926-0400 [TRACE] statemgr.Filesystem: forcing lineage "4ddf5053-a993-fc23-eda1-2383a5767d64" serial 2 for migration/import
2024-03-15T10:44:28.926-0400 [TRACE] statemgr.Filesystem: preparing to manage state snapshots at errored.tfstate
2024-03-15T10:44:29.603-0400 [TRACE] statemgr.Filesystem: existing snapshot has lineage "4ddf5053-a993-fc23-eda1-2383a5767d64" serial 3
2024-03-15T10:44:29.603-0400 [TRACE] statemgr.Filesystem: state file backups are disabled
2024-03-15T10:44:29.603-0400 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2024-03-15T10:44:29.603-0400 [TRACE] statemgr.Filesystem: writing snapshot at errored.tfstate
╷
│ Error: Failed to save state
│ 
│ Error saving state: Failed to upload state: POST https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted?ID=df7262f3-793e-9689-b010-e263a5b3d4db giving up after 3 attempt(s)
╵
╷
│ Error: Failed to persist state to backend
│ 
│ The error shown above has prevented OpenTofu from writing the updated state to the configured backend. To allow for recovery, the state has been written to the file "errored.tfstate" in the current working directory.
│ 
│ Running "tofu apply" again at this point will create a forked state, making it harder to recover.
│ 
│ To retry writing this state, use the following command:
│     tofu state push errored.tfstate
│ 
╵
2024-03-15T10:44:29.948-0400 [DEBUG] DELETE https://gitlab.com/api/v4/projects/1234/terraform/state/encrypted/lock

```

### Expected Behavior

HTTP Backend should work with the encrypted state format.

### Actual Behavior

HTTP 500 Error when saving state to Gitlab HTTP state backend.

### Steps to Reproduce

1. Configure HTTP backend config
2. `tofu init`
3. `tofu apply`
4. Change config to add encryption
5. `tofu apply`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
Some backends require certain fields like "serial" in order to function. It is relatively safe to keep some of these metadata fields in the encrypted state json payload.

Long term, we should remove this metadata, but this provides a better user experience for the initial migration to encrypted state as different backends take time to adjust their expectations.

Currently only "serial" and "linage" are passed through.

Resolves #1407 

## Target Release

1.7.0

### CODE REVIEW

**Review by Evi1Pumpkin — APPROVED** [review]
Hope we won't need it, but looking good overall

File: internal/encryption/base.go [hunk 1]
```diff
@@ -117,7 +117,7 @@ func (s *baseEncryption) encrypt(data []byte) ([]byte, error) {
 		Meta:    s.encMeta,
 		Data:    encd,
 	}
-	jsond, err := json.Marshal(es)
+	jsond, err := json.Marshal(enhance(es))
```
Comment (ollevche) [inline internal/encryption/base.go:120]: It feels kinda hacky. If there are more use-cases, we should consider delegating serialization and validation outside of `baseEncryption` since they are already "leaked"

**Review by ollevche — APPROVED** [review]
Looks good, thank you! One minor comment for future extension

File: internal/encryption/base.go (hunk 1 above)
Comment (cam72cam) [reply internal/encryption/base.go:120]: I'm hoping that long-term we can revert this PR, but I'm not sure that it's realistic to do so as there are many many http backends.

Comment (cam72cam) [reply internal/encryption/base.go:120]: The alternate (without a larger refactor) would be doing a unmarshal/enchance/marshal inside of state.go, which adds a lot of overhead.

Comment (ollevche) [reply internal/encryption/base.go:120]: I agree that the current implementation is the most optimal. Let's see where it goes in the future, thanks!
