### PR TITLE
Handle ignoring computed fields in ignore_changes blocks for testing

### LINKED ISSUE #3644: test mocking errors on cleanup.
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.11.2
on linux_amd64
```

### OpenTofu Configuration Files

https://github.com/grimm26/tftest

### Debug Output

https://gist.github.com/grimm26/584ae145c0dcccf149f294740167056e

### Expected Behavior

All tests passing and clean exit.

### Actual Behavior

```
tests/vm.tftest.hcl... pass
  run "ansible"... pass
  run "ansible_no_email"... pass
  run "chef"... pass
  run "environment_fail"... pass
  run "memory_fail"... pass
  run "custom_network_interface"... pass
  run "default_network_interface"... pass
  run "xenial_network_interface"... pass
  run "datastore_cluster_suffix_default"... pass
  run "datastore_cluster_suffix_db"... pass
  run "datastore_cluster_suffix_wharf"... pass
  run "datastore_cluster_suffix_invalid"... pass
OpenTofu encountered an error destroying resources created while executing tests/vm.tftest.hcl/datastore_cluster_suffix_wharf.
╷
│ Error: Invalid mock/override field `device_address`
│ 
│   with vsphere_virtual_machine.vm["module-test-ds-wharf01"],
│   on host.tf line 19, in resource "vsphere_virtual_machine" "vm":
│   19: resource "vsphere_virtual_machine" "vm" {
│ 
│ Config value can not be specified for computed field
╵
╷
│ Error: Invalid mock/override field `key`
│ 
│   with vsphere_virtual_machine.vm["module-test-ds-wharf01"],
│   on host.tf line 19, in resource "vsphere_virtual_machine" "vm":
│   19: resource "vsphere_virtual_machine" "vm" {
│ 
│ Config value can not be specified for computed field
╵

OpenTofu left the following resources in state after executing tests/vm.tftest.hcl/datastore_cluster_suffix_wharf, these left-over
resources can be viewed by reading the statefile written to disk(errored_test.tfstate) and they need to be cleaned up manually:
  - infoblox_ip_allocation.ib["module-test-ds-wharf01"]
  - random_shuffle.cluster_pool["module-test-ds-wharf01"]
  - vsphere_virtual_machine.vm["module-test-ds-wharf01"]

Writing state to file: errored_test.tfstate

Success! 12 passed, 0 failed.
```

### Steps to Reproduce

1. clone the referenced repo
2. tofu init -backend=false
3. tofu test

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by Yantrio**
When a resource has `lifecycle { ignore_changes = [ block ] }` on a
block, the processIgnoreChanges will copy the entire prior state block
to the config including computed-only fields. I didn't want to change
the behaviour of what happens to all providers, only the mock providers
so this change will fix the issue by filtering computed-only attributes
from the configuration before passing it on.

Resolves #3644

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by Yantrio** [comment]
Note for merger: When merging this please merge unsquashed commits to facilitate backporting to 1.11 easier.

It seems that this is not a bug in 1.10

File: internal/tofu/provider_for_test_framework.go [hunk 1]
```diff
@@ -68,14 +69,35 @@ func (p providerForTest) PlanResourceChange(_ context.Context, r providers.PlanR
...
 	resp.PlannedState, resp.Diagnostics = newMockValueComposer(r.TypeName).
-		ComposeBySchema(resSchema, r.Config, p.overrideValues)
+		ComposeBySchema(resSchema, filteredConfig, p.overrideValues)
 
 	return resp
 }
 
+// filterComputedOnlyAttributes returns a copy of value where all computed-only attributes
+// (i.e. computed and not optional) defined in resSchema are replaced with null values.
+func filterComputedOnlyAttributes(resSchema *configschema.Block, value cty.Value) cty.Value {
```
Comment (diofeher) [inline internal/tofu/provider_for_test_framework.go:85]: From what I was checking, `resSchema` can be nil, based on the implementation of `p.schema.SchemaForResourceType` and its return value. Should we add a nil check before going further in the function to avoid calling `resSchema.AttributeByPath` on a nil value?

Comment (Yantrio) [reply internal/tofu/provider_for_test_framework.go:85]: good catch, I'll add a nil check and I'll also add a unit test to cover some of this too.

Comment (Yantrio) [reply internal/tofu/provider_for_test_framework.go:85]: Resolved in 36161d879ddd7fc0a91b6846c0f72f2a746cd40e

File: internal/tofu/provider_for_test_framework.go [hunk 2]
```diff
@@ -68,14 +69,36 @@ func (p providerForTest) PlanResourceChange(_ context.Context, r providers.PlanR
...
+	if resSchema == nil || value.IsNull() || !value.IsKnown() {
+		// Nothing to filter here, or we dont know how to filter
+		// so we should move on
+		return value
+	}
+
+	ret, _ := cty.Transform(value, func(path cty.Path, v cty.Value) (cty.Value, error) {
```
Comment (yottta) [inline internal/tofu/provider_for_test_framework.go:92]: Checked the error returned by `cty.Transform` and seems that in this particular case is safe to ignore it. Just want to highlight this for others to be sure that I didn't miss a thing.
