### PR TITLE
Fix destroy/orphan path with provider instances

### LINKED ISSUE #2149: Error: provider provider["registry.opentofu.org/hashicorp/aws"].<alias> not initialized is not very explanatory
### OpenTofu Version

```shell
OpenTofu v1.9.0-alpha1
on linux_amd64
+ provider registry.opentofu.org/hashicorp/aws v5.74.0
```

### OpenTofu Configuration Files

```hcl
provider "aws" {
  for_each = var.students

  alias = "student"

  assume_role {
    role_arn = "arn:aws:iam::${module.student-account[each.key].account.id}:role/OrganizationAccountAccessRole"
  }
}

# create 1 AWS account per student
module "student-account" {
  source = "./mod-student-account"

  for_each   = var.students

  email      = each.value["email"]
  student_id = each.key
  parent_id  = aws_organizations_organizational_unit.training.id

}
```

### Debug Output

[available on request]

### Expected Behavior

I'd like to know what is wrong and how to fix it.
Should I decommission resources before I remove the providers ?
Do I have orphan resources ? Do I have a broken state ?

### Actual Behavior

The current error messages are not very explanatory: 
```
Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: provider provider["registry.opentofu.org/hashicorp/aws"].student not initialized
│
│
╵
╷
│ Error: provider provider["registry.opentofu.org/hashicorp/aws"].student not initialized
│
│
╵
```

### Steps to Reproduce

`tofu destroy`

### Additional Context

using tofu with the followin context:
 - env variables comming from `summon` (AWS credentials)
 - tf variables comming from `terragrunt`
 
the full command I used to get this error is:
`TF_LOG=debug summon -up tofu destroy --var-file=./terragrunt-debug.tfvars.json`

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
As reported in the linked issue, the destroy path was broken in the alpha due to https://github.com/opentofu/opentofu/pull/2105.  I additionally noticed that we had some related issues with orphaned instances.

For the destroy scenario, I realized that `NodeDestroyResourceInstance`s are created without a corresponding expansion data.  In that scenario, we are unable to use the configuration to determine the correct provider instance keys and should instead rely on the state.

In the `NodePlanResourceInstanceOrphaned` scenario, only the `NodePlanResourceInstance`s have corresponding expansion data from the configuration.  If provider keys are in use and expansion data can't be determined, we should try to default to the state.

Overall this mixes in some logic from the ProviderTransformer attempting to deal with nodes missing configuration, but can really only be fixed when we re-design the provider reference system from the ground up.

Resolves #2149

## Target Release

1.9.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/tofu/context_apply2_test.go [hunk 1]
```diff
@@ -4150,3 +4151,265 @@ func TestContext2Apply_excludedModuleRecursive(t *testing.T) {
 <no state>
 	`)
 }
+
+func TestContext2_providerResourceIteration(t *testing.T) {
```
Comment (apparentlymart) [inline internal/tofu/context_apply2_test.go:4155]: Nit: The tests in this and the other "apply" file tend to start with `TestContext2Apply` to differentiate them from the context tests for other phases. (This is _very very occasionally_ useful for using `-run='^TestContext2Apply_'` to filter down the tests by phase, but it's admittedly marginal given how broad a scope these tests cover.)

**Review by apparentlymart — APPROVED** [review]
This makes sense to me and I agree that, while this is clunky, it's the most pragmatic solution for the current shape of things.

In the long run I think we ought to try to standardize on having the initial plan graph contain only whole resources and never resource instances _in all cases_, since the little exceptions like whole-resource orphans being treated differently has been a repeated maintenance hazard. That's too risky a change for how late we are in this release's development period, though.

**Review by apparentlymart — APPROVED** [review]
