### PR TITLE
Fix test crash when using deprecated outputs in the root module

### LINKED ISSUE #3246: tofu test assert crashes when output is deprecated
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.10.6
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
output "example" {
  value = "example"
  deprecated = "for reasons"
}
```

and in a test file...

```hcl
run "example" {
  command = plan

  assert {
    condition = output.example == "example"
    error_message = "ruh-roh"
  }
}
```

### Debug Output

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

ReferenceFromCall used with root module output

Success! 1 passed, 0 failed.
goroutine 16 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:18 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2feb360, 0x3d068f0}, {0xc0001b9400, 0x276, 0x400})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xd6
github.com/opentofu/opentofu/internal/command.(*TestCommand).Run.PanicHandlerWithTraceFn.func4()
        github.com/opentofu/opentofu/internal/logging/panic.go:82 +0x8a
panic({0x2feb360?, 0x3d068f0?})
        runtime/panic.go:792 +0x132
github.com/opentofu/opentofu/internal/addrs.AbsOutputValue.ModuleCallOutput(...)
        github.com/opentofu/opentofu/internal/addrs/output_value.go:200
github.com/opentofu/opentofu/internal/lang/marks.DeprecatedOutput({{{0x3d4c118?, 0xc0001aeba9?}}, {0x2feb360?, 0xc000098cf0?}}, {{0x0, 0x0, 0x0}, {{}, {0xc000a05290, 0x7}}}, ...)
        github.com/opentofu/opentofu/internal/lang/marks/marks.go:110 +0x1fb
github.com/opentofu/opentofu/internal/tofu.(*evaluationStateData).GetOutput(0xc0008e22d0, {{}, {0xc000a05340?, 0x3008db100?}}, {{0xc000a022d0, 0x12}, {0x5, 0x15, 0x41}, {0x5, ...}})
        github.com/opentofu/opentofu/internal/tofu/evaluate.go:1025 +0x434
github.com/opentofu/opentofu/internal/lang.(*evalVarBuilder).putValueBySubject(0xc0008db3b8, 0x0?)
        github.com/opentofu/opentofu/internal/lang/eval.go:520 +0xe23
github.com/opentofu/opentofu/internal/lang.(*Scope).evalContext(0xc0008e2360, 0x0, {0xc0006961f0, 0x1, 0x1}, {0x0, 0x0})
        github.com/opentofu/opentofu/internal/lang/eval.go:381 +0x765
github.com/opentofu/opentofu/internal/lang.(*Scope).EvalContext(...)
        github.com/opentofu/opentofu/internal/lang/eval.go:309
github.com/opentofu/opentofu/internal/tofu.(*TestContext).evaluate(0xc0003c9bc0, 0x28?, 0xc000099170, 0xc00090a410, 0x2)
        github.com/opentofu/opentofu/internal/tofu/test_context.go:180 +0x8d7
github.com/opentofu/opentofu/internal/tofu.(*TestContext).EvaluateAgainstPlan(0xc0003c9bc0, 0xc00090a410)
        github.com/opentofu/opentofu/internal/tofu/test_context.go:70 +0xe5
github.com/opentofu/opentofu/internal/command.(*TestFileRunner).ExecuteTestRun(0xc0008dbe18, {0x3d4bd28, 0xc00086b1d0}, 0xc00090a410, 0xc00090a460, 0xc0007969b0, 0xc0002b7ea0)
        github.com/opentofu/opentofu/internal/command/test.go:618 +0x10d8
github.com/opentofu/opentofu/internal/command.(*TestFileRunner).ExecuteTestFile(0xc0008dbe18, {0x3d4bd28, 0xc00086b1d0}, 0xc00090a460)
        github.com/opentofu/opentofu/internal/command/test.go:483 +0x4c9
github.com/opentofu/opentofu/internal/command.(*TestSuiteRunner).Start(0xc000202b60, {0x3d4bd28, 0xc00086b1d0})
        github.com/opentofu/opentofu/internal/command/test.go:408 +0x1bd
github.com/opentofu/opentofu/internal/command.(*TestCommand).Run.func2()
        github.com/opentofu/opentofu/internal/command/test.go:302 +0x6c
created by github.com/opentofu/opentofu/internal/command.(*TestCommand).Run in goroutine 1
        github.com/opentofu/opentofu/internal/command/test.go:296 +0xfb4
With go-routine called from:
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:26 +0x5e
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
        github.com/opentofu/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/command.(*TestCommand).Run(0xc0008c0488, {0xc0001a4090?, 0x0?, 0x0?})
        github.com/opentofu/opentofu/internal/command/test.go:295 +0xe85
github.com/mitchellh/cli.(*CLI).Run(0xc00090e3c0)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x4de
main.realMain()
        github.com/opentofu/opentofu/cmd/tofu/main.go:335 +0x1e6b
main.main()
        github.com/opentofu/opentofu/cmd/tofu/main.go:65 +0x13
```

### Expected Behavior

Test succeeds with no crash

### Actual Behavior

The test runs successfully, but then the process crashes.

If you remove the `deprecated` argument from the output block, the test runs successfully with no crash.

### Steps to Reproduce

1. `tofu init`
2. `tofu test`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
Marking a root output as deprecated has no impact. We hit this case when using the test framework on a module.

Resolves #3246 

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

**Review by Gogotchuri — APPROVED** [review]

File: internal/lang/marks/marks.go [hunk 1]
```diff
@@ -117,6 +117,12 @@ func Deprecated(v cty.Value, cause DeprecationCause) cty.Value {
 // DeprecatedOutput marks a given values as deprecated constructing a DeprecationCause
 // from module output specific data.
 func DeprecatedOutput(v cty.Value, addr addrs.AbsOutputValue, msg string, isFromRemoteModule bool) cty.Value {
+	if addr.Module.IsRoot() {
+		// Marking a root output as deprecated has no impact.
+		// We hit this case when using the test framework on a module however.
+		// This is requried as the ModuleCallOutput() below will panic on the root module.
```
Comment (diofeher) [inline internal/lang/marks/marks.go:123]: Ops, just noticed that we didn't see this typo here @cam72cam
