### PR TITLE
Module Expansion Transformer now skips creating edges for check related nodes

### LINKED ISSUE #3060: Depending on a module with a check in it causes a dependency cycle
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.10.1
on linux_amd64
+ provider registry.opentofu.org/hashicorp/http v3.5.0
```

### OpenTofu Configuration Files

The below config is also in a repro repo: https://github.com/jwhitaker-gridcog/tf-module-dep-problem

```hcl
# main.tf
module "base" {
  source = "./base_module"
}

module "dependent_module" {
  source     = "./dependent_module"
  depends_on = [module.base]
}
```

```hcl
# base_module/main.tf
resource "terraform_data" "res" {
  input = "dep_123"
}
module "checker" {
  source = "../submodule_with_check"
}
```

```hcl
# dependent_module/main.tf
resource "terraform_data" "res" {
  input = "dep_456"
}
module "checker" {
  source = "../submodule_with_check"
}
```

```hcl
# submodule_with_check/main.tf
check "check_example" {
  data "http" "check_example" {
    url = "https://wttr.in/Melbourne?format=j1"
  }
  assert {
    condition     = jsondecode(data.http.check_example.response_body).current_condition[0].temp_C < 40
    error_message = "It's too hot for tofu, try icecream instead"
  }
}
```

### Debug Output

[trace.log in repro repo](https://github.com/jwhitaker-gridcog/tf-module-dep-problem/blob/main/trace.log)

### Expected Behavior

This configuration should apply, as it does if you comment out the `check` block.

### Actual Behavior

I get a dep cycle:

```
│ Error: Cycle:
  module.base.module.checker (close),
  module.base (close),
  module.dependent_module (expand),
  module.dependent_module.terraform_data.res (expand),
  module.dependent_module.terraform_data.res, (execute checks),
  module.base.module.checker.data.http.check_example,
  module.base.module.checker.check.check_example (expand)
```

### Steps to Reproduce

1. clone repro repo: https://github.com/jwhitaker-gridcog/tf-module-dep-problem
2. `tofu init`
3. `tofu apply`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by baa-ableton**
Resolves #3060 

When module.dependent_module has depends_on = [module.base], and both modules use a shared check module, a cycle is created. In ModuleExpansionTransformer.Transform(), we are now skipping connecting check-related nodes to module closers.

## Checklist

- [X] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [X] I have not used an AI coding assistant to create this PR.
- [X] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [X] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [X] I have run golangci-lint on my change and receive no errors relevant to my code.
- [X] I have run existing tests to ensure my code doesn't break anything.
- [ ] I have added tests for all relevant use cases of my code, and those tests are passing.
- [ ] I have only exported functions, variables and structs that should be used from other packages.
- [X] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/tofu/transform_module_expansion.go [hunk 1]
```diff
@@ -235,3 +245,31 @@ func (t *pathTree) find(addr []string) dag.Set {
...
+		config = n.Config
+	case *nodeExpandPlannableResource:
+		config = n.Config
+	case *nodeExpandApplyableResource:
+		config = n.Config
+	case *NodePlannableResourceInstance:
+		config = n.Config
+	case *NodeApplyableResourceInstance:
+		config = n.Config
+	}
```
Comment (Yantrio) [inline internal/tofu/transform_module_expansion.go]: Whilst I think this approach could work, I'm slightly worried about the possibilities for regressions in the future with new node types.

What do you think about checking if the node is a `GraphNodeConfigResource` (it should be in this case), and then once you have that you can check everything you need to. 

I think something similar to this may work: (Note my development env isn't working today, so this may need some tweaks!)

```go
func (t *ModuleExpansionTransformer) isNestedCheckDataSource(v dag.Vertex) bool {
    cfgNode, ok := v.(GraphNodeConfigResource)
    if !ok {
        return false
    }

    addr := cfgNode.ResourceAddr()
    if addr.Resource.Mode != addrs.DataResourceMode {
        return false
    }

    config := t.Config.Descendent(addr.Module)
    if config == nil {
        return false
    }

    resource := config.Module.DataResources[addr.Resource.String()]
    if resource != nil && resource.Container != nil {
        _, isCheck := resource.Container.(*configs.Check)
        return isCheck
    }

    return false
}
```

**Comment by baa-ableton** [comment]
Hey @Yantrio , I will check the inline comments today. As for the reproduction case in the relevant issue, I was able to test it and the issue was resolved.

File: internal/tofu/transform_module_expansion.go (hunk 1 above)
Comment (baa-ableton) [reply internal/tofu/transform_module_expansion.go]: Hey @Yantrio , I decided to copy/paste your code since I don't think any additional checks are needed. Like you said this will be more generic for more resource types in the future

**Comment by baa-ableton** [comment]
Please check plan/apply:
```bash
opentofu/issue-3060-repro on  3060 [!?] 
➜ /tmp/tofu plan                  
module.base.terraform_data.res: Refreshing state... [id=87d6ae99-1bb1-89ee-c5f2-d0af789b934a]
module.dependent_module.terraform_data.res: Refreshing state... [id=6280bfcf-4e10-e98d-fb10-8993d586033a]
module.base.module.checker.data.http.check_example: Reading...
module.dependent_module.module.checker.data.http.check_example: Reading...
module.dependent_module.module.checker.data.http.check_example: Still reading... [10s elapsed]
module.base.module.checker.data.http.check_example: Still reading... [10s elapsed]
module.base.module.checker.data.http.check_example: Read complete after 16s [id=https://wttr.in/Melbourne?format=3]
module.dependent_module.module.checker.data.http.check_example: Read complete after 16s [id=https://wttr.in/Melbourne?format=3]

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
 <= read (data resources)

OpenTofu will perform the following actions:

  # module.base.module.checker.data.http.check_example will be read during apply
  # (config will be reloaded to verify a check block)
 <= data "http" "check_example" {
      + body                 = <<-EOT
            Melbourne: ☀️   +17°C
        EOT
      + id                   = "https://wttr.in/Melbourne?format=3"
      + response_body        = <<-EOT
            Melbourne: ☀️   +17°C
        EOT
      + response_body_base64 = "TWVsYm91cm5lOiDimIDvuI8gICArMTfCsEMK"
      + response_headers     = {
          + "Access-Control-Allow-Origin" = "*"
          + "Content-Length"              = "27"
          + "Content-Type"                = "text/plain; charset=utf-8"
          + "Date"                        = "Tue, 06 Jan 2026 16:08:15 GMT"
        }
      + status_code          = 200
      + url                  = "https://wttr.in/Melbourne?format=3"
    }

  # module.dependent_module.module.checker.data.http.check_example will be read during apply
  # (config will be reloaded to verify a check block)
 <= data "http" "check_example" {
      + body                 = <<-EOT
            Melbourne: ☀️   +17°C
        EOT
      + id                   = "https://wttr.in/Melbourne?format=3"
      + response_body        = <<-EOT
            Melbourne: ☀️   +17°C
        EOT
      + response_body_base64 = "TWVsYm91cm5lOiDimIDvuI8gICArMTfCsEMK"
      + response_headers     = {
          + "Access-Control-Allow-Origin" = "*"
          + "Content-Length"              = "27"
          + "Content-Type"                = "text/plain; charset=utf-8"
          + "Date"                        = "Tue, 06 Jan 2026 16:08:15 GMT"
        }
      + status_code          = 200
      + url                  = "https://wttr.in/Melbourne?format=3"
    }

Plan: 0 to add, 0 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so OpenTofu can't guarantee to take exactly these
actions if you run "tofu apply" now.

opentofu/issue-3060-repro on  3060 [!?] took 18s 
➜ /tmp/tofu apply
module.base.terraform_data.res: Refreshing state... [id=87d6ae99-1bb1-89ee-c5f2-d0af789b934a]
module.dependent_module.terraform_data.res: Refreshing state... [id=6280bfcf-4e10-e98d-fb10-8993d586033a]
module.base.module.checker.data.http.check_example: Reading...
module.dependent_module.module.checker.data.http.check_example: Reading...
module.base.module.checker.data.http.check_example: Read complete after 10s [id=https://wttr.in/Melbourne?format=3]
module.dependent_module.module.checker.data.http.check_example: Still reading... [10s elapsed]

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
 <= read (data resources)

OpenTofu will perform the following actions:

  # module.base.module.checker.data.http.check_example will be read during apply
  # (config will be reloaded to verify a check block)
 <= data "http" "check_example" {
      + body                 = <<-EOT
            Melbourne: ☀️   +17°C
        EOT
      + id                   = "https://wttr.in/Melbourne?format=3"
      + response_body        = <<-EOT
            Melbourne: ☀️   +17°C
        EOT
      + response_body_base64 = "TWVsYm91cm5lOiDimIDvuI8gICArMTfCsEMK"
      + response_headers     = {
          + "Access-Control-Allow-Origin" = "*"
          + "Content-Length"              = "27"
          + "Content-Type"                = "text/plain; charset=utf-8"
          + "Date"                        = "Tue, 06 Jan 2026 16:08:15 GMT"
        }
      + status_code          = 200
      + url                  = "https://wttr.in/Melbourne?format=3"
    }

  # module.dependent_module.module.checker.data.http.check_example will be read during apply
  # (config will be reloaded to verify a check block)
 <= data "http" "check_example" {
      + body                 = (known after apply)
      + id                   = (known after apply)
      + response_body        = (known after apply)
      + response_body_base64 = (known after apply)
      + response_headers     = (known after apply)
      + status_code          = (known after apply)
      + url                  = "https://wttr.in/Melbourne?format=3"
    }

Plan: 0 to add, 0 to change, 0 to destroy.
╷
│ Warning: Error making request
│ 
│   with module.dependent_module.module.checker.data.http.check_example,
│   on submodule_with_check/main.tf line 2, in check "check_example":
│    2:   data "http" "check_example" {
│ 
│ timeout error: GET https://wttr.in/Melbourne?format=3 giving up after 1 attempt(s): Get
│ "https://wttr.in/Melbourne?format=3": net/http: TLS handshake timeout
╵

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.dependent_module.module.checker.data.http.check_example: Reading...
module.base.module.checker.data.http.check_example: Reading...
module.dependent_module.module.checker.data.http.check_example: Still reading... [20s elapsed]
module.dependent_module.module.checker.data.http.check_example: Read complete after 5s [id=https://wttr.in/Melbourne?format=3]
module.base.module.checker.data.http.check_example: Read complete after 8s [id=https://wttr.in/Melbourne?format=3]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by baa-ableton** [comment]
@Yantrio I would like to add a test fixture as part of this PR, should we simply use the case described in the issue? Could you also please help me exactly where the fixture should go in the directory tree? I'm afraid I dont have full grasp on the testing fixture structure

File: internal/tofu/transform_module_expansion.go [hunk 2]
```diff
@@ -67,6 +67,16 @@ func (t *ModuleExpansionTransformer) Transform(_ context.Context, g *Graph) erro
 		case *nodeCloseModule:
 			// a module closer cannot connect to itself
 			continue
+		case *nodeExpandCheck, *nodeReportCheck, *nodeCheckAssert:
+			// Check nodes should not get edges added to.
+			// This prevents cycles when a module with checks is referenced
+			// via depends_on by another module.
+			continue
+		}
```
Comment (apparentlymart) [inline internal/tofu/transform_module_expansion.go:77]:
```suggestion
		case *nodeExpandCheck, *nodeReportCheck, *nodeCheckAssert:
			// Check-related nodes are not module-close dependencies because
			// they don't produce any values that could potentially contribute
			// to a module's output values, and skipping these edges avoids
			// dependency cycles when a module containing checks is used
			// in a depends_on in the parent module.
			continue
		}
```

This is just a slightly more elaborate comment to try to capture the reason why we think it's okay to skip adding these dependencies, in addition to the reason why we _need_ to skip adding these dependencies. We've had some recent experience elsewhere with trying to understand why certain special cases are present in graph construction, so I hope this'll be helpful context for a future maintainer someday. 😀

**Comment by Yantrio** [comment]
@baa-ableton I recommend placing a new set of test data based on the original reporting case (simplified if you can) into `/internal/tofu/testdata/test-name`. and then the golang for the test case could be added to `internal/tofu/context_plan_test.go`. 

It could be quite a simple test just to assert that an error doesn't happen.

**Comment by diofeher** [comment]
Should we add a CHANGELOG entry for this bug fix? @opentofu/maintainers-new

**Comment by baa-ableton** [comment]
Hey @diofeher should I create the changelog entry?

**Comment by yottta** [comment]
> Hey @diofeher should I create the changelog entry?

Yes, that would be great. Thanks

**Review by yottta — APPROVED** [review]

**Review by diofeher — APPROVED** [review]
