### PR TITLE
Always return null value for write-only attributes from the mock provider for 'tofu test'

### LINKED ISSUE #3964: test cleanup fails with mocked provider with a resource type that has a write-only attribute
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.11.4
on linux_amd64
+ provider registry.opentofu.org/hashicorp/helm v3.1.1
```

### OpenTofu Configuration Files

```hcl
resource "helm_release" "foo" {
  name       = "nothing"
  repository = "https://github.com/stuff"
  chart      = "broken"
  version    = "1.0.0"
  namespace  = "bar"
  set_wo = [
    {
      name  = "thing"
      value = "dont-tell-anyone"
    }
  ]
}

terraform {
  required_version = "~> 1.11"
  required_providers {
    helm = {
      source  = "hashicorp/helm"
      version = ">= 3.0"
    }
  }
}
```

### Debug Output

Here's the errored state: https://gist.github.com/grimm26/a5b5e1599b99df0e9cfa4437352fdc3b

### Expected Behavior

Just work :). Handle ephemeral/wo attributes like they should be.

### Actual Behavior

Didn't work :). Wrote wo attributes to state.

### Steps to Reproduce

1. tofu init
2. tofu test

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by yottta**
Resolves #3964

This fixes the way values are generated during 'tofu test' for write-only attributes.
A write-only attribute should always be null in the response of the provider, which matches the [behavior of the
terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework/blob/4f243a8faa2716d4c34abd6e8b26766ecc920821/internal/fwserver/write_only_nullification.go#L17-L21).

The fix provided here ignores any of the other rules to generate values because a write-only attribute, regardless if it's required/optional/computed, should be null in the returned state (planned state during `plan` or final state during `apply`).

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/configs/hcl2shim/mock_value_composer.go [hunk 1]
```diff
@@ -148,7 +150,9 @@ func (mvc MockValueComposer) composeMockValueForAttributes(attrs map[string]*con
 		}
 
 		// Determine the value
-		if attr.Required {
+		if attr.WriteOnly {
+			mockAttrs[k] = cty.NullVal(attr.ImpliedType())
```
Comment (cam72cam) [inline internal/configs/hcl2shim/mock_value_composer.go:154]: Should we error if the user tries to set an override for this attr?

Comment (yottta) [reply internal/configs/hcl2shim/mock_value_composer.go:154]: Good question, Since write-only promise stands in having it returned as null from the provider, setting such an override will do nothing, is useless.
I don't think that it worths adding an error for such cases.
Maybe we could add something in the docs?

Comment (cam72cam) [reply internal/configs/hcl2shim/mock_value_composer.go:154]: When useless attrs are set, we typically warn users why it won't work in the mocking system.

Comment (yottta) [reply internal/configs/hcl2shim/mock_value_composer.go:154]: WDYT? fd522945ab6478dacf214b904f36067edcd67195

Comment (cam72cam) [reply internal/configs/hcl2shim/mock_value_composer.go:154]: Looks reasonable to me.  Would be good to have @Yantrio double check as we built this truth table together.

Comment (Yantrio) [reply internal/configs/hcl2shim/mock_value_composer.go:154]: It looks reasonable to me too. I like the approach

File: internal/configs/hcl2shim/mock_value_composer.go [hunk 2]
```diff
@@ -148,7 +150,16 @@ func (mvc MockValueComposer) composeMockValueForAttributes(attrs map[string]*con
...
+			if hasOverride {
+				diags = diags.Append(tfdiags.WholeContainingBody(
+					tfdiags.Warning,
+					fmt.Sprintf("Encountered override for write-only attribute `%v`", k),
+					"Override values for write-only attributes has no impact since the write-only attributes will always be null in the provider response.",
```
Comment (Yantrio) [inline internal/configs/hcl2shim/mock_value_composer.go]:
```suggestion
					"Override values for write-only attributes have no impact since the write-only attributes will always be null in the provider response.",
```

Comment (yottta) [reply internal/configs/hcl2shim/mock_value_composer.go]: Fixed in 39bf32816ec66168aaf0b0ee347c292cfe00d741
