### PR TITLE
Catch invalid name in provider_meta before it causes a crash

### LINKED ISSUE #2345: Invalid chars in provider_meta will cause crash
### OpenTofu Version

```shell
1.10.0-dev
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">= 1.5.7"

  # Intentional typo below to force a crash. The correct would be "google-beta" instead.
  provider_meta "google_beta" { # 
    hello = "world"
  }
}
```

### Debug Output

N/A

### Expected Behavior

A error level diagnostic is produced to complain about the invalid name in provider_meta

### Actual Behavior

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

must contain only letters, digits, and dashes, and may not use leading or trailing dashes
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.23/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go-1.23/src/runtime/debug/stack.go:18 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2d3cb20, 0xc00054c4a0}, {0x0, 0x0, 0x0})
        /home/cmesh/OpenTOFU/opentofu-community/internal/logging/panic.go:96 +0xd6
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        /home/cmesh/OpenTOFU/opentofu-community/internal/logging/panic.go:51 +0x85
panic({0x2d3cb20?, 0xc00054c4a0?})
        /usr/lib/go-1.23/src/runtime/panic.go:785 +0x132
github.com/opentofu/opentofu/internal/addrs.MustParseProviderPart({0xc0006e8310?, 0x7fab50465358?})
        /home/cmesh/OpenTOFU/opentofu-community/internal/addrs/provider.go:195 +0x45
github.com/opentofu/opentofu/internal/addrs.NewDefaultProvider(...)
        /home/cmesh/OpenTOFU/opentofu-community/internal/addrs/provider.go:91
github.com/opentofu/opentofu/internal/addrs.ImpliedProviderForUnqualifiedType({0xc0006e8310?, 0x505ea108?})
        /home/cmesh/OpenTOFU/opentofu-community/internal/addrs/provider.go:83 +0xcf
github.com/opentofu/opentofu/internal/configs.(*Module).ImpliedProviderForUnqualifiedType(...)
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/module.go:809
github.com/opentofu/opentofu/internal/configs.(*Module).ProviderForLocalConfig(0x0?, {{0xc0006e8310?, 0x60?}, {0x0?, 0x2fecb80?}})
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/module.go:795 +0xaf
github.com/opentofu/opentofu/internal/configs.(*Module).appendFile(0xc000225100, 0xc00066a1a0)
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/module.go:349 +0xd9b
github.com/opentofu/opentofu/internal/configs.NewModule({0xc00056c108, 0x1, 0x46fff8?}, {0x0, 0x0, 0xc00056c0f0?}, {{0x0, 0x0, 0x0}, 0xc00099c798, ...}, ...)
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/module.go:226 +0x909
github.com/opentofu/opentofu/internal/configs.NewModuleWithTests({0xc00056c108?, 0x39aaa00?, 0x7?}, {0x0?, 0x53e70c0?, 0x0?}, 0xc0008b56e0, {{0x0, 0x0, 0x0}, ...}, ...)
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/module.go:154 +0x7b
github.com/opentofu/opentofu/internal/configs.(*Parser).LoadConfigDirWithTests(0xc000142e80, {0x399a930, 0x1}, {0x336043b?, 0x0?}, {{0x0, 0x0, 0x0}, 0xc00099c798, {0x399a930, ...}, ...})
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/parser_config_dir.go:89 +0x41e
github.com/opentofu/opentofu/internal/command.(*Meta).loadSingleModuleWithTests(0xc000766400, {0xc00007e064?, 0xc00083c9f0?}, {0x336043b, 0x5})
        /home/cmesh/OpenTOFU/opentofu-community/internal/command/meta_config.go:198 +0x2a5
github.com/opentofu/opentofu/internal/command.(*InitCommand).Run(0xc000766400, {0xc000074050, 0x0, 0x0})
        /home/cmesh/OpenTOFU/opentofu-community/internal/command/init.go:193 +0x13da
github.com/mitchellh/cli.(*CLI).Run(0xc0006c4140)
        /home/cmesh/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x55f
main.realMain()
        /home/cmesh/OpenTOFU/opentofu-community/cmd/tofu/main.go:347 +0x1fcb
main.main()
        /home/cmesh/OpenTOFU/opentofu-community/cmd/tofu/main.go:66 +0x13
```

### Steps to Reproduce

tofu init

### Additional Context

This bug goes back to commit https://github.com/opentofu/opentofu/commit/759b76436af, which was present prior to the fork. This bug was originally reported to the Terraform project, but impacts the MPL2.0 origin of both codebases.

The provider names in provider_meta are treated as such through the config package, but can be returned from `configs.decodeProviderMetaBlock` even when not proper identifiers.  This will lead to the panic documented above.

### References

- Terraform Issue where the bug was originally documented: https://github.com/hashicorp/terraform/issues/35835

### PR DESCRIPTION
**Pull request by marcinwyszynski**
The name of the provider in the `provider_meta` block is enforced by `addrs.MustParseProviderPart`. The caller chain of the affected function assumes that if the returned `ProviderMeta` is not `nil`, it is valid. Hence the panic later.

The fix is to return `nil` if *any* of the diagnostics in this function fail with an error.

Resolves #2345 

## Target Release

1.10.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [ ] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/configs/provider_meta.go [hunk 1]
```diff
@@ -31,7 +31,9 @@ func decodeProviderMetaBlock(block *hcl.Block) (*ProviderMeta, hcl.Diagnostics)
 	}
 
 	// verify that the local name is already localized or produce an error.
```
Comment (Yantrio) [inline internal/configs/provider_meta.go:33]: This comment should be updated to reflect that it's no longer throwing an error but instead returning early.

File: internal/configs/testdata/invalid-modules/provider-meta-invalid-name/main.tf [hunk 2]
```diff
@@ -0,0 +1,5 @@
+terraform {
```
Comment (Yantrio) [inline internal/configs/testdata/invalid-modules/provider-meta-invalid-name/main.tf:1]: I see this new file has been added but is a test already referencing it? I couldn't find one but maybe im blind.

Comment (marcinwyszynski) [reply internal/configs/testdata/invalid-modules/provider-meta-invalid-name/main.tf:1]: Took me a while as well. There's a magical test that picks up all the directories in the `invalid-modules` directory and runs them as individual test cases.

File: internal/configs/provider_meta.go (hunk 1 above)
Comment (marcinwyszynski) [reply internal/configs/provider_meta.go]: That's fair. PTAL 🙏🏻

File: internal/configs/testdata/invalid-modules/provider-meta-invalid-name/main.tf (hunk 2 above)
Comment (Yantrio) [reply internal/configs/testdata/invalid-modules/provider-meta-invalid-name/main.tf:1]: Oh awesome :D

**Review by Yantrio — APPROVED** [review]
I'm happy with this, I'd like to get @cam72cam's eyes on this too as he knows this better than I

**Comment by cam72cam** [comment]
My only additional feedback would be to ask for a changelog entry.  Thanks @marcinwyszynski!

**Comment by marcinwyszynski** [comment]
Added the requested entry @cam72cam. PTAL 🙏🏻

**Review by cam72cam — APPROVED** [review]
