### PR TITLE
fix(s3): allow aliases for kms key

### LINKED ISSUE #669: s3backend: doesn't support kms key aliases
### OpenTofu Version

```shell
OpenTofu v1.6.0-dev
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {

    region       = "us-east-1"

    encrypt    = true
    bucket     = "prodigy-terraform-state-dev"
    key        = "v2/us-east-1/test/random/terraform.tfstate"
    kms_key_id = "arn:aws:kms:us-east-1:<account id>:alias/aws/s3"

    dynamodb_table = "terraform-state"
  }

}

variable "length" {
  default     = 18
  description = "Length of random string to create"
}


resource "random_string" "random" {
  length = var.length
}

```

### Debug Output

2023-10-05T13:18:21.788-0400 [INFO]  OpenTofu version: 1.6.0 dev
2023-10-05T13:18:21.788-0400 [DEBUG] using github.com/hashicorp/go-tfe v1.32.0
2023-10-05T13:18:21.788-0400 [DEBUG] using github.com/cube2222/hcl/v2 v2.0.0-20231005102050-b9c5ea273216
2023-10-05T13:18:21.788-0400 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2023-10-05T13:18:21.788-0400 [DEBUG] using github.com/zclconf/go-cty v1.13.2
2023-10-05T13:18:21.788-0400 [INFO]  Go runtime version: go1.21.1
2023-10-05T13:18:21.788-0400 [INFO]  CLI args: []string{"/Users/andrew.denhertog/go/bin/tofu", "init"}
2023-10-05T13:18:21.788-0400 [TRACE] Stdout is not a terminal
2023-10-05T13:18:21.788-0400 [TRACE] Stderr is a terminal of width 100
2023-10-05T13:18:21.788-0400 [TRACE] Stdin is a terminal
2023-10-05T13:18:21.789-0400 [DEBUG] Attempting to open CLI config file: /Users/andrew.denhertog/.tofurc
2023-10-05T13:18:21.789-0400 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-10-05T13:18:21.789-0400 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-10-05T13:18:21.789-0400 [DEBUG] ignoring non-existing provider search directory /Users/andrew.denhertog/.terraform.d/plugins
2023-10-05T13:18:21.789-0400 [DEBUG] ignoring non-existing provider search directory /Users/andrew.denhertog/Library/Application Support/io.terraform/plugins
2023-10-05T13:18:21.789-0400 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2023-10-05T13:18:21.790-0400 [DEBUG] Found the config directory: /Users/andrew.denhertog/.terraform.d
2023-10-05T13:18:21.790-0400 [INFO]  CLI command args: []string{"init"}
2023-10-05T13:18:21.795-0400 [TRACE] Meta.Backend: built configuration for "s3" backend with hash value 3871393137
2023-10-05T13:18:21.795-0400 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2023-10-05T13:18:21.795-0400 [DEBUG] New state was assigned lineage "73888908-c147-c1ba-8405-8be51fd56ba7"
2023-10-05T13:18:21.795-0400 [TRACE] Meta.Backend: moving from default local state only to "s3" backend
2023-10-05T13:18:21.795-0400 [DEBUG] checking for provisioner in "."
2023-10-05T13:18:21.795-0400 [DEBUG] checking for provisioner in "/Users/andrew.denhertog/go/bin"
2023-10-05T13:18:21.796-0400 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2023-10-05T13:18:21.796-0400 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2023-10-05T13:18:21.796-0400 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2023-10-05T13:18:21.796-0400 [TRACE] statemgr.Filesystem: read nil snapshot
2023-10-05T13:18:21.796-0400 [TRACE] Meta.Backend: ignoring local "default" workspace because its state is empty
╷
│ Error: Invalid KMS Key ARN
│
│   on main.tf line 9, in terraform:
│    9:     kms_key_id = "arn:aws:kms:us-east-1:719845697152:alias/aws/s3"
│
│ Value must be a valid KMS Key ARN, got "arn:aws:kms:us-east-1:719845697152:alias/aws/s3"
╵

### Expected Behavior

Successfully pull from s3 backend with the use of a kms key alias

### Actual Behavior

```
╷
│ Error: Invalid KMS Key ARN
│
│   on main.tf line 9, in terraform:
│    9:     kms_key_id = "arn:aws:kms:us-east-1:<account id>:alias/aws/s3"
│
│ Value must be a valid KMS Key ARN, got "arn:aws:kms:us-east-1:<account id>:alias/aws/s3"
╵

```

### Steps to Reproduce

with the provided openTofu config file, this error is thrown on `tofu init`

### Additional Context

_No response_

### References

- https://github.com/hashicorp/terraform/issues/33979
- https://github.com/hashicorp/terraform/pull/33993

### PR DESCRIPTION
**Pull request by andrewhertog**
Release 1.6.0 broke the ability to use s3 key aliases in the s3 backend. This change adjusts the tests, and validation of kms key arn's to look for aliases

Resolves #669

## Target Release

1.6.0

### BUG FIXES

 

-  Fixes the ability to use KMS key aliases in the S3 backend

### CODE REVIEW

**Comment by marcinwyszynski** [comment]
@andrewhertog would you mind adding the changelog entry as part of this PR? Otherwise having read the relevant S3 and KMS docs multiple times I see no reason whatsoever to disallow key aliases.

**Review by marcinwyszynski — APPROVED** [review]

File: internal/backend/remote-state/s3/validate.go [hunk 1]
```diff
@@ -12,6 +12,7 @@ import (
 const (
 	multiRegionKeyIdPattern = `mrk-[a-f0-9]{32}`
 	uuidRegexPattern        = `[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[ab89][a-f0-9]{3}-[a-f0-9]{12}`
+	aliasRegexPattern       = `alias/(.*)`
```
Comment (maunzCache) [inline internal/backend/remote-state/s3/validate.go:15]:
```suggestion
	aliasRegexPattern       = `^alias/[a-zA-Z0-9/_-]+$`
```

I guess this should match https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-alias.html#aws-resource-kms-alias-properties

Comment (andrewhertog) [reply internal/backend/remote-state/s3/validate.go:15]: The match filter for the characters is fine, but because the anchors are already in the code this would break it. I'll add the change to the filter though

Comment (andrewhertog) [reply internal/backend/remote-state/s3/validate.go:15]: I've tried several different iterations of the above and they all break the tests. I'm going to leave it as is for now, unless @marcinwyszynski would prefer it gets fixed.

I've tried the above as well as `alias\/[a-zA-Z0-9\/\-\_]+`

Comment (marcinwyszynski) [reply internal/backend/remote-state/s3/validate.go:15]: The anchors can't be part of this `const` because it's part of an expression that already has them. Curious though what breaks when you replace `(.*)` with `[a-zA-Z0-9/_-]+`?

Comment (andrewhertog) [reply internal/backend/remote-state/s3/validate.go]: Added this change in a different commit, as i don't know if i can edit a suggestion.

Comment (andrewhertog) [reply internal/backend/remote-state/s3/validate.go]: Ok, I fixed the issue. I needed to add `()` around the regex to define it as a capture group for the one match look up.

**Comment by marcinwyszynski** [comment]
Thanks a lot for your contribution @andrewhertog !
