### PR TITLE
Fixes #1594: Support lower-case http/https_proxy env variables in S3 backend

### LINKED ISSUE #1594: s3 state backend no longer honours `https_proxy` environment variable
### OpenTofu Version

```shell
OpenTofu v1.6.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {
    # A configuration using Amazon S3
  }
}
```

### Debug Output

Not needed

### Expected Behavior

When operating in an environment where access to the internet is via a proxy server, and with an `https_proxy` environment variable defined, OpenTofu should use the configured proxy server, **as HashiCorp Terraform v1.5.7 correctly does**.

### Actual Behavior

OpenTofu disregards the environment variable. It tries to reach S3 directly, and eventually times out and fails.

### Steps to Reproduce

Do any command which tries to talk to the state backend (e.g. `tofu init`, `tofu plan`) in an environment with an `s3` backend configured, a `https_proxy` environment variable set, and no access to the S3 service other than through the proxy.

### Additional Context

The environment variables `http_proxy`, `HTTP_PROXY`, etc. are not well standardized. The blog post https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/ provides a good survey of the state of the world.

One of the conclusions there is that **the lowercased variables are preferred by many systems**.

OpenTofu is currently breaking from the prevailing direction by honouring the uppercased variable names exclusively, and this **differs from HashiCorp Terraform** behaviour.

For consistency with other widely deployed software, including HashiCorp Terraform, I believe OpenTofu should honour the lowercased versions of the proxy environment variables.

### References

Looking through Git history, it appears likely this was introduced by #770.

### PR DESCRIPTION
**Pull request by janosdebugs**
This is a lightweight fix for #1594 which now supports the `http_proxy` and `https_proxy` (lowercase) environment variables. The tests will likely be retrofitted later due to their complexity in the original PR (#1676).

## Target Release

1.8.0

## Checklist

- [X] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [X] I have not used an AI coding assistant to create this PR.
- [X] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.

### Go checklist

 

- [X] I have run golangci-lint on my change and receive no errors relevant to my code.
- [X] I have run existing tests to ensure my code doesn't break anything.
- [ ] ~I have added tests for all relevant use cases of my code, and those tests are passing.~
- [X] I have only exported functions, variables and structs that should be used from other packages.
- [X] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/backend/remote-state/s3/backend.go [hunk 1]
```diff
@@ -732,9 +732,10 @@ func (b *Backend) Configure(obj cty.Value) tfdiags.Diagnostics {
 		// Note: we don't need to read env variables explicitly because they are read implicitly by aws-sdk-base-go:
 		// see: https://github.com/hashicorp/aws-sdk-go-base/blob/v2.0.0-beta.41/internal/config/config.go#L133
 		// which relies on: https://cs.opensource.google/go/x/net/+/refs/tags/v0.18.0:http/httpproxy/proxy.go;l=89-96
-		HTTPProxy:            aws.String(stringAttrDefaultEnvVar(obj, "http_proxy", "HTTP_PROXY")),
-		HTTPSProxy:           aws.String(stringAttrDefaultEnvVar(obj, "https_proxy", "HTTPS_PROXY")),
-		NoProxy:              stringAttrDefaultEnvVar(obj, "no_proxy", "NO_PROXY"),
+		//
+		// Note: we are switching to "separate" mode here since the legacy mode is deprecated and should no longer be
+		// used.
+		HTTPProxyMode:        awsbase.HTTPProxyModeSeparate,
```
Comment (ollevche) [inline internal/backend/remote-state/s3/backend.go:738]: Should we switch when we have proper test coverage?

**Review by ollevche — APPROVED** [review]

**Review by cam72cam — DISMISSED** [review]

**Review by cam72cam — APPROVED** [review]
