### PR TITLE
Fix bug in import 'to' parsing in json configurations

### LINKED ISSUE #1652: Error parsing import statement in HCL-JSON
### OpenTofu Version

```shell
» tofu --version                                       
OpenTofu v1.7.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.95.0
```

### OpenTofu Configuration Files

```
{
  "//": {
    "metadata": {
      "backend": "pg",
      "imports": {
        "azurerm_storage_account": [
          "storageAccount"
        ]
      },
      "stackName": "storageAccount1234",
      "version": "0.20.7"
    },
    "outputs": {
    }
  },
  "import": [
    {
      "id": "/subscriptions/cfb45937-0e77-4aaa-a3ec-d2d83e4df678/resourceGroups/test1234/providers/Microsoft.Storage/storageAccounts/storageAccount1234",
      "to": "azurerm_storage_account.storageAccount"
    }
  ],
  "provider": {
    "azurerm": [
      {
        "features": {
        }
      }
    ]
  },
  "resource": {
    "azurerm_storage_account": {
      "storageAccount": {
        "//": {
          "metadata": {
            "path": "storageAccount1234/storageAccount",
            "uniqueId": "storageAccount"
          }
        },
        "account_replication_type": "LRS",
        "account_tier": "Standard",
        "lifecycle": {
          "ignore_changes": [
            "location"
          ]
        },
        "location": "westus",
        "name": "lzstorageaccount1234",
        "resource_group_name": "storageAccount1234"
      }
    }
  },
  "terraform": {
    "backend": {
      "pg": {
        "conn_str": "postgres://postgres:mysecretpassword@localhost/terraform_backend?sslmode=disable"
      }
    },
    "required_providers": {
      "azurerm": {
        "source": "azurerm",
        "version": "3.95.0"
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/aherbst-broad/4e7730390be12825dfcbac95c70f52c2

### Expected Behavior

The plan and subsequent apply should succeed instead of erroring out. Running against Terraform 1.8.3 succeeds.

### Actual Behavior

`tofu plan` errors out like this:

```
╷
│ Error: Invalid import address expression
│
│   on cdk.tf.json line 19, in import[0]:
│   19:       "to": "azurerm_storage_account.storageAccount"
│
│ Import address must be a reference to a resource's address, and only allows for indexing with dynamic keys. For example: module.my_module[expression1].aws_s3_bucket.my_buckets[expression2] for resources inside of modules, or simply
│ aws_s3_bucket.my_bucket for a resource in the root module
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### Additional Context

_No response_

### References

May be related to this [commit](https://github.com/opentofu/opentofu/commit/63c88507a878513cf7f860eceefd024a6da78b57)

### PR DESCRIPTION
**Pull request by Evi1Pumpkin**
When we introduced the `import for_each` feature in 1.7.0, we accidentally broke the parsing of `to` addresses in `import` blocks when using JSON configuration. This PR should fix this issue:
1. Now, if the `to` expression originates from a JSON configuration, it'll first be parsed to a regular HCL expression. I used an existing logic from `replace_trigger_by` decoding and extracted it to a shared function in `parser_config.go`.
2. Added tests for JSON configurations for `import` block and `replace_trigger_by` attribute.

Resolves #1652

## Target Release

1.8.0 (and will be backported to 1.7.2)

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have marked any code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from. 

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/configs/parser_config.go [hunk 1]
```diff
@@ -370,3 +371,27 @@ var configFileExperimentsSniffBlockSchema = &hcl.BodySchema{
 		{Name: "language"},
 	},
 }
+
+// Sometimes, we manually parse an expression instead of using the hcl library
+// for parsing. In this case we need to handle json configs specially, as the
+// values will be json strings rather than hcl.
+func convertJSONExpressionToHCL(expr hcl.Expression) (hcl.Expression, hcl.Diagnostics) {
```
Comment (cam72cam) [inline internal/configs/parser_config.go:378]: Perhaps this should be moved to the hcl2shim package?  That's where we have historically stored hcl helper functions (though that's a longer discussion).

**Comment by cam72cam** [comment]
Looks good!  Only one minor nit pick.

**Review by ollevche — APPROVED** [review]

File: internal/configs/parser_config.go (hunk 1 above)
Comment (Evi1Pumpkin) [reply internal/configs/parser_config.go:378]: [Done](https://github.com/opentofu/opentofu/pull/1665/commits/95916b88dcbe5976845032350ef6c1c9c25a7f7d)

**Review by ollevche — APPROVED** [review]
