### PR TITLE
Fix: When a RequiredProvider is having syntax errors, return an empty one to allow further validations to generate their diags

### LINKED ISSUE #2344: Syntax error in required_providers causes crash
### OpenTofu Version

```shell
1.10.0-dev
```

### OpenTofu Configuration Files

main.tf 
```hcl
terraform {
  required_providers {
    tfcoremock = {
      source = "tfcoremock"
      version = "0.3.0"
    }
  }
}

resource "tfcoremock_simple_resource" "foo" {}
```
other.tf 
```hcl
terraform {
  required_providers {
    tfcoremock = {
      source = "tfcoremock"
      version = "0.3.0"
    {
  }
}

resource "tfcoremock_simple_resource" "bar" {}
```

### Debug Output

N/A

### Expected Behavior

Syntax error

### Actual Behavior

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.23/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go-1.23/src/runtime/debug/stack.go:18 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2e95fc0, 0x5307290}, {0x0, 0x0, 0x0})
        /home/cmesh/OpenTOFU/opentofu-community/internal/logging/panic.go:96 +0xd6
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        /home/cmesh/OpenTOFU/opentofu-community/internal/logging/panic.go:51 +0x85
panic({0x2e95fc0?, 0x5307290?})
        /usr/lib/go-1.23/src/runtime/panic.go:785 +0x132
github.com/opentofu/opentofu/internal/configs.NewModule({0xc0005150a0, 0x2, 0x46fff8?}, {0x0, 0x0, 0xc000515080?}, {{0x0, 0x0, 0x0}, 0xc000b80e28, ...}, ...)
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/module.go:199 +0x131c
github.com/opentofu/opentofu/internal/configs.NewModuleWithTests({0xc0005150a0?, 0x39aaa00?, 0x7?}, {0x0?, 0x53e70c0?, 0x0?}, 0xc0005be660, {{0x0, 0x0, 0x0}, ...}, ...)
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/module.go:154 +0x7b
github.com/opentofu/opentofu/internal/configs.(*Parser).LoadConfigDirWithTests(0xc00081e1e0, {0x399a930, 0x1}, {0x336043b?, 0x0?}, {{0x0, 0x0, 0x0}, 0xc000b80e28, {0x399a930, ...}, ...})
        /home/cmesh/OpenTOFU/opentofu-community/internal/configs/parser_config_dir.go:89 +0x41e
github.com/opentofu/opentofu/internal/command.(*Meta).loadSingleModuleWithTests(0xc0002bc400, {0xc00007e064?, 0xc00082ccf0?}, {0x336043b, 0x5})
        /home/cmesh/OpenTOFU/opentofu-community/internal/command/meta_config.go:198 +0x2a5
github.com/opentofu/opentofu/internal/command.(*InitCommand).Run(0xc0002bc400, {0xc000074050, 0x0, 0x0})
        /home/cmesh/OpenTOFU/opentofu-community/internal/command/init.go:193 +0x13da
github.com/mitchellh/cli.(*CLI).Run(0xc0002a2640)
        /home/cmesh/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x55f
main.realMain()
        /home/cmesh/OpenTOFU/opentofu-community/cmd/tofu/main.go:347 +0x1fcb
main.main()
        /home/cmesh/OpenTOFU/opentofu-community/cmd/tofu/main.go:66 +0x13
```

### Steps to Reproduce

tofu init

### Additional Context

This bug goes back to commit 7ca7b1f0fe6, which was present prior to the fork.  This bug was originally reported to the Terraform project, but impacts the MPL2.0 origin of both codebases.

When the required_providers block is parsed, a nil value can be returned if the block is invalid and is then added to the `configs.File`.  During the duplicate block detection logic in `configs.NewModule`, we emit error messages to notify the user of the invalid configuration.  A nil value from a broken required_providers block can produce the above panic when it's information is used to build the diagnostic message.

This could either be fixed by adding a nil check, or returning a valid (but empty) required_providers struct from parsing instead of nil.

I lean toward the second as it would still attempt to provide the user with clear information as to the source of the duplicate block.

### References

- Terraform Issue where the bug was originally documented: https://github.com/hashicorp/terraform/issues/35532

### PR DESCRIPTION
**Pull request by yottta**
Resolves #2344

Instead of just adding a nil check, just return an empty RequiredProvider to ensure that down the line we are not getting a panic.
Checking the usage `decodeRequiredProvidersBlock` function, the changes made should have no other side-effects.

## Target Release

1.10.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/configs/module_test.go [hunk 1]
```diff
@@ -210,6 +210,31 @@ func TestModule_required_provider_overrides(t *testing.T) {
...
+		t.Fatal("module should have error diags, but does not")
+	}
+
+	want := []string{
+		`Missing attribute value; Expected an attribute value`,
+		`Unexpected "resource" block; Blocks are not allowed here`,
+		`Duplicate required providers configuration`,
+	}
+	if wantLen, gotLen := len(want), len(diags.Errs()); wantLen != gotLen {
+		t.Fatalf("got less errors than expected. Expected %d but got %d", wantLen, gotLen)
```
Comment (RLRabinowitz) [inline internal/configs/module_test.go:229]: nit

It's not necessarily "less errors than expected"

```suggestion
		t.Fatalf("number of errors is not as expected. Expected %d but got %d", wantLen, gotLen)
```

File: internal/configs/provider_requirements.go [hunk 2]
```diff
@@ -33,16 +33,18 @@ type RequiredProviders struct {
...
-
 	ret := &RequiredProviders{
 		RequiredProviders: make(map[string]*RequiredProvider),
 		DeclRange:         block.DefRange,
 	}
 
+	attrs, diags := block.Body.JustAttributes()
+	if diags.HasErrors() {
+		// Returns an empty RequiredProvider to allow further validations to work properly,
+		// allowing to return correctly all the diagnostics.
```
Comment (RLRabinowitz) [inline internal/configs/provider_requirements.go:44]:
```suggestion
		// allowing to return all the diagnostics correctly.
```

**Review by RLRabinowitz — DISMISSED** [review]
Looks good 🙏🏻

File: internal/configs/module_test.go (hunk 1 above)
Comment (yottta) [reply internal/configs/module_test.go]: Fixed. Thanks. 
Indeed, the message could have been confusing when it comes to the actual validation.

File: internal/configs/provider_requirements.go (hunk 2 above)
Comment (yottta) [reply internal/configs/provider_requirements.go]: Fixed.
Done.

**Review by cam72cam — DISMISSED** [review]

**Review by cam72cam — APPROVED** [review]
