### PR TITLE
Cloud Backend - Fix logic that forces TF_WORKSPACE to be equal to a tag name

### LINKED ISSUE #1787: TF_WORKSPACE must be explicitly defined in tags, rather than matching on the configured tags
### OpenTofu Version

```shell
1.7.3
```

### OpenTofu Configuration Files

```hcl
terraform {
  cloud {
    organization = "$organizationId"
    hostname = "hostname.com"

    workspaces {
      tags = ["demo"]
    }
  }
}

variable "region" {
  type = string
}

resource "random_string" "test" {
  length = 8
}

output "region_suffix" {
  value = "${var.region}-${random_string.test.result}"  
}
```

### Debug Output

```
TF_LOG=trace TF_WORKSPACE=tofu-demo-1 tofu plan
2024-07-09T12:09:36.910-0400 [INFO]  OpenTofu version: 1.7.3
2024-07-09T12:09:36.910-0400 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2024-07-09T12:09:36.910-0400 [DEBUG] using github.com/opentofu/hcl/v2 v2.0.0-20240416130056-03228b26f391
2024-07-09T12:09:36.910-0400 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-07-09T12:09:36.910-0400 [DEBUG] using github.com/zclconf/go-cty v1.14.4
2024-07-09T12:09:36.910-0400 [INFO]  Go runtime version: go1.21.3
2024-07-09T12:09:36.910-0400 [INFO]  CLI args: []string{"/Users/rwittman/.asdf/installs/opentofu/1.7.3/bin/tofu", "plan"}
2024-07-09T12:09:36.910-0400 [TRACE] Stdout is a terminal of width 108
2024-07-09T12:09:36.910-0400 [TRACE] Stderr is a terminal of width 108
2024-07-09T12:09:36.910-0400 [TRACE] Stdin is a terminal
2024-07-09T12:09:36.910-0400 [DEBUG] Attempting to open CLI config file: /Users/rwittman/.tofurc
2024-07-09T12:09:36.910-0400 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-07-09T12:09:36.910-0400 [INFO]  Loading CLI configuration from /Users/rwittman/.terraform.d/credentials.tfrc.json
2024-07-09T12:09:36.911-0400 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-07-09T12:09:36.911-0400 [DEBUG] ignoring non-existing provider search directory /Users/rwittman/.terraform.d/plugins
2024-07-09T12:09:36.911-0400 [DEBUG] ignoring non-existing provider search directory /Users/rwittman/Library/Application Support/io.terraform/plugins
2024-07-09T12:09:36.911-0400 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2024-07-09T12:09:36.911-0400 [DEBUG] Found the config directory: /Users/rwittman/.terraform.d
2024-07-09T12:09:36.911-0400 [INFO]  CLI command args: []string{"plan"}
2024-07-09T12:09:36.911-0400 [TRACE] Meta.Backend: built configuration for "cloud" backend with hash value 2856480487
2024-07-09T12:09:36.911-0400 [TRACE] Preserving existing state lineage "5062a514-a077-340b-638b-033b9d5fcc1c"
2024-07-09T12:09:36.911-0400 [TRACE] Preserving existing state lineage "5062a514-a077-340b-638b-033b9d5fcc1c"
2024-07-09T12:09:36.911-0400 [TRACE] Meta.Backend: working directory was previously initialized for "cloud" backend
2024-07-09T12:09:36.911-0400 [TRACE] Meta.Backend: using already-initialized, unchanged "cloud" backend configuration
╷
│ Error: Invalid workspaces configuration
│ 
│ The workspace defined using the environment variable "TF_WORKSPACE" does not belong to "tags".
│ 
│ The 'workspaces' block configures how OpenTofu CLI maps its workspaces for this single
│ configuration to workspaces within a cloud backend organization. Two strategies are available:
│ 
│ [bold]tags[reset] - A set of tags used to select remote cloud backend workspaces to be used for this
│ single
│ configuration. New workspaces will automatically be tagged with these tag values. Generally, this
│ is the primary and recommended strategy to use. This option conflicts with "name".
│ 
│ [bold]name[reset] - The name of a single cloud backend workspace to be used with this configuration.
│ When configured, only the specified workspace can be used. This option conflicts with "tags"
```

### Expected Behavior

I have an implementation of the cloud backend for usage with OpenTofu. If I have 2 workspaces, with the appropriate tags, such as 
```
tofu-demo-1: {"tags":["demo"]}
tofu-demo-2: { "tags": ["demo"]}
```
I expect that I should be able to do 
```shell 
tofu init 
TF_WORKSPACE=tofu-demo-1 tofu plan
TF_WORKSPACE=tofu-demo-2 tofu plan
```
to operate on 2 different workspaces in the cloud, while using the same configuration. 

### Actual Behavior

Tofu seems to require that the workspace defined by`TF_WORKSPACE` be defined explicitly in the list of tags, which I think defeats the purpose of using tag based selection

### Steps to Reproduce

This would be fairly hard to reproduce, as it requires a server, or at least static endpoints, that satisfies the cloud backend. But with that in place, I should be able to do 
```
tofu init 
TF_WORKSPACE=terraform-demo-1 tofu plan
TF_WORKSPACE=terraform-demo-2 tofu plan
```

to run plans on 2 separate cloud workspaces, without having to change the underlying configuration

### Additional Context

I've been working on an open source application that satisfies the API endpoints required for the `cloud` backend. Most of the related operations are standard OpenTofu usage.

### References

- https://github.com/opentofu/opentofu/pull/867/files

I believe this is the code causing the error state. Ideally, this wouldn't check if the workspace name is in the list of tags, but rather fetch the workspace information from the API, and verify that the configured tags match the tags on the workspace
- https://github.com/opentofu/opentofu/blob/main/internal/cloud/backend.go#L470

### PR DESCRIPTION
**Pull request by Evi1Pumpkin**
Resolves #1787

## Target Release

1.9.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/cloud/backend.go [hunk 1]
```diff
@@ -465,13 +465,15 @@ func (b *Cloud) setConfigurationFields(obj cty.Value) tfdiags.Diagnostics {
 }
 
 func reconcileWorkspaceMappingEnvVars(w *WorkspaceMapping) tfdiags.Diagnostic {
-	// See: https://github.com/opentofu/opentofu/issues/814
-	if v := os.Getenv("TF_WORKSPACE"); v != "" && w.Name == "" {
-		if len(w.Tags) > 0 && !workspaceInTags(w.Tags, v) {
-			return invalidWorkspaceConfigMisconfigurationEnvVar
+	if v := os.Getenv("TF_WORKSPACE"); v != "" {
+		if w.Name != "" && w.Name != v {
```
Comment (Evi1Pumpkin) [inline internal/cloud/backend.go:469]: Found this missing case while running tests - if the user used `TF_WORKSPACE` and has `workspaces: { name = xx }` in config, to maintain compatibility, we need to validate that they have the same value or send an error.

**Review by cam72cam — APPROVED** [review]

**Review by ollevche — APPROVED** [review]
