### PR TITLE
Fix global schema caching

### LINKED ISSUE #944: The execution of tofu plan and tofu apply becomes stuck
### OpenTofu Version

```shell
OpenTofu v1.6.0-beta1
on linux_amd64
```

### OpenTofu Configuration Files

https://github.com/hashicorp/learn-terraform-provision-eks-cluster

### Debug Output

[plan.txt](https://github.com/opentofu/opentofu/files/13508290/plan.txt)

### Expected Behavior

[expected-results.txt](https://github.com/opentofu/opentofu/files/13508332/expected-results.txt)

### Actual Behavior

After execute `tofu plan` or `tofu apply`, it's getting stuck for a long time and don't return anything

### Steps to Reproduce

Follow the same instructions described in: https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks

1. `aws configure` then fill the required fields
2. comment out the cloud block in the `terraform.tf` file 
3. `tofu init`
4. **OPTIONAL:** `export TF_LOG=trace` 
5. `tofu plan` or `tofu apply`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by kislerdm**
Resolves #944, #929, #930 

## Target Release

1.6.0

## What changed

- Revert the global cache setting condition introduced in #719 
- `GetProviderSchema`: add the condition to validate if schema is required to be read after provider's instantiation

## Why do we need it

- To fix global caching flow

### CODE REVIEW

File: internal/providers/provider.go [hunk 1]
```diff
@@ -123,6 +123,8 @@ type ServerCapabilities struct {
 	// provider does not require calling GetProviderSchema to operate
 	// normally, and the caller can used a cached copy of the provider's
 	// schema.
+	// In other words, the providers for which GetProviderSchemaOptional is false
+	// require their schema to be read after EVERY initialisation to function normally.
```
Comment (cube2222) [inline internal/providers/provider.go:127]: initialisation => instantiation
