### PR TITLE
Bump our hcl fork to include fix for Provider defined functions in parentheses

### LINKED ISSUE #3401: Missing provider functions in the namespace when calling functions within brackets
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
OpenTofu v1.10.6
on linux_amd64
+ provider registry.opentofu.org/hashicorp/google v7.7.0
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
    }
  }
}

resource "google_pubsub_topic" "default" {
  project = "my-project"
  name    = "my-topic"
}

# Value is "my-project"
output "project_from_id" {
  value = (provider::google::project_from_id(google_pubsub_topic.default.id))
}
```

### Debug Output

intentionally left blank

### Expected Behavior

No errors on `terraform plan`

### Actual Behavior

```
│ Error: Call to unknown function
│ 
│   on main.tf line 16, in output "project_from_id":
│   16:   value = (provider::google::project_from_id(google_pubsub_topic.default.id))
│ 
│ There are no functions in namespace "provider::google::".
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### Additional Context

Removing the brackes around the value:
```hcl
value = provider::google::project_from_id(google_pubsub_topic.default.id)
```

Fixes this issue. But in more complex expressions, brackets are used to get better code readability and formatting. In such cases, it is not possible to use provider function with ToFu.

### References

- not sure if relevant - #3236

### PR DESCRIPTION
**Pull request by Yantrio**
Resolves #3401 

This brings in the commit from the PR here: https://github.com/opentofu/hcl/pull/2

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

**Comment by Yantrio** [comment]
> Maybe a unit test to prove that it works well?

Unit tests for the references code (quite low level) have been added. This isn't so much to exhaustively test the functionality but to ensure that we don't have a regression in the future.

**Review by apparentlymart — APPROVED** [review]

File: internal/lang/references_test.go [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+			// Extract provider function references
+			var gotFuncRefs []string
+			for _, ref := range refs {
+				if provFunc, ok := ref.Subject.(addrs.ProviderFunction); ok {
+					gotFuncRefs = append(gotFuncRefs, provFunc.String())
+				}
+			}
+
+			if diff := cmp.Diff(test.wantFuncRefs, gotFuncRefs); diff != "" {
+				t.Errorf("Wrong provider function references (-want +got):\n%s", diff)
```
Comment (yottta) [inline internal/lang/references_test.go:98]: `(-want +got)` 
Great pattern! Consider it stolen 😅

**Review by yottta — APPROVED** [review]
LGTM. Thanks for adding this test.

File: internal/lang/references_test.go (hunk 1 above)
Comment (Yantrio) [reply internal/lang/references_test.go:98]: I added this because I've seen other projects use it, and this syntax drives me crazy all the time. I always forget which is which, and have to google it.  I actually meant to remove this before committing, but it can stay :D
