### PR TITLE
Import block validation

### LINKED ISSUE #2416: `tofu validate` doesn't validate import blocks
### OpenTofu Version

```shell
1.9.0
```

### OpenTofu Configuration Files

```hcl
resource "null_resource" "undef-local" {
}

resource "null_resource" "undef-var" {
}

import {
  to = null_resource.undef-local
  id = local.something_not_defined
}

import {
  to = null_resource.undef-var
  id = var.some_other_undefined_thing
}
```

### Debug Output

..

### Expected Behavior

tofu validate should fail, as there are undeclared variables and locals in the import block

### Actual Behavior

tofu validate does not fail
`Success! The configuration is valid.`

### Steps to Reproduce

1. `tofu init`
2. `tofu validate`

### Additional Context

_No response_

### References

Terraform Issue where the bug was originally documented: https://github.com/hashicorp/terraform/issues/35516

### PR DESCRIPTION
**Pull request by Gogotchuri**
Adds validation for import block IDs.
This implementation doesn't add validation for addresses, as the code generation option ('-generate-config-out') may be used during the plan, which could create non-existent or invalid resources during the plan phase. Hence, validating addresses may result in false positives.

Resolves #2416 

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/tofu/eval_import.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ func evaluateImportIdExpression(expr hcl.Expression, evalCtx EvalContext, keyDat
 		return "", diags.Append(&hcl.Diagnostic{
 			Severity: hcl.DiagError,
 			Summary:  "Invalid import id argument",
-			Detail:   `The import block "id" argument depends on resource attributes that cannot be determined until apply, so OpenTofu cannot plan to import this resource.`, // FIXME and what should I do about that?
+			Detail:   `The import block "id" argument includes an undefined variable or depends on resource attributes that cannot be determined until apply, so OpenTofu cannot plan to import this resource.`, // FIXME and what should I do about that?
```
Comment (apparentlymart) [inline internal/tofu/eval_import.go]: I would expect an error related to referring to something that hasn't been declared to have already been returned in the `evalDiags` value returned from `evaluateExprWithRepetitionData`, and that diagnostic should have more useful detail about what exactly was wrong.

Assuming that's true, could we instead add a check for whether `evalDiags.HasErrors()` immediately after `diags = diags.Append(evalDiags)` and return early if so? It seems like all of the other checks we perform afterwards are relevant only if the expression was evaluable, and so continuing to make these checks even when expression evaluation failed is likely to generate redundant confusing errors rather than adding additional useful information, and dealing with unknown values here only when the expression was otherwise valid means that we can keep this error message focused only on that one case rather than giving the reader two different possibilities to check. :thinking:

Comment (Gogotchuri) [reply internal/tofu/eval_import.go]: Thanks for the catch. I had the same idea, but somehow forgot to add that check.
It's been added in https://github.com/opentofu/opentofu/pull/2973/commits/7a9bf09c5424330f4bb3e7b6ca99a4ae8769d2cd

File: internal/tofu/context_import.go [hunk 2]
```diff
@@ -108,6 +108,54 @@ func NewImportResolver() *ImportResolver {
...
+		forEachVal, evalDiags := evaluateForEachExpressionValue(ctx, importTarget.Config.ForEach, rootCtx, unknownsNotAllowed, tupleAllowed, nil)
+		diags = diags.Append(evalDiags)
+		if diags.HasErrors() {
+			return diags
+		}
+
+		// We are building an instances.RepetitionData based on each for_each key and val combination
+		var repetitions []instances.RepetitionData
+
+		it := forEachVal.ElementIterator()
```
Comment (cam72cam) [inline internal/tofu/context_import.go:137]: How does this work with for_each when keys are known, but values are unknown?

We also stub repetition data in NodeValidatableResource.stubRepititionData. It seems like we need to be careful with unknown handling in here.

Comment (Gogotchuri) [reply internal/tofu/context_import.go:137]: I'll look into it. Also, I'll try to add a test case that covers it first.

Comment (Gogotchuri) [reply internal/tofu/context_import.go:137]: Finally, I was able to get back to this PR. I think your concerns are covered in [`evaluateImportIdExpression`](https://github.com/opentofu/opentofu/blob/86c229f28e32afcab84e13eb7540c39e2341df0e/internal/tofu/eval_import.go#L51). It takes repetition data, keys, and values and does evaluation/validation. After a bit of exploration of imports, to the best of my understanding, those checks should be enough.
Can you take a look at that? Are additional/earlier checks required for the use cases you have mentioned? @cam72cam

Comment (Gogotchuri) [reply internal/tofu/context_import.go:137]: Ah, validation against unknown values may be wrong for OpenTofu and needs modification based on our documentation at https://opentofu.org/docs/language/import/#importing-multiple-resources
Was that your concern that we would flag those cases invalid?

Comment (cam72cam) [reply internal/tofu/context_import.go:137]: Ok, that makes sense.  We do little validation here, but rely on evaluateImportIdExpression for the specific check.

**Review by cam72cam — APPROVED** [review]
