### PR TITLE
statemgr: Do not read the state file before acquiring a lock

### LINKED ISSUE #3239: Filesystem Lock is broken on Windows
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

While working on fixing the statelocker tests on Windows, I noticed a silly bug on `TestApply_lockedStateWait`.

This test can be summarized in three parts:

1. We lock the state file, which triggers the statelocker binary to lock the file;

https://github.com/opentofu/opentofu/blob/45e379b4be8ed937352b872387f898f83320ee45/internal/command/apply_test.go#L262-L273

2. We start to run the apply, with a locked state file and a timeout of 4s:

https://github.com/opentofu/opentofu/blob/45e379b4be8ed937352b872387f898f83320ee45/internal/command/apply_test.go#L281-L298

3.  We call `unlock` after 500ms, while apply is running

https://github.com/opentofu/opentofu/blob/45e379b4be8ed937352b872387f898f83320ee45/internal/command/apply_test.go#L276-L279

Tofu actually fails to wait for the lock. This occurs due to the Windows implementation of locks, known as mandatory locking. We don't see this error on the other systems since they implement advisory locking. Looking at our code and at a debug session, we can understand the fundamental differences between the implementations:

Lock is implemented at stateMgr.Lock:

https://github.com/opentofu/opentofu/blob/45e379b4be8ed937352b872387f898f83320ee45/internal/states/statemgr/filesystem.go#L359-L361

The trick issue is that before trying to acquire the lock, we actually call `createStateFiles`, reading the state file and creating a state backup at:

https://github.com/opentofu/opentofu/blob/45e379b4be8ed937352b872387f898f83320ee45/internal/states/statemgr/filesystem.go#L522-L540

This works fine in Linux, as advisory locking allows another process to open and write to the file if it hasn't chosen to participate in the locking session yet. In Windows, this is not allowed, since the mandatory lock is already in place and the file can't be read to be backed up. 

The lock is only in place on Linux later in the code, while trying to acquire the lock at:

https://github.com/opentofu/opentofu/blob/45e379b4be8ed937352b872387f898f83320ee45/internal/states/statemgr/filesystem.go#L374-L385

Flock will return: `resource temporarily unavailable`, ensuring we can't access the file since the lock is in place. Windows won't get to that part since it can't write to the backup file, returning early.

### OpenTofu Version

```shell
testing on `dev` and 1.9.1
```

### OpenTofu Configuration Files

Shouldn't be relevant

### Debug Output

-

### Expected Behavior

It should be possible to get the Lock after waiting for the lock to be released by the other `statelocker` process.

### Actual Behavior

Tofu actually fails to wait for the lock.

### Steps to Reproduce

`go test ./internal/command -run TestApply_lockedStateWait` on Windows

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by diofeher**
Blocked by https://github.com/opentofu/opentofu/pull/3206
Resolves #3239

This PR waits to write a backup file on file systems where we haven't yet acquired a lock. 
This PR splits the `createStateFiles` function and only writes to the backup file after the lock is acquired.

It fixes `TestApply_lockedStateWait` on Windows.

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/states/statemgr/filesystem.go [hunk 1]
```diff
@@ -500,9 +507,13 @@ func (s *Filesystem) createStateFiles() error {
 	}
 
 	s.stateFileOut = f
+	return nil
+}
 
+func (s *Filesystem) writeBackupFile() error {
```
Comment (apparentlymart) [inline internal/states/statemgr/filesystem.go]: I think I broadly understand why this change fixed the test -- it means that the `Lock` method can acquire a lock on the file before we try to read anything from it, which is important on Windows because it uses mandatory rather than advisory locks.

However, it took me a while to understand this change because I was initially confused by the name of this function. I assume that by "write backup file" you meant to write to _the `s.backupFile` field_, but unfortunately the naming is ambiguous because "backup file" could also refer to the the on disk that [this `s.backupFile` object is eventually saved into](https://github.com/opentofu/opentofu/blob/b203bc0dd7d09a8c549aa6081729531a3b54d100/internal/states/statemgr/filesystem.go#L202-L207) (whose path is in `s.backupPath`), so I expected that this function would actually write to that file on disk.

What do you think about calling this `prepareBackupFile` instead? For me, that means "make preparations to write the backup file later" rather than "write the backup file _now_".

Comment (diofeher) [reply internal/states/statemgr/filesystem.go]: I agree with you. I actually got confused when I was reading the function and assumed it was writing to the file... But now that I'm re-reading, I'm seeing why I considered that.

Addressed on https://github.com/opentofu/opentofu/pull/3240/commits/4e27d75804698ef59dbf82938b3dbc5de34ebfea
