### PR TITLE
fix config generation with optional empty sensitive string

### LINKED ISSUE #1984: OpenTofu Crash during tofu plan Command with AWS Elasticache Import
### OpenTofu Version

```shell
OpenTofu v1.8.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

```
stg % tofu plan -generate-config-out=generated_resources.tf
aws_elasticache_replication_group.XXX_redis: Preparing import... [id=XXX-redis]
aws_elasticache_replication_group.XXX_redis: Refreshing state... [id=XXX-redis]

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 121 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x1c
github.com/opentofu/opentofu/internal/logging.panicHandler({0x105858440, 0x105e7a190}, {0x14001940800, 0x365, 0x400})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xcc
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.PanicHandlerWithTraceFn.func2()
        github.com/opentofu/opentofu/internal/logging/panic.go:82 +0x8c
panic({0x105858440?, 0x105e7a190?})
        runtime/panic.go:920 +0x26c
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        github.com/zclconf/go-cty@v1.14.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.AsString({{{0x105eb8e18?, 0x1400000f031?}}, {0x105b038e0?, 0x14003780fc0?}})
        github.com/zclconf/go-cty@v1.14.4/cty/value_ops.go:1385 +0x54
github.com/opentofu/opentofu/internal/genconfig.writeConfigAttributesFromExisting({{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, {0x1400056e720, 0x21}, {0x1400080ac50, ...}}, ...}}, ...)
        github.com/opentofu/opentofu/internal/genconfig/generate_config.go:158 +0x5a8
github.com/opentofu/opentofu/internal/genconfig.GenerateResourceContents({{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, {0x1400056e720, 0x21}, {0x1400080ac50, ...}}, ...}}, ...)
        github.com/opentofu/opentofu/internal/genconfig/generate_config.go:48 +0x510
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).generateHCLStringAttributes(0x1400192b4a0, {{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, {0x1400056e720, 0x21}, ...}, ...}}, ...)
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:682 +0x154
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).importState(0x1400192b4a0, {0x105ed3ca0, 0x140017cc500}, {{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, ...}, ...}}, ...)
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:607 +0x1090
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).managedResourceExecute(0x1400192b4a0, {0x105ed3ca0, 0x140017cc500})
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:203 +0x590
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).Execute(0x12d1fcc68?, {0x105ed3ca0?, 0x140017cc500?}, 0x80?)
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:92 +0x7c
github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0x140077a7c20, {0x105ed3ca0, 0x140017cc500}, {0x156f20e38, 0x1400192b4a0})
        github.com/opentofu/opentofu/internal/tofu/graph_walk_context.go:147 +0xa0
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x105e34460, 0x1400192b4a0})
        github.com/opentofu/opentofu/internal/tofu/graph.go:86 +0x27c
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x14000a4a840, {0x105e34460, 0x1400192b4a0}, 0x14001905600)
        github.com/opentofu/opentofu/internal/dag/walk.go:385 +0x2a8
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 271
        github.com/opentofu/opentofu/internal/dag/walk.go:308 +0xb0c
With go-routine called from:
goroutine 271 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
        github.com/opentofu/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk(0x14001aa6240, {0x105eb9788, 0x140077a7c20})
        github.com/opentofu/opentofu/internal/tofu/graph.go:51 +0x40
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x105dce120, 0x14001b6c460})
        github.com/opentofu/opentofu/internal/tofu/graph.go:127 +0x5f8
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x14000926ba0, {0x105dce120, 0x14001b6c460}, 0x14001ebda40)
        github.com/opentofu/opentofu/internal/dag/walk.go:385 +0x2a8
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 209
        github.com/opentofu/opentofu/internal/dag/walk.go:308 +0xb0c
```

### Expected Behavior

The tofu plan command should execute successfully without crashing.

### Actual Behavior

OpenTofu crashes and outputs a stack trace.

### Steps to Reproduce

1. Set up an import configuration in import.tf:
```
import {
  to = aws_elasticache_replication_group.XXX_redis
  id = "XXX-redis"
}
```
2. Execute the command:
```
tofu plan -generate-config-out=generated_resources.tf
```
3. Witnessed a crash with the following error message.

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ollevche**
Resolves #1984

This PR fixes configuration generation on import when an empty string value is marked as sensitive.

## Target Release

1.9.0

## Checklist

- [X] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [X] I have not used an AI coding assistant to create this PR.
- [X] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [X] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [X] I have run golangci-lint on my change and receive no errors relevant to my code.
- [X] I have run existing tests to ensure my code doesn't break anything.
- [X] I have added tests for all relevant use cases of my code, and those tests are passing.
- [X] I have only exported functions, variables and structs that should be used from other packages.
- [X] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/genconfig/generate_config.go [hunk 1]
```diff
@@ -152,16 +152,17 @@ func writeConfigAttributesFromExisting(addr addrs.AbsResourceInstance, buf *stri
...
-					val = attrS.EmptyValue()
-				}
-			}
 			if attrS.Sensitive || val.IsMarked() {
 				buf.WriteString("null # sensitive")
 			} else {
+				if val.Type() == cty.String {
+					// SHAMELESS HACK: If we have "" for an optional value, assume
+					// it is actually null, due to the legacy SDK.
+					if !val.IsNull() && attrS.Optional && len(val.AsString()) == 0 {
```
Comment (ollevche) [inline internal/genconfig/generate_config.go:161]: AsString() panic if value is marked so we need to call it only after the sensitivity check.

**Review by Evi1Pumpkin — APPROVED** [review]
LGTM!

**Review by cam72cam — APPROVED** [review]
