### PR TITLE
fix: provider not initialized in some cases (mostly, deposed)

### LINKED ISSUE #2334: Dynamic Provider issue: provider not initialized
### OpenTofu Version

```shell
OpenTofu v1.9.0-dev
on linux_amd64
+ provider registry.opentofu.org/hashicorp/aws v5.82.2
```

### OpenTofu Configuration Files

```hcl

provider "aws" {
  for_each = var.provider_regions
  alias    = "secondary_regions"
  region   = each.value.region
}

module "secondary_region" {
  source   = "./modules/secondary-region"

  for_each = var.secondary_regions

  providers = {
    aws          = aws.secondary_regions[each.key]
    aws.aws_main = aws.aws_main
  }
...
}
```

### Debug Output

Available on demand (sensitive)

### Expected Behavior

Should work

### Actual Behavior

Displays the plan properly, and then displays an error:

```
[...]
module.secondary_region["Ireland"].module.lb-service.aws_lambda_permission.api_gateway: Refreshing state... [id=AllowAPIGatewayInvoke]
module.secondary_region["Ireland"].module.lb-service.aws_api_gateway_stage.lb_service: Refreshing state... [id=ags-xxxx-prod]
module.secondary_region["Ireland"].module.lb-service.aws_api_gateway_base_path_mapping.lb: Refreshing state... [id=hlb.eu-west-1.xxxx.xxxx.cloud/]

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu planned the following actions, but then encountered a problem:

  # module.secondary_region["Ireland"].module.customer-lb-provisioner.aws_lambda_function.customer_lb_provisioner will be updated in-place
  ~ resource "aws_lambda_function" "customer_lb_provisioner" {
        id                             = "customer-lb-provisioner"
      ~ image_uri                      = "xxxx.dkr.ecr.eu-west-1.amazonaws.com/hlb-customer-lb-provisioner:da66e2bf0efdacc2eb4c34f93fab0ea58be61dd0" -> "xxxx.dkr.ecr.eu-west-1.amazonaws.com/hlb-customer-lb-provisioner:da66e2bf0efdacc2eb4c34f93fab0ea58be61dd1"
      ~ last_modified                  = "2025-01-06T09:16:51.000+0000" -> (known after apply)
        tags                           = {}
        # (18 unchanged attributes hidden)

        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Error: provider provider["registry.opentofu.org/hashicorp/aws"].secondary_regions not initialized
│ 
│ 
╵
```

But the weirdest thing is that limiting the action to one module works fine:
```
$ tofu apply -var-file=test.tfvars -target='module.secondary_region["Ireland"].module.customer-lb-provisioner.aws_lambda_function.customer_lb_provisioner'
[...]
module.secondary_region["Ireland"].module.alb.aws_route53_record.control_plane: Refreshing state... [id=Z02xxx_control-plane.eu-west-1.xxx.xxx.cloud_A]
module.secondary_region["Ireland"].module.elasticache.aws_elasticache_replication_group.token_cache: Refreshing state... [id=token-cache]
module.secondary_region["Ireland"].module.customer-lb-provisioner.aws_lambda_function.customer_lb_provisioner: Refreshing state... [id=customer-lb-provisioner]

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu will perform the following actions:

  # module.secondary_region["Ireland"].module.customer-lb-provisioner.aws_lambda_function.customer_lb_provisioner will be updated in-place
  ~ resource "aws_lambda_function" "customer_lb_provisioner" {
        id                             = "customer-lb-provisioner"
      ~ image_uri                      = "xxxx.dkr.ecr.eu-west-1.amazonaws.com/hlb-customer-lb-provisioner:da66e2bf0efdacc2eb4c34f93fab0ea58be61dd0" -> "xxxx.dkr.ecr.eu-west-1.amazonaws.com/hlb-customer-lb-provisioner:da66e2bf0efdacc2eb4c34f93fab0ea58be61dd1"
      ~ last_modified                  = "2025-01-06T09:16:51.000+0000" -> (known after apply)
        tags                           = {}
        # (18 unchanged attributes hidden)

        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with either the -target option or the -exclude option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target and -exclude options are not for routine use, and are provided only for exceptional situations such as recovering from errors or mistakes, or when OpenTofu specifically suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:```

### Steps to Reproduce

tofu apply -var-file=test.tfvars

```hcl
environment        = "test"
master_region      = "eu-central-1"
master_vpc_cidr    = "10.xxx.0.0/16" 
customer_role_name = "xxx/service-role"
provider_regions  = {
  Ireland = { 
    region = "eu-west-1"
  }
  Milan = { 
    region = "eu-south-1"
  }
}
secondary_regions  = {
  Ireland = { 
    region = "eu-west-1"
    vpc_cidr = "10.xxx.0.0/16"
  }
}
```

### Additional Context

using opentofu 1.9.0-rc2

### References

_No response_

### PR DESCRIPTION
**Pull request by ollevche**
Resolves #2334

This PR resolves the issue described in #2334 and a few more cases, where a provider is not resolved before its usage. Also, we improve error messages for cases, when provider configuration is changed (its instances, or the presence of for_each).

Must be backported to v1.9

## Target Release

1.9.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

File: internal/tofu/node_resource_abstract_instance.go [hunk 1]
```diff
@@ -204,19 +204,75 @@ func (n *NodeAbstractResourceInstance) resolveProvider(ctx EvalContext, hasExpan
...
+			// We're associated with the no-key instance of a provider configuration, which
+			// suggests that someone is in the process of adopting provider for_each for
+			// a provider configuration that didn't previously use it but has some
+			// orphaned resource instance objects in the state that need to have
+			// their destroy completed first.
+			diags = diags.Append(tfdiags.Sourceless(
+				tfdiags.Error,
+				"Provider instance not present",
+				fmt.Sprintf(
+					"To work with %s its original provider instance at %s is required, but it has been removed. This suggests that you've added for_each to this provider configuration while there are existing instances of %s that need to be destroyed by the original single-instance provider configuration.\n\nTo proceed, return to your previous single-instance configuration for %s and ensure that %s has been destroyed or forgotten before using for_each with this provider, or change the resource configuration to still declare an instance with the key %s.",
```
Comment (cam72cam) [inline internal/tofu/node_resource_abstract_instance.go:235]: I wonder if the recommendation here is to update this resource to support for_each, instead of suggesting deleting it.

Comment (ollevche) [reply internal/tofu/node_resource_abstract_instance.go:235]: I think the suggestion is correct: user needs to either destroy / forget the resource via previous version of provider configuration or get the resource configuration back (with a proper link to provider configuration).

This is possible when a resource is no longer present in the configuration and needs to be removed via provider which is also removed from configuration.

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,7 +13,8 @@ ENHANCEMENTS:
 * OpenTofu will now recommend using `-exclude` instead of `-target`, when possible, in the error messages about unknown values in `count` and `for_each` arguments, thereby providing a more definitive workaround. ([#2154](https://github.com/opentofu/opentofu/pull/2154))
 
 BUG FIXES:
-* `tofu init` command does not attempt to read encryption keys when `-backend=false` flag is set. (https://github.com/opentofu/opentofu/pull/2293)
+* `tofu init` command does not attempt to read encryption keys when `-backend=false` flag is set. ([#2293](https://github.com/opentofu/opentofu/pull/2293))
+* Provider iteration no longer fails on plan / apply, when dealing with deposed and forgotten resources. Also, some error messages for provider configuration changes are more understandable. ([#2334](https://github.com/opentofu/opentofu/pull/2334))
```
[the remark this answers is not in the document]
Comment (ollevche) [reply CHANGELOG.md]: Absolutely makes sense. I removed the entry for this fix and also a few more for other bug fixes from v1.9

**Review by cam72cam — APPROVED** [review]
