### PR TITLE
Improve encryption internals and fix a few bugs therein

### LINKED ISSUE #1604: encrypted remote state validates unused key providers
### OpenTofu Version

```shell
OpenTofu v1.7.0
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.43.0
+ provider registry.opentofu.org/hashicorp/local v2.5.1
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" { ... }

  encryption {

    method "unencrypted" "plaintext" {}
    key_provider "aws_kms" "aes_256" {
      kms_key_id = "mrk-1"
      region     = "us-east-1"
      key_spec   = "AES_256"
    }
    method "aes_gcm" "kms_aes_256" {
      keys = key_provider.aws_kms.aes_256
    }
    state {
      method = method.aes_gcm.kms_aes_256
      fallback {
        method = method.unencrypted.plaintext
      }
    }

    key_provider "aws_kms" "remote_r" {
      kms_key_id = "mrk-2"
      region     = "us-east-1"
      key_spec   = "AES_256"
    }
    method "aes_gcm" "remote_r" {
      keys = key_provider.aws_kms.remote_r
    }

    remote_state_data_sources {
      remote_state_data_source "r" {
        method = method.aes_gcm.remote_r
        fallback {
          method = method.unencrypted.plaintext
        }
      }
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.43.0"
    }
  }

}

data "terraform_remote_state" "r" {
  backend = "s3"
  config = {
    region         = "us-east-1"
    bucket         = "bucket-r"
    key            = "global/s3/terraform.tfstate"
    dynamodb_table = "table-r"
    encrypt        = true
  }
}

```

### Debug Output

private

### Expected Behavior

I would expect to be able to read from the remote state.

### Actual Behavior

```
Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: Unable to fetch encryption key data
│
│ key_provider.aws_kms.aes_256 failed with error: : operation error KMS: Decrypt, https response error StatusCode: 400, RequestID: sdfsdfsdf, IncorrectKeyException: The key ID in the
│ request does not identify a CMK that can perform this operation.
╵
╷
│ Error: data.terraform_remote_state.production: Unable to read remote state
│
```

### Steps to Reproduce

1. tofu apply

### Additional Context

I am unable to read from an encrypted remote state. From the error description, it looks like tofu is using the wrong key provider.

Looking at the log, you can notice its refering to `key_provider.aws_kms.aes_256`, but this isn't even the key provided related to my remote! It should be `key_provider.aws_kms.remote_r`.

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
The encryption package went through a wild ride of design decisions when it was original built.  This PR takes a more idiomatic approach to processing the configured targets, methods, and key_providers to fix a few bugs.  It also makes the individual components easier to test, as well as work on.

Resolves #1604 by only loading the methods and key_providers required in a particular target, and in isolation.  Previously, all methods and key_providers were fully configured and initialized, regardless of the operation and target specified.  This led to some interesting bugs, particularly when it came to conflicting key_provider names between projects used together with `terraform_remote_data`.  Key providers which were not referenced would still be initialized and attempt to understand metadata that didn't actually belong to them.  Thankfully, the only result of the bug was a failure to decrypt data from a sub-project.

It also fixes an issue with chained key_providers, where it would only work if the key_providers were declared in the right order in the configuration.

Finally, with the new structures in place, it was trivial to add support for static variables/locals in methods.  This is tested with the aad field in aesgcm.

## Target Release

1.10.0

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [ ] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

File: internal/encryption/targets.go [hunk 1]
```diff
@@ -9,121 +9,75 @@ import (
...
-	diags = append(diags, targetDiags...)
-
-	if base.enforced {
-		for _, m := range methods {
-			if unencrypted.Is(m) {
-				return nil, append(diags, &hcl.Diagnostic{
+	var methods []config.MethodConfig
+
+	for target != nil {
+		traversal, travDiags := hcl.RelTraversalForExpr(target.Method)
```
Comment (yottta) [inline internal/encryption/targets.go:21]: `question`
What is the reason of using `RelTraversalForExpr` and not `AbsTraversalForExpr`? 🤔

File: internal/encryption/targets_test.go [hunk 2]
```diff
@@ -52,7 +52,7 @@ func TestBaseEncryption_buildTargetMethods(t *testing.T) {
 					method = method.aes_gcm.example
 				}
 			`,
-			wantErr: `Test Config Source:3,25-32: Unsupported attribute; This object does not have an attribute named "static".`,
+			wantErr: `Test Config Source:3,13-38: Undefined Key Provider; Key provider static.basic is missing from the encryption configuration.`,
```
Comment (yottta) [inline internal/encryption/targets_test.go:55]: `suggestion`
It would be great to have the test `TestBaseEncryption_buildTargetMethods` renamed as well.

File: internal/encryption/targets_test.go [hunk 3]
```diff
@@ -175,6 +175,62 @@ func TestBaseEncryption_buildTargetMethods(t *testing.T) {
 			`,
 			wantErr: "Test Config Source:3,12-34: Invalid Key Provider expression format; Expected key_provider.<type>.<name>",
 		},
+		"unused-key-provider": {
```
Comment (yottta) [inline internal/encryption/targets_test.go:178]: `suggestion`
Could we add a unit test similar to [this one](https://github.com/opentofu/opentofu/pull/2547/files#diff-89663d138a7de3a7669ab0efd13ac851af80d5f7a6a4179b6e8e250682f5ee1bR209)?

Comment (cam72cam) [reply internal/encryption/targets_test.go:179]: I've cherry picked in the tests from that commit, with your authorship :+1:

File: internal/encryption/targets.go (hunk 1 above)
Comment (cam72cam) [reply internal/encryption/targets.go:21]: I don't have a good reason, I used an example from another area in the code.  The only practical difference is that I don't have to check different casts for different elements.

Under the hood, Rel calls Abs and modifies the result.

File: internal/encryption/keyprovider.go [hunk 4]
```diff
@@ -10,61 +10,132 @@ import (
...
+
+		depType := depTypeAttr.Name
+		depName := depNameAttr.Name
+
+		kpc, ok := cfg.GetKeyProvider(depType, depName)
+		if !ok {
+			diags = diags.Append(&hcl.Diagnostic{
+				Severity: hcl.DiagError,
+				Summary:  "Undefined Key Provider",
+				Detail:   fmt.Sprintf("Key provider %s.%s is missing from the encryption configuration.", depType, depName),
```
Comment (apparentlymart) [inline internal/encryption/keyprovider.go:99]:
```suggestion
				Summary:  "Reference to undeclared key provider",
				Detail:   fmt.Sprintf("There is no key_provider %q %q block declared in the encryption block.", depType, depName),
```

To make this more consistent with [the similar message for resource references](https://github.com/opentofu/opentofu/blob/35368d990955f225d0fd72ba6409563c992733e1/internal/tofu/evaluate.go#L658-L664).

File: internal/encryption/keyprovider.go [hunk 5]
```diff
@@ -73,15 +144,12 @@ func (e *targetBuilder) setupKeyProvider(cfg config.KeyProviderConfig, stack []c
...
-					// TODO add the stack trace to the detail message
-					Detail: fmt.Sprintf("Can not load %q due to circular reference", addr),
-				},
-			)
-			return diags
+			return diags.Append(&hcl.Diagnostic{
+				Severity: hcl.DiagError,
+				Summary:  "Circular reference detected",
+				// TODO add the stack trace to the detail message
+				Detail: fmt.Sprintf("Can not load %q due to circular reference", addr),
```
Comment (apparentlymart) [inline internal/encryption/keyprovider.go:151]:
```suggestion
				Detail: fmt.Sprintf("Cannot load %s due to circular reference between key providers.", addr),
```

Along with being a little more specific about what is relevant to this circular reference and adding the period to the end to make it a full sentence, I also changed `%q` to `%s` because it seems like `keyprovider.Addr` represents a reference address like `key_provider.foo.bar` and we don't typically quote those in error messages once we've confirmed that they refer to something valid.

(There are some other "can not" vs. "cannot" typos elsewhere in this function too, FWIW.)

File: internal/encryption/keyprovider.go [hunk 6]
```diff
@@ -120,79 +188,32 @@ func (e *targetBuilder) setupKeyProvider(cfg config.KeyProviderConfig, stack []c
 
 	// Locate all the dependencies
 	deps, varDiags := gohcl.VariablesInBody(cfg.Body, keyProviderConfig)
-	diags = append(diags, varDiags...)
+	diags = diags.Extend(varDiags)
```
Comment (apparentlymart) [inline internal/encryption/keyprovider.go:191]: FWIW this `Extend` method is exactly equivalent to the `append` you replaced. I don't have a strong opinion about which way to write it so this is just FYI, but other parts of the system do tend to just use `append` directly. :man_shrugging:

File: internal/encryption/method/unencrypted/method.go [hunk 7]
```diff
@@ -19,12 +20,12 @@ func (f *descriptor) ID() method.ID {
 	return "unencrypted"
 }
 func (f *descriptor) ConfigStruct() method.Config {
-	return new(config)
+	return new(mconfig)
 }
 
-type config struct{}
+type mconfig struct{}
```
Comment (apparentlymart) [inline internal/encryption/method/unencrypted/method.go:26]: Is this intended to be short for `methodConfig`? Could we just call it `methodConfig`, if so? or... `methodConfigBuilder`, since it seems to have a `Build` method. :thinking:

File: internal/encryption/targets.go (hunk 1 above)
Comment (apparentlymart) [reply internal/encryption/targets.go:21]: The distinction between relative and absolute traversals is mainly there for the difference in how they appear when parsed directly from source code: in `foo.bar[somethingElse].baz` `foo.bar` is an absolute traversal, while `.baz` is a relative traversal.

When we interpret an _already-parsed_ expression as a traversal using these `AbsTraversalForExpr`/`RelTraversalForExpr` functions the native syntax and JSON syntax implementations both only work directly against an absolute traversal anyway and so the distinction is pretty weak and more about representing intent for how the result is going to be used. For example, elsewhere in the language we use `AbsTraversalForExpr` to deal with `depends_on` but `RelTraversalForExpr` to deal with `ignore_changes`, because the former is representing a reference to something in the global scope while the latter is representing a reference to something relative to the resource instance object.

Given that I think `AbsTraversalForExpr` would better represent what this result is intended to mean, but you are right that it makes no technical difference whatsoever with the two HCL syntax implementations we have in today's OpenTofu. A future implementation of `hcl.Expression` for another syntax might choose to interpret these differently, and so being consistent might help with hypothetical adoption of a new syntax in the future but that seems pretty unlikely in the near future. :man_shrugging:

File: internal/encryption/targets.go [hunk 8]
```diff
@@ -9,121 +9,75 @@ import (
...
-		fallback, fallbackDiags := e.build(target.Fallback, targetName+".fallback")
-		diags = append(diags, fallbackDiags...)
-		methods = append(methods, fallback...)
+	if enforced {
+		for _, m := range methods {
+			if unencrypted.IsConfig(m) {
+				return nil, append(diags, &hcl.Diagnostic{
+					Severity: hcl.DiagError,
+					Summary:  "Unencrypted method is forbidden",
+					Detail:   "Unable to use `unencrypted` method since the `enforced` flag is used.",
```
Comment (apparentlymart) [inline internal/encryption/targets.go:77]: OpenTofu error messages don't typically use backticks like this. I would suggest either leaving them unquoted or using normal double quotes for consistency. I might also say that the enforced flag is _true_, rather than just that it is _used_, to be clearer what exactly we're talking about.

**Review by apparentlymart — APPROVED** [review]
Overall this makes sense to me, based on my quick studying of this subsystem so I could understand it better. :grinning: 

My inline comments are largely just nitpicking about error messages not following the prevailing style from elsewhere in the system. I tried to leave each kind of feedback on that only once, but I do note that there are multiple examples of some of these inconsistencies -- this subsystem was consistent with itself, even if not with the rest of OpenTofu -- and so if you accept any of these then probably best to also change the other similar messages in the same way. However, error messages were not the main point of this change so I leave it up to you how much to change that here vs. saving that for another day.

File: internal/encryption/keyprovider.go (hunk 6 above)
Comment (cam72cam) [reply internal/encryption/keyprovider.go:191]: I got a bit carried away, but in general I like the Extend / Append methods on hcl diags a bit more than the append syntax.

File: internal/encryption/targets_test.go (hunk 2 above)
Comment (cam72cam) [reply internal/encryption/targets_test.go:56]: Fixed in a318008b3c :+1:

File: internal/encryption/config/config_parse.go [hunk 9]
```diff
@@ -36,6 +36,10 @@ func DecodeConfig(body hcl.Body, rng hcl.Range) (*EncryptionConfig, hcl.Diagnost
 				break
 			}
 		}
+
```
[the remark this answers is not in the document]
Comment (cam72cam) [reply internal/encryption/config/config_parse.go:38]: Fixed in 1c3e8c0677

File: internal/encryption/targets.go (hunk 1 above)
Comment (cam72cam) [reply internal/encryption/targets.go]: Resolved in 2d0240d703ba13aca19a357a0752f5f7dc011f72

**Review by yottta — APPROVED** [review]

**Review by Gogotchuri — APPROVED** [review]

File: internal/encryption/keyprovider.go [hunk 10]
```diff
@@ -10,61 +10,131 @@ import (
...
+func (v valueMap) has(first string, second string) bool {
+	s, ok := v[first]
+	if !ok {
+		return false
+	}
+	_, ok = s[second]
+	return ok
+}
+
+func (v valueMap) hclEvalContext(root string) *hcl.EvalContext {
```
Comment (Yantrio) [inline internal/encryption/keyprovider.go:44]: `root` is not used here, is that intentional?

Comment (Yantrio) [reply internal/encryption/keyprovider.go:44]: ofcourse 🤦 because it's a map. That's fine 👍

**Review by Yantrio — APPROVED** [review]
