### PR TITLE
Fixes #913: Incorrect installation instructions for RPM

### LINKED ISSUE #913: install of tofu-1.6.0~alpha5-1.x86_64.rpm fails - rpm not signed
### OpenTofu Version

```shell
N/A
```

### OpenTofu Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

opentofu should have installed

### Actual Behavior

```
Package tofu-1.6.0~alpha5-1.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

### Steps to Reproduce

1. Create repo file following https://opentofu.org/docs/intro/install/rpm
2. Run `sudo dnf install tofu`

### Additional Context

_No response_

### References

_No response_

### LINKED ISSUE #916: [RFC] Adding a new Provider/Module to Registry via GitHub issues
This proposal is meant to complement the selected new [Homebrew-inspired registry](https://github.com/opentofu/opentofu/issues/741.), and as an alternative to https://github.com/opentofu/opentofu/issues/895.  

## Implementation Overview
1. Have packages submitted via GitHub [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
1. Have a GitHub action that upon matched GitHub issue creation/edit will use the submitted information to:
1. Validate the information provided
1. When valid  
    1. Create a new branch where the submitted data is captured in the the proper sharded directory structure/metadata-json
    1. Create a Pull Request for said branch [description will say closes: #issue to auto-close that issue when merged]
    1. Create Pull Request for GPG key submission
1. When invalid  
    1. Will comment back on issue mentioning author asking them to fix what isn’t valid
    1. Upon edit GitHub action will trigger once more

## Pros
- A neat, familiar and secure user interface for proposing modules/provider
- Completely automated whenever possible
- Issues provide submission visibility, allow for conversations to occur in context and on issue when manual admin/core team intervention is required
- No CLI or additional installs required to submit a provider, less maintenance on client-side issues/distribution by core team members
- No GitHub tokens or other means of CLI based authentication required
- Abstracts away any codebase implementation detail like directory sharding logic/code intricacies otherwise required when submitting new provider/module/key directly
- Visible history/timeline for submission/acceptance/deny

## Cons
- Will contribute to GitHub action cost (though probably nothing significant) 
- Since the PRs are generated, git history won't track to a _signed_ commit by submitter
- Forks may cause some loss of audit history as Issues do not transfer with forks

### Reuse the approach for when revising _existing_ packages
The approach described on the PRD is for submitting new Provider or Module, but it can also be extended to say, submitting a GPG key rotation, ask for removal or replacement of faulty version or forcefully bump a new version beyond that cron based version bump - all in the same familiar manner.  

### GitHub CLI
I have also had the notion of being able to do so from GitHub CLI by going:
```
gh issue create -R 'opentofu/registry-stable' -T provider.yml
```

and following form prompt, but it seems like [issue forms aren’t supported yet by CLI](https://github.com/cli/cli/issues/5865), but perhaps would be a good CLI approach patching into the same mechanism later once GitHub supports forms in its CLI.

### PR DESCRIPTION
**Pull request by janosdebugs**
Currently, the installation instructions for RPM-based distributions are incorrect since we are not GPG-signing the packages. This change turns off GPG verification for those packages. This is preferable to disabling the GPG check on the command line because the GPG key will likely change anyway when we enable package signing.

The change also contains a fix in the convenience script instructions for openSUSE LEAP users, offering instructions for Zypper instead of Yum.

As an additional change, this commit also includes testing scripts for the installation instructions on various distributions to avoid such errors in the future. The test script can be invoked on a Linux distribution with Docker/Podman installed using
`test-install-instructions.sh`:

```
$ ./test-install-instructions.sh
[+] Running 10/10
 ✔ Container install-rockylinux-convenience-1  Removed
 ✔ Container install-debian-convenience-1      Removed
 ✔ Container install-ubuntu-convenience-1      Removed

...

install-fedora-convenience-1 exited with code 0
Test case       Exit code
debian-convenience      0
debian-manual   0
fedora-convenience      0
fedora-manual   0
opensuse-convenience   0
opensuse-manual 0
rockylinux-convenience  0
rockylinux-manual       0
ubuntu-convenience      0
ubuntu-manual   0
All tests passed.
```

Resolves #913

## Target Release

1.6.0

### CODE REVIEW

File: website/docs/intro/install/test-deb.sh [hunk 1]
```diff
@@ -0,0 +1,3 @@
+#!/bin/bash
+
+for distro in fedora quay.io/
```
Comment (cam72cam) [inline website/docs/intro/install/test-deb.sh:3]: Is this complete/needed?

Comment (janosdebugs) [reply website/docs/intro/install/test-deb.sh:3]: No, removing it.

**Review by cam72cam — APPROVED** [review]

**Review by kislerdm — APPROVED** [review]
@janosdebugs Hey János! Thank you for taking care of such an important matter as installation instructions! 

I have a non-blocking nit/suggestion. WDYT about removing "-y" flag from the commands? Motivation, let's let users decided whether they'd prefer to auto-approval. For context, docker [instructions](https://docs.docker.com/desktop/install/fedora/) don't use "-y" flag.

**Comment by janosdebugs** [comment]
> I have a non-blocking nit/suggestion. WDYT about removing "-y" flag from the commands? Motivation, let's let users decided whether they'd prefer to auto-approval. For context, docker [instructions](https://docs.docker.com/desktop/install/fedora/) don't use "-y" flag.

This would mean we can't test the instructions in an automated fashion.

**Comment by janosdebugs** [comment]
I visually checked the new instructions, looks good to me. Are we good to merge on this one?
