### PR TITLE
Fix repetitive diagnosis output in init response

### LINKED ISSUE #1812: tofu init response repetitive diags when configuration has extra label
### OpenTofu Version

```shell
Any/Latest
```

### OpenTofu Configuration Files

```hcl
terraform {
  extra_label{
    required_providers {
      azurerm = {
        source  = "hashicorp/azurerm"
        version = "~> 3.0.2"
      }
    }
  }
}
```

### Debug Output

2024-07-12T10:59:02.775+0800 [INFO]  OpenTofu version: 1.8.0 dev
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/opentofu/hcl/v2 v2.0.0-20240416130056-03228b26f391
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/zclconf/go-cty v1.14.4
2024-07-12T10:59:02.784+0800 [INFO]  Go runtime version: go1.21.4
2024-07-12T10:59:02.784+0800 [INFO]  CLI args: []string{"E:\\Test_workspace\\test-template\\test-it\\tofu.exe", "init"}
2024-07-12T10:59:02.787+0800 [DEBUG] Attempting to open CLI config file: C:\Users\AppData\Roaming\terraform.rc
2024-07-12T10:59:02.787+0800 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-07-12T10:59:02.787+0800 [DEBUG] checking for credentials in "C:\\Users\\AppData\\Roaming\\terraform.d\\plugins"
2024-07-12T10:59:02.787+0800 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-07-12T10:59:02.787+0800 [DEBUG] will search for provider plugins in C:\Users\AppData\Roaming\terraform.d\plugins
2024-07-12T10:59:02.790+0800 [DEBUG] ignoring non-existing provider search directory C:\Users\AppData\Roaming\HashiCorp\Terraform\plugins
2024-07-12T10:59:02.791+0800 [DEBUG] Found the config directory: C:\Users\AppData\Roaming\terraform.d
2024-07-12T10:59:02.791+0800 [INFO]  CLI command args: []string{"init"}

### Expected Behavior

The configuration diags should only occur once

### Actual Behavior

$ ./tofu.exe init

Initializing the backend...
OpenTofu encountered problems during initialization, including problems
with the configuration, described below.

The OpenTofu configuration must be valid before initialization so that
OpenTofu can determine which modules and providers need to be installed.
╷
│ Error: Unsupported block type
│
│   on main.tf line 2, in terraform:
│    2:   extra_label{
│
│ Blocks of type "extra_label" are not expected here.
╵

╷
│ Error: Unsupported block type
│
│   on main.tf line 2, in terraform:
│    2:   extra_label{
│
│ Blocks of type "extra_label" are not expected here.

### Steps to Reproduce

tofu init

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by buraksenn**
In the issue #1812 it was explained and demonstrated clearly that init response was outputting duplicate diagnosis error. I have added `Merge` method to diagnostics to not add exact equal diagnostics to prevent duplicates.

Resolves #1812 

## Target Release

1.9.0

## Checklist
- [X] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [X] I have not used an AI coding assistant to create this PR.
- [X] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.

### Go checklist
- [X] I have run golangci-lint on my change and receive no errors relevant to my code.
- [X] I have run existing tests to ensure my code doesn't break anything.
- [X] I have added tests for all relevant use cases of my code, and those tests are passing.
- [X] I have only exported functions, variables and structs that should be used from other packages.
- [X] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

**Review by ollevche — CHANGES_REQUESTED** [review]
Hey @buraksenn, thank you for working on this issue!

Ignoring `backDiags` when we print `earlyConfDiags` may require users to run init multiple times just to find out there are more errors that need fixing.

I would suggest trying to consolidate those diags even if they are errors. It needs to be done delicately so we don't silence any useful messages, that are not duplicated.

That will also help with failed tests, since we don't change the existing behaviour. 

Happy to answer any questions and discuss potential concerns!

**Comment by buraksenn** [comment]
> Hey @buraksenn, thank you for working on this issue!
> 
> Ignoring `backDiags` when we print `earlyConfDiags` may require users to run init multiple times just to find out there are more errors that need fixing.
> 
> I would suggest trying to consolidate those diags even if they are errors. It needs to be done delicately so we don't silence any useful messages, that are not duplicated.
> 
> That will also help with failed tests, since we don't change the existing behaviour.
> 
> Happy to answer any questions and discuss potential concerns!

That made sense to me as well but I saw that we are not consolidation error level if source is nil so thought that this would be the fix. Then the resolution would be to expand consolidateWarnings or add another method such as consolidateErrors to prevent duplicates right @ollevche ?

**Comment by cam72cam** [comment]
Hmm, I've done some related work on one of my branches: https://github.com/opentofu/opentofu/commit/032c9ff91d0f2c1de4e0b8b4a54e17629a97cbd8#diff-cb9acfeab1fa4de42a8453d53172343075c9db7dfbd41d59569050760f455132

I can take some time today to get that PR ready for review.  It could make sense to rebase this work on top of my changes once they are reviewed and merged.

**Comment by Ericwww** [comment]
I would also prefer the opinion that consolidate duplicated error. For some details, we could have a discussion on how to judge diagnostics is equal (or duplicated) 😄

**Comment by cam72cam** [comment]
Long term, we should revise how and where we are loading configuration (only once).  That depends on a *lot* of refactoring in the command package that we have not had time to start or review.

The question is do we want to do a "generic" merge like in https://github.com/opentofu/opentofu/pull/1894 or do we want to have a more explicit "merge between these two sets" logic, which might make more sense here.

**Comment by cam72cam** [comment]
> I agree it makes more sense to have some explicit merge logic, that will result in a unique diag list from the previous two (backDiags and earlyConfDiags).

In that case @ollevche, it probably wouldn't make sense for this PR to be based on mine, though it could be used as a reference.

**Comment by buraksenn** [comment]
So I'm not sure which approach I should take right now. I would be glad to do the work related to consolidating etc but it would be great to clarify the approach. @cam72cam should I wait for your PR to be merged to continue?

**Comment by cam72cam** [comment]
@buraksenn You should be able to continue on this branch with the approach of merging two different lists of diagnostics, removing any exact duplicates.  This would probably look something like:
`diags = diags.Append(earlyConfDiags.Merge(backDiags))`

**Comment by buraksenn** [comment]
> @buraksenn You should be able to continue on this branch with the approach of merging two different lists of diagnostics, removing any exact duplicates. This would probably look something like: `diags = diags.Append(earlyConfDiags.Merge(backDiags))`

Thanks @cam72cam , I will continue with this. Appreciate it

File: internal/tfdiags/diagnostics.go [hunk 1]
```diff
@@ -101,6 +102,23 @@ func (diags Diagnostics) Append(new ...interface{}) Diagnostics {
...
 }
 
+func (diags Diagnostics) Merge(other Diagnostics) Diagnostics {
+	if len(diags) == 0 {
+		return other
+	}
+
+	for _, d := range diags {
+		for _, o := range other {
+			if reflect.DeepEqual(d, o) {
```
Comment (buraksenn) [inline internal/tfdiags/diagnostics.go:112]: I was thinking about adding Equal method but `Diagnostic` interface has many structs/interfaces that also has other struct/interface dependencies. For the comparison check it would become a overkill for adding that much `Equal()` functions to many structs. That's why I have used `reflect.DeepEqual` here

**Comment by buraksenn** [comment]
@ollevche can you review again if possible?

**Comment by ollevche** [comment]
@buraksenn I'll take a look at the PR today. Thank you for working on this one!

File: internal/tfdiags/diagnostics.go (hunk 1 above)
Comment (ollevche) [reply internal/tfdiags/diagnostics.go:112]: `reflect.DeepEqual` feels a bit of an overkill here. Also, it could fail with wrapped diags.

Would you mind adapting the logic in [ConsolidateWarnings](https://github.com/opentofu/opentofu/blob/main/internal/tfdiags/consolidate_warnings.go#L25) here?

I think we can treat two diags as duplicates if:
* their `Severity`s are equal
* their `Source.Subject`s are present and the whole `Source`s are equal
* their `Description`s are equal

I would also check if `DoNotConsolidateDiagnostic` function allows merging the diag.

**Review by ollevche — COMMENTED** [review]
Thank you for the contribution!

It looks pretty good, special kudos for adding a test. However, I think we need to change the comparison logic to something similar to `ConsolidateWarnings`' implementation.

Left a comment with more details.

File: internal/tfdiags/diagnostics.go (hunk 1 above)
Comment (cam72cam) [reply internal/tfdiags/diagnostics.go:112]: I've gone back and forth on this.  We know we are using overlapping code paths to produce duplicate diagnostics.  I'm ok with this being a bit stricter than ConsolidateWarnings.  I think the DeepEqual is probably a bit overkill, but @ollevche's list makes sense, perhaps with the Ranges added as well.

Comment (cam72cam) [reply internal/tfdiags/diagnostics.go:112]: I also think that DoNotConsolidateDiagnostic can be ignored for this particular function, as it is a special purpose function only for this scenario.

File: internal/tfdiags/diagnostics.go [hunk 2]
```diff
@@ -101,6 +102,23 @@ func (diags Diagnostics) Append(new ...interface{}) Diagnostics {
 	return diags
 }
 
+func (diags Diagnostics) Merge(other Diagnostics) Diagnostics {
```
Comment (cam72cam) [inline internal/tfdiags/diagnostics.go:105]: Perhaps name this StrictDedeuplicate or similar to signal that it is made for a very specific purpose?

File: internal/tfdiags/diagnostics.go (hunk 1 above)
Comment (ollevche) [reply internal/tfdiags/diagnostics.go:112]: Yep, I agree `DoNotConsolidateDiagnostic` check is optional here.

> perhaps with the Ranges added as well.

`Source`s should be equal and `Source.Subject`s (ranges) should be non-zero.

Comment (buraksenn) [reply internal/tfdiags/diagnostics.go]: Added Equal() methods to used structs and refactored the function

File: internal/tfdiags/diagnostics.go (hunk 2 above)
Comment (buraksenn) [reply internal/tfdiags/diagnostics.go]: Changed it to StrictDeduplicateMerge

**Review by cam72cam — APPROVED** [review]

File: internal/tfdiags/diagnostics.go [hunk 3]
```diff
@@ -101,6 +101,23 @@ func (diags Diagnostics) Append(new ...interface{}) Diagnostics {
 	return diags
 }
 
+func (diags Diagnostics) StrictDeduplicateMerge(other Diagnostics) Diagnostics {
```
Comment (ollevche) [inline internal/tfdiags/diagnostics.go:104]: Can we say that diags are duplicates if there is no source range set in them?

Those diags (same description and severity) could reference different parts of configuration and should not be treated as duplicates.

Comment (cam72cam) [reply internal/tfdiags/diagnostics.go:104]: If everything else is identical, and there is no source range, I don't see how hiding one of two duplicate errors would cause any difficulty.

**Review by ollevche — APPROVED** [review]

**Comment by cam72cam** [comment]
Thanks @buraksenn !
