### PR TITLE
Fix: Allow function calls in test variable blocks (#2947)

### LINKED ISSUE #2947: Allow function calls in test variable blocks.
### Community note

> [!TIP]
> 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

### OpenTofu Version

```shell
1.9.1
```

### The problem in your OpenTofu project

I want to use function calls in tofu tests, e.g. using `jsonencode` to build a json string, etc etc.

```hcl
❯ cat main.tf
variable "foo" {
  type = string
}
❯ cat tests/foo.tftest.hcl
run "test" {
  variables {
    foo = jsonencode(["bar", "baz"])
  }
}
```

```
❯ tofu test
tests/foo.tftest.hcl... fail
  run "test"... fail
╷
│ Error: No value for required variable
│ 
│   on main.tf line 1:
│    1: variable "foo" {
│ 
│ The root module input variable "foo" is not set, and has no default value. Use a -var or -var-file command line argument
│ to provide a value for this variable.
╵
╷
│ Error: Function calls not allowed
│ 
│   on tests/foo.tftest.hcl line 3, in run "test":
│    3:     foo = jsonencode(["bar", "baz"])
│ 
│ Functions may not be called here.
╵
```

### Attempted Solutions

not using function calls

### Proposal

allow function calls

### Workarounds and Alternatives

use terraform

### References

_No response_

### PR DESCRIPTION
**Pull request by kasulani**
Add function definitions to the evaluation context in getEvalContextForTest to enable the use of functions like jsonencode in .tftest.hcl variable blocks.

Add a test case to verify that function calls in test variable blocks work properly.

The implementation to support function calls in variables was already present in the codebase, but was missing a test to verify the functionality.

Resolves #2947

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.
- [x] I (and other contributors to this PR) have not looked at the Terraform source code while implementing this PR.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### Website/documentation checklist

- [x] I have locally started the website as [described here](https://github.com/opentofu/opentofu/blob/main/website/README.md) and checked my changes.

### CODE REVIEW

**Comment by yottta** [comment]
Hi @kasulani, thanks for your submission.

Per our [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md), we don't accept PRs without an associated issue.
Is there such a thing for this PR? If so, please link it in the description of the PR.

File: internal/command/test.go [hunk 1]
```diff
@@ -1205,7 +1207,17 @@ type testVariableValueExpression struct {
 
 func (v testVariableValueExpression) ParseVariableValue(mode configs.VariableParsingMode) (*tofu.InputValue, tfdiags.Diagnostics) {
 	var diags tfdiags.Diagnostics
-	val, hclDiags := v.expr.Value(v.ctx)
+
+	evalCtx := v.ctx
+	if evalCtx.Functions == nil {
```
Comment (cam72cam) [inline internal/command/test.go]: Tracing through the code, it looks the change to getEvalContextForTest solves this issue.  In what scenario are we creating a testVariableValueExpression without using getEvalContextForTest() for the ctx?

**Comment by cam72cam** [comment]
@yottta they are assigned to https://github.com/opentofu/opentofu/issues/2947.  They still need a changelog entry and to link to that issue.

File: internal/command/test.go (hunk 1 above)
Comment (kasulani) [reply internal/command/test.go]: @cam72cam I have scanned through the code and I don't see any scenario the `testVariableValueExpression` without invoking `getEvalContextForTest` first to create the ctx. Should I remove this check?

Comment (cam72cam) [reply internal/command/test.go]: Sounds reasonable, thanks!

**Comment by kasulani** [comment]
> @yottta they are assigned to #2947. They still need a changelog entry and to link to that issue.
@cam72cam I have added a changelog entry for this issue into the `CHANGELOG.md` file.

File: internal/command/test.go (hunk 1 above)
Comment (kasulani) [reply internal/command/test.go]: @cam72cam is there any other issue I have to correct in this PR?

Comment (cam72cam) [reply internal/command/test.go]: I still see that you haven't removed this code.  I believe that only getEvalContextForTest needs to be modified for this PR.
