### PR TITLE
Better handling of key_provider references

### LINKED ISSUE #1918: opentofu crashed when using list index operator in pbkdf2 passphrase
### OpenTofu Version

```shell
OpenTofu v1.8.0
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
variable "passphrase" {
  default = "changeme!changeme!"
}

variable "passphrase_list" {
  default = ["changeme!changeme!"]
}

terraform {
  encryption {
    key_provider "pbkdf2" "mykey" {
      passphrase = var.passphrase_list[0]
    }

    method "aes_gcm" "new_method" {
      keys = key_provider.pbkdf2.mykey
    }

    state {
      method = method.aes_gcm.new_method
    }
  }
}
```

### Debug Output

❯ TF_LOG=trace tofu apply
2024-08-14T23:20:31.432+0800 [INFO]  OpenTofu version: 1.8.0
2024-08-14T23:20:31.432+0800 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2024-08-14T23:20:31.432+0800 [DEBUG] using github.com/opentofu/hcl/v2 v2.0.0-20240416130056-03228b26f391
2024-08-14T23:20:31.432+0800 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-08-14T23:20:31.432+0800 [DEBUG] using github.com/zclconf/go-cty v1.14.4
2024-08-14T23:20:31.432+0800 [INFO]  Go runtime version: go1.22.5
2024-08-14T23:20:31.432+0800 [INFO]  CLI args: []string{"tofu", "apply"}
2024-08-14T23:20:31.432+0800 [TRACE] Stdout is a terminal of width 150
2024-08-14T23:20:31.432+0800 [TRACE] Stderr is a terminal of width 150
2024-08-14T23:20:31.432+0800 [TRACE] Stdin is a terminal
2024-08-14T23:20:31.432+0800 [DEBUG] Attempting to open CLI config file: /home/vac/.tofurc
2024-08-14T23:20:31.432+0800 [INFO]  Loading CLI configuration from /home/vac/.tofurc
2024-08-14T23:20:31.432+0800 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-08-14T23:20:31.432+0800 [DEBUG] ignoring non-existing provider search directory /home/vac/.terraform.d/plugins
2024-08-14T23:20:31.432+0800 [DEBUG] ignoring non-existing provider search directory /home/vac/.local/share/terraform/plugins
2024-08-14T23:20:31.432+0800 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2024-08-14T23:20:31.432+0800 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2024-08-14T23:20:31.432+0800 [DEBUG] ignoring non-existing provider search directory /home/vac/.nix-profile/share/terraform/plugins
2024-08-14T23:20:31.432+0800 [DEBUG] ignoring non-existing provider search directory /nix/var/nix/profiles/default/share/terraform/plugins
2024-08-14T23:20:31.432+0800 [DEBUG] Found the config directory: /home/vac/.terraform.d
2024-08-14T23:20:31.432+0800 [INFO]  CLI command args: []string{"apply"}

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

interface conversion: hcl.Traverser is hcl.TraverseIndex, not hcl.TraverseAttr
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x58b3ef3fb720, 0xc000957950}, {0x0, 0x0, 0x0})
        /build/opentofu/src/opentofu-1.8.0/internal/logging/panic.go:96 +0xe5
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        /build/opentofu/src/opentofu-1.8.0/internal/logging/panic.go:51 +0x88
panic({0x58b3ef3fb720?, 0xc000957950?})
        /usr/lib/go/src/runtime/panic.go:770 +0x132
github.com/opentofu/opentofu/internal/encryption.(*targetBuilder).setupKeyProvider(0xc0008bf410, {{0xc00091a1d6, 0x6}, {0xc00091a1ea, 0x5}, {0x58b3ef8b8828, 0xc000950bb0}}, {0x0, 0x0, 0x0})
        /build/opentofu/src/opentofu-1.8.0/internal/encryption/keyprovider.go:133 +0x2205
github.com/opentofu/opentofu/internal/encryption.(*targetBuilder).setupKeyProviders(0xc0008bf410)
        /build/opentofu/src/opentofu-1.8.0/internal/encryption/keyprovider.go:33 +0x176
github.com/opentofu/opentofu/internal/encryption.(*baseEncryption).buildTargetMethods(0xc00077e5f0, 0xc000957650)
        /build/opentofu/src/opentofu-1.8.0/internal/encryption/targets.go:53 +0xff
github.com/opentofu/opentofu/internal/encryption.newBaseEncryption(0xc00077e5a0, 0xc000777020, 0x0, {0x58b3ee7e9348, 0x5}, 0xc00077e550)
        /build/opentofu/src/opentofu-1.8.0/internal/encryption/base.go:72 +0xc8
github.com/opentofu/opentofu/internal/encryption.newStateEncryption(...)
        /build/opentofu/src/opentofu-1.8.0/internal/encryption/state.go:62
github.com/opentofu/opentofu/internal/encryption.New({0x58b3ef8b8b70, 0x58b3f100ebf0}, 0xc0005b0630, 0xc00077e550)
        /build/opentofu/src/opentofu-1.8.0/internal/encryption/encryption.go:56 +0x1b8
github.com/opentofu/opentofu/internal/command.(*Meta).EncryptionFromModule(0xc0009354a0?, 0xc000918200)
        /build/opentofu/src/opentofu-1.8.0/internal/command/meta_encryption.go:55 +0x106
github.com/opentofu/opentofu/internal/command.(*Meta).EncryptionFromPath(0xc0009354a0, {0xc000078004?, 0x0?})
        /build/opentofu/src/opentofu-1.8.0/internal/command/meta_encryption.go:36 +0xbd
github.com/opentofu/opentofu/internal/command.(*Meta).Encryption(0xc0009354a0)
        /build/opentofu/src/opentofu-1.8.0/internal/command/meta_encryption.go:26 +0xb4
github.com/opentofu/opentofu/internal/command.(*ApplyCommand).Run(0xc0009354a0, {0xc000074050, 0x0, 0x0})
        /build/opentofu/src/opentofu-1.8.0/internal/command/apply.go:74 +0x5c7
github.com/mitchellh/cli.(*CLI).Run(0xc000910280)
        /build/opentofu/src/opentofu-1.8.0/vendor/github.com/mitchellh/cli/cli.go:262 +0x5b8
main.realMain()
        /build/opentofu/src/opentofu-1.8.0/cmd/tofu/main.go:347 +0x202b
main.main()
        /build/opentofu/src/opentofu-1.8.0/cmd/tofu/main.go:66 +0x13

### Expected Behavior

No crash.

### Actual Behavior

Opentofu crashed.

### Steps to Reproduce

1. `tofu init` or `tofu plan`

### Additional Context

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by cam72cam**
Fixes detection of key_provider vs variable/local and adds guard-rails around bad key_provider formats

Resolves #1918  

## Target Release

1.9.0, 1.8.x

## Checklist

- [x] I have read the [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md).
- [x] I have not used an AI coding assistant to create this PR.
- [x] I have written all code in this PR myself OR I have marked all code I have not written myself (including modified code, e.g. copied from other places and then modified) with a comment indicating where it came from.

### Go checklist

 

- [x] I have run golangci-lint on my change and receive no errors relevant to my code.
- [x] I have run existing tests to ensure my code doesn't break anything.
- [x] I have added tests for all relevant use cases of my code, and those tests are passing.
- [x] I have only exported functions, variables and structs that should be used from other packages.
- [x] I have added meaningful comments to all exported functions, variables, and structs.

### CODE REVIEW

**Review by Andrew-Hayes — APPROVED** [review]

File: internal/encryption/targets_test.go [hunk 1]
```diff
@@ -145,6 +145,20 @@ func TestBaseEncryption_buildTargetMethods(t *testing.T) {
 			`,
 			wantErr: "Test Config Source:3,12-28: Undefined variable; Undefined variable var.undefinedkey",
 		},
+		"bad-keyprovider-format": {
+			rawConfig: `
+				key_provider "static" "basic" {
+					key = key_provider.static[0]
```
Comment (Evi1Pumpkin) [inline internal/encryption/targets_test.go:151]: Do we also want to add a test for the happy flow when accessing a list var with an index?

Comment (cam72cam) [reply internal/encryption/targets_test.go:167]: Added in [7565b00](https://github.com/opentofu/opentofu/pull/1921/commits/7565b0087f91015d0be669664fb10f4d88ce1496)

**Review by Evi1Pumpkin — APPROVED** [review]
LGTM!

**Review by ollevche — APPROVED** [review]
